// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Contract.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Contract_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_Contract_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4023000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4023004 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "ComboLeg.pb.h"
#include "DeltaNeutralContract.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_Contract_2eproto

PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Contract_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable
    descriptor_table_Contract_2eproto;
namespace protobuf {
class Contract;
struct ContractDefaultTypeInternal;
extern ContractDefaultTypeInternal _Contract_default_instance_;
}  // namespace protobuf
PROTOBUF_NAMESPACE_OPEN
template <>
::protobuf::Contract* Arena::CreateMaybeMessage<::protobuf::Contract>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

namespace protobuf {

// ===================================================================


// -------------------------------------------------------------------

class Contract final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protobuf.Contract) */ {
 public:
  inline Contract() : Contract(nullptr) {}
  ~Contract() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR Contract(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Contract(const Contract& from);
  Contract(Contract&& from) noexcept
    : Contract() {
    *this = ::std::move(from);
  }

  inline Contract& operator=(const Contract& from) {
    CopyFrom(from);
    return *this;
  }
  inline Contract& operator=(Contract&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Contract& default_instance() {
    return *internal_default_instance();
  }
  static inline const Contract* internal_default_instance() {
    return reinterpret_cast<const Contract*>(
               &_Contract_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Contract& a, Contract& b) {
    a.Swap(&b);
  }
  inline void Swap(Contract* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Contract* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Contract* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Contract>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Contract& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Contract& from) {
    Contract::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Contract* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "protobuf.Contract";
  }
  protected:
  explicit Contract(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kComboLegsFieldNumber = 20,
    kSymbolFieldNumber = 2,
    kSecTypeFieldNumber = 3,
    kLastTradeDateOrContractMonthFieldNumber = 4,
    kRightFieldNumber = 6,
    kExchangeFieldNumber = 8,
    kPrimaryExchFieldNumber = 9,
    kCurrencyFieldNumber = 10,
    kLocalSymbolFieldNumber = 11,
    kTradingClassFieldNumber = 12,
    kSecIdTypeFieldNumber = 13,
    kSecIdFieldNumber = 14,
    kDescriptionFieldNumber = 15,
    kIssuerIdFieldNumber = 16,
    kComboLegsDescripFieldNumber = 19,
    kDeltaNeutralContractFieldNumber = 17,
    kStrikeFieldNumber = 5,
    kMultiplierFieldNumber = 7,
    kConIdFieldNumber = 1,
    kIncludeExpiredFieldNumber = 18,
  };
  // repeated .protobuf.ComboLeg comboLegs = 20;
  int combolegs_size() const;
  private:
  int _internal_combolegs_size() const;

  public:
  void clear_combolegs() ;
  ::protobuf::ComboLeg* mutable_combolegs(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protobuf::ComboLeg >*
      mutable_combolegs();
  private:
  const ::protobuf::ComboLeg& _internal_combolegs(int index) const;
  ::protobuf::ComboLeg* _internal_add_combolegs();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::protobuf::ComboLeg>& _internal_combolegs() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::protobuf::ComboLeg>* _internal_mutable_combolegs();
  public:
  const ::protobuf::ComboLeg& combolegs(int index) const;
  ::protobuf::ComboLeg* add_combolegs();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protobuf::ComboLeg >&
      combolegs() const;
  // optional string symbol = 2;
  bool has_symbol() const;
  void clear_symbol() ;
  const std::string& symbol() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_symbol(Arg_&& arg, Args_... args);
  std::string* mutable_symbol();
  PROTOBUF_NODISCARD std::string* release_symbol();
  void set_allocated_symbol(std::string* ptr);

  private:
  const std::string& _internal_symbol() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_symbol(
      const std::string& value);
  std::string* _internal_mutable_symbol();

  public:
  // optional string secType = 3;
  bool has_sectype() const;
  void clear_sectype() ;
  const std::string& sectype() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_sectype(Arg_&& arg, Args_... args);
  std::string* mutable_sectype();
  PROTOBUF_NODISCARD std::string* release_sectype();
  void set_allocated_sectype(std::string* ptr);

  private:
  const std::string& _internal_sectype() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sectype(
      const std::string& value);
  std::string* _internal_mutable_sectype();

  public:
  // optional string lastTradeDateOrContractMonth = 4;
  bool has_lasttradedateorcontractmonth() const;
  void clear_lasttradedateorcontractmonth() ;
  const std::string& lasttradedateorcontractmonth() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_lasttradedateorcontractmonth(Arg_&& arg, Args_... args);
  std::string* mutable_lasttradedateorcontractmonth();
  PROTOBUF_NODISCARD std::string* release_lasttradedateorcontractmonth();
  void set_allocated_lasttradedateorcontractmonth(std::string* ptr);

  private:
  const std::string& _internal_lasttradedateorcontractmonth() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_lasttradedateorcontractmonth(
      const std::string& value);
  std::string* _internal_mutable_lasttradedateorcontractmonth();

  public:
  // optional string right = 6;
  bool has_right() const;
  void clear_right() ;
  const std::string& right() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_right(Arg_&& arg, Args_... args);
  std::string* mutable_right();
  PROTOBUF_NODISCARD std::string* release_right();
  void set_allocated_right(std::string* ptr);

  private:
  const std::string& _internal_right() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_right(
      const std::string& value);
  std::string* _internal_mutable_right();

  public:
  // optional string exchange = 8;
  bool has_exchange() const;
  void clear_exchange() ;
  const std::string& exchange() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_exchange(Arg_&& arg, Args_... args);
  std::string* mutable_exchange();
  PROTOBUF_NODISCARD std::string* release_exchange();
  void set_allocated_exchange(std::string* ptr);

  private:
  const std::string& _internal_exchange() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_exchange(
      const std::string& value);
  std::string* _internal_mutable_exchange();

  public:
  // optional string primaryExch = 9;
  bool has_primaryexch() const;
  void clear_primaryexch() ;
  const std::string& primaryexch() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_primaryexch(Arg_&& arg, Args_... args);
  std::string* mutable_primaryexch();
  PROTOBUF_NODISCARD std::string* release_primaryexch();
  void set_allocated_primaryexch(std::string* ptr);

  private:
  const std::string& _internal_primaryexch() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_primaryexch(
      const std::string& value);
  std::string* _internal_mutable_primaryexch();

  public:
  // optional string currency = 10;
  bool has_currency() const;
  void clear_currency() ;
  const std::string& currency() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_currency(Arg_&& arg, Args_... args);
  std::string* mutable_currency();
  PROTOBUF_NODISCARD std::string* release_currency();
  void set_allocated_currency(std::string* ptr);

  private:
  const std::string& _internal_currency() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_currency(
      const std::string& value);
  std::string* _internal_mutable_currency();

  public:
  // optional string localSymbol = 11;
  bool has_localsymbol() const;
  void clear_localsymbol() ;
  const std::string& localsymbol() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_localsymbol(Arg_&& arg, Args_... args);
  std::string* mutable_localsymbol();
  PROTOBUF_NODISCARD std::string* release_localsymbol();
  void set_allocated_localsymbol(std::string* ptr);

  private:
  const std::string& _internal_localsymbol() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_localsymbol(
      const std::string& value);
  std::string* _internal_mutable_localsymbol();

  public:
  // optional string tradingClass = 12;
  bool has_tradingclass() const;
  void clear_tradingclass() ;
  const std::string& tradingclass() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_tradingclass(Arg_&& arg, Args_... args);
  std::string* mutable_tradingclass();
  PROTOBUF_NODISCARD std::string* release_tradingclass();
  void set_allocated_tradingclass(std::string* ptr);

  private:
  const std::string& _internal_tradingclass() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_tradingclass(
      const std::string& value);
  std::string* _internal_mutable_tradingclass();

  public:
  // optional string secIdType = 13;
  bool has_secidtype() const;
  void clear_secidtype() ;
  const std::string& secidtype() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_secidtype(Arg_&& arg, Args_... args);
  std::string* mutable_secidtype();
  PROTOBUF_NODISCARD std::string* release_secidtype();
  void set_allocated_secidtype(std::string* ptr);

  private:
  const std::string& _internal_secidtype() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_secidtype(
      const std::string& value);
  std::string* _internal_mutable_secidtype();

  public:
  // optional string secId = 14;
  bool has_secid() const;
  void clear_secid() ;
  const std::string& secid() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_secid(Arg_&& arg, Args_... args);
  std::string* mutable_secid();
  PROTOBUF_NODISCARD std::string* release_secid();
  void set_allocated_secid(std::string* ptr);

  private:
  const std::string& _internal_secid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_secid(
      const std::string& value);
  std::string* _internal_mutable_secid();

  public:
  // optional string description = 15;
  bool has_description() const;
  void clear_description() ;
  const std::string& description() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_description(Arg_&& arg, Args_... args);
  std::string* mutable_description();
  PROTOBUF_NODISCARD std::string* release_description();
  void set_allocated_description(std::string* ptr);

  private:
  const std::string& _internal_description() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_description(
      const std::string& value);
  std::string* _internal_mutable_description();

  public:
  // optional string issuerId = 16;
  bool has_issuerid() const;
  void clear_issuerid() ;
  const std::string& issuerid() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_issuerid(Arg_&& arg, Args_... args);
  std::string* mutable_issuerid();
  PROTOBUF_NODISCARD std::string* release_issuerid();
  void set_allocated_issuerid(std::string* ptr);

  private:
  const std::string& _internal_issuerid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_issuerid(
      const std::string& value);
  std::string* _internal_mutable_issuerid();

  public:
  // optional string comboLegsDescrip = 19;
  bool has_combolegsdescrip() const;
  void clear_combolegsdescrip() ;
  const std::string& combolegsdescrip() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_combolegsdescrip(Arg_&& arg, Args_... args);
  std::string* mutable_combolegsdescrip();
  PROTOBUF_NODISCARD std::string* release_combolegsdescrip();
  void set_allocated_combolegsdescrip(std::string* ptr);

  private:
  const std::string& _internal_combolegsdescrip() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_combolegsdescrip(
      const std::string& value);
  std::string* _internal_mutable_combolegsdescrip();

  public:
  // optional .protobuf.DeltaNeutralContract deltaNeutralContract = 17;
  bool has_deltaneutralcontract() const;
  void clear_deltaneutralcontract() ;
  const ::protobuf::DeltaNeutralContract& deltaneutralcontract() const;
  PROTOBUF_NODISCARD ::protobuf::DeltaNeutralContract* release_deltaneutralcontract();
  ::protobuf::DeltaNeutralContract* mutable_deltaneutralcontract();
  void set_allocated_deltaneutralcontract(::protobuf::DeltaNeutralContract* deltaneutralcontract);
  private:
  const ::protobuf::DeltaNeutralContract& _internal_deltaneutralcontract() const;
  ::protobuf::DeltaNeutralContract* _internal_mutable_deltaneutralcontract();
  public:
  void unsafe_arena_set_allocated_deltaneutralcontract(
      ::protobuf::DeltaNeutralContract* deltaneutralcontract);
  ::protobuf::DeltaNeutralContract* unsafe_arena_release_deltaneutralcontract();
  // optional double strike = 5;
  bool has_strike() const;
  void clear_strike() ;
  double strike() const;
  void set_strike(double value);

  private:
  double _internal_strike() const;
  void _internal_set_strike(double value);

  public:
  // optional double multiplier = 7;
  bool has_multiplier() const;
  void clear_multiplier() ;
  double multiplier() const;
  void set_multiplier(double value);

  private:
  double _internal_multiplier() const;
  void _internal_set_multiplier(double value);

  public:
  // optional int32 conId = 1;
  bool has_conid() const;
  void clear_conid() ;
  ::int32_t conid() const;
  void set_conid(::int32_t value);

  private:
  ::int32_t _internal_conid() const;
  void _internal_set_conid(::int32_t value);

  public:
  // optional bool includeExpired = 18;
  bool has_includeexpired() const;
  void clear_includeexpired() ;
  bool includeexpired() const;
  void set_includeexpired(bool value);

  private:
  bool _internal_includeexpired() const;
  void _internal_set_includeexpired(bool value);

  public:
  // @@protoc_insertion_point(class_scope:protobuf.Contract)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protobuf::ComboLeg > combolegs_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr symbol_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sectype_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr lasttradedateorcontractmonth_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr right_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr exchange_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr primaryexch_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr currency_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr localsymbol_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr tradingclass_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr secidtype_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr secid_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr description_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr issuerid_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr combolegsdescrip_;
    ::protobuf::DeltaNeutralContract* deltaneutralcontract_;
    double strike_;
    double multiplier_;
    ::int32_t conid_;
    bool includeexpired_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Contract_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Contract

// optional int32 conId = 1;
inline bool Contract::has_conid() const {
  bool value = (_impl_._has_bits_[0] & 0x00020000u) != 0;
  return value;
}
inline void Contract::clear_conid() {
  _impl_.conid_ = 0;
  _impl_._has_bits_[0] &= ~0x00020000u;
}
inline ::int32_t Contract::conid() const {
  // @@protoc_insertion_point(field_get:protobuf.Contract.conId)
  return _internal_conid();
}
inline void Contract::set_conid(::int32_t value) {
  _internal_set_conid(value);
  // @@protoc_insertion_point(field_set:protobuf.Contract.conId)
}
inline ::int32_t Contract::_internal_conid() const {
  return _impl_.conid_;
}
inline void Contract::_internal_set_conid(::int32_t value) {
  _impl_._has_bits_[0] |= 0x00020000u;
  _impl_.conid_ = value;
}

// optional string symbol = 2;
inline bool Contract::has_symbol() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void Contract::clear_symbol() {
  _impl_.symbol_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Contract::symbol() const {
  // @@protoc_insertion_point(field_get:protobuf.Contract.symbol)
  return _internal_symbol();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Contract::set_symbol(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.symbol_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.Contract.symbol)
}
inline std::string* Contract::mutable_symbol() {
  std::string* _s = _internal_mutable_symbol();
  // @@protoc_insertion_point(field_mutable:protobuf.Contract.symbol)
  return _s;
}
inline const std::string& Contract::_internal_symbol() const {
  return _impl_.symbol_.Get();
}
inline void Contract::_internal_set_symbol(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;


  _impl_.symbol_.Set(value, GetArenaForAllocation());
}
inline std::string* Contract::_internal_mutable_symbol() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.symbol_.Mutable( GetArenaForAllocation());
}
inline std::string* Contract::release_symbol() {
  // @@protoc_insertion_point(field_release:protobuf.Contract.symbol)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.symbol_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.symbol_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void Contract::set_allocated_symbol(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.symbol_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.symbol_.IsDefault()) {
          _impl_.symbol_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.Contract.symbol)
}

// optional string secType = 3;
inline bool Contract::has_sectype() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void Contract::clear_sectype() {
  _impl_.sectype_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& Contract::sectype() const {
  // @@protoc_insertion_point(field_get:protobuf.Contract.secType)
  return _internal_sectype();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Contract::set_sectype(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.sectype_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.Contract.secType)
}
inline std::string* Contract::mutable_sectype() {
  std::string* _s = _internal_mutable_sectype();
  // @@protoc_insertion_point(field_mutable:protobuf.Contract.secType)
  return _s;
}
inline const std::string& Contract::_internal_sectype() const {
  return _impl_.sectype_.Get();
}
inline void Contract::_internal_set_sectype(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000002u;


  _impl_.sectype_.Set(value, GetArenaForAllocation());
}
inline std::string* Contract::_internal_mutable_sectype() {
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.sectype_.Mutable( GetArenaForAllocation());
}
inline std::string* Contract::release_sectype() {
  // @@protoc_insertion_point(field_release:protobuf.Contract.secType)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.sectype_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.sectype_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void Contract::set_allocated_sectype(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.sectype_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.sectype_.IsDefault()) {
          _impl_.sectype_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.Contract.secType)
}

// optional string lastTradeDateOrContractMonth = 4;
inline bool Contract::has_lasttradedateorcontractmonth() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void Contract::clear_lasttradedateorcontractmonth() {
  _impl_.lasttradedateorcontractmonth_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const std::string& Contract::lasttradedateorcontractmonth() const {
  // @@protoc_insertion_point(field_get:protobuf.Contract.lastTradeDateOrContractMonth)
  return _internal_lasttradedateorcontractmonth();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Contract::set_lasttradedateorcontractmonth(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.lasttradedateorcontractmonth_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.Contract.lastTradeDateOrContractMonth)
}
inline std::string* Contract::mutable_lasttradedateorcontractmonth() {
  std::string* _s = _internal_mutable_lasttradedateorcontractmonth();
  // @@protoc_insertion_point(field_mutable:protobuf.Contract.lastTradeDateOrContractMonth)
  return _s;
}
inline const std::string& Contract::_internal_lasttradedateorcontractmonth() const {
  return _impl_.lasttradedateorcontractmonth_.Get();
}
inline void Contract::_internal_set_lasttradedateorcontractmonth(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000004u;


  _impl_.lasttradedateorcontractmonth_.Set(value, GetArenaForAllocation());
}
inline std::string* Contract::_internal_mutable_lasttradedateorcontractmonth() {
  _impl_._has_bits_[0] |= 0x00000004u;
  return _impl_.lasttradedateorcontractmonth_.Mutable( GetArenaForAllocation());
}
inline std::string* Contract::release_lasttradedateorcontractmonth() {
  // @@protoc_insertion_point(field_release:protobuf.Contract.lastTradeDateOrContractMonth)
  if ((_impl_._has_bits_[0] & 0x00000004u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004u;
  auto* released = _impl_.lasttradedateorcontractmonth_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.lasttradedateorcontractmonth_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void Contract::set_allocated_lasttradedateorcontractmonth(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.lasttradedateorcontractmonth_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.lasttradedateorcontractmonth_.IsDefault()) {
          _impl_.lasttradedateorcontractmonth_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.Contract.lastTradeDateOrContractMonth)
}

// optional double strike = 5;
inline bool Contract::has_strike() const {
  bool value = (_impl_._has_bits_[0] & 0x00008000u) != 0;
  return value;
}
inline void Contract::clear_strike() {
  _impl_.strike_ = 0;
  _impl_._has_bits_[0] &= ~0x00008000u;
}
inline double Contract::strike() const {
  // @@protoc_insertion_point(field_get:protobuf.Contract.strike)
  return _internal_strike();
}
inline void Contract::set_strike(double value) {
  _internal_set_strike(value);
  // @@protoc_insertion_point(field_set:protobuf.Contract.strike)
}
inline double Contract::_internal_strike() const {
  return _impl_.strike_;
}
inline void Contract::_internal_set_strike(double value) {
  _impl_._has_bits_[0] |= 0x00008000u;
  _impl_.strike_ = value;
}

// optional string right = 6;
inline bool Contract::has_right() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void Contract::clear_right() {
  _impl_.right_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline const std::string& Contract::right() const {
  // @@protoc_insertion_point(field_get:protobuf.Contract.right)
  return _internal_right();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Contract::set_right(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.right_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.Contract.right)
}
inline std::string* Contract::mutable_right() {
  std::string* _s = _internal_mutable_right();
  // @@protoc_insertion_point(field_mutable:protobuf.Contract.right)
  return _s;
}
inline const std::string& Contract::_internal_right() const {
  return _impl_.right_.Get();
}
inline void Contract::_internal_set_right(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000008u;


  _impl_.right_.Set(value, GetArenaForAllocation());
}
inline std::string* Contract::_internal_mutable_right() {
  _impl_._has_bits_[0] |= 0x00000008u;
  return _impl_.right_.Mutable( GetArenaForAllocation());
}
inline std::string* Contract::release_right() {
  // @@protoc_insertion_point(field_release:protobuf.Contract.right)
  if ((_impl_._has_bits_[0] & 0x00000008u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000008u;
  auto* released = _impl_.right_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.right_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void Contract::set_allocated_right(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  _impl_.right_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.right_.IsDefault()) {
          _impl_.right_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.Contract.right)
}

// optional double multiplier = 7;
inline bool Contract::has_multiplier() const {
  bool value = (_impl_._has_bits_[0] & 0x00010000u) != 0;
  return value;
}
inline void Contract::clear_multiplier() {
  _impl_.multiplier_ = 0;
  _impl_._has_bits_[0] &= ~0x00010000u;
}
inline double Contract::multiplier() const {
  // @@protoc_insertion_point(field_get:protobuf.Contract.multiplier)
  return _internal_multiplier();
}
inline void Contract::set_multiplier(double value) {
  _internal_set_multiplier(value);
  // @@protoc_insertion_point(field_set:protobuf.Contract.multiplier)
}
inline double Contract::_internal_multiplier() const {
  return _impl_.multiplier_;
}
inline void Contract::_internal_set_multiplier(double value) {
  _impl_._has_bits_[0] |= 0x00010000u;
  _impl_.multiplier_ = value;
}

// optional string exchange = 8;
inline bool Contract::has_exchange() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline void Contract::clear_exchange() {
  _impl_.exchange_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline const std::string& Contract::exchange() const {
  // @@protoc_insertion_point(field_get:protobuf.Contract.exchange)
  return _internal_exchange();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Contract::set_exchange(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.exchange_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.Contract.exchange)
}
inline std::string* Contract::mutable_exchange() {
  std::string* _s = _internal_mutable_exchange();
  // @@protoc_insertion_point(field_mutable:protobuf.Contract.exchange)
  return _s;
}
inline const std::string& Contract::_internal_exchange() const {
  return _impl_.exchange_.Get();
}
inline void Contract::_internal_set_exchange(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000010u;


  _impl_.exchange_.Set(value, GetArenaForAllocation());
}
inline std::string* Contract::_internal_mutable_exchange() {
  _impl_._has_bits_[0] |= 0x00000010u;
  return _impl_.exchange_.Mutable( GetArenaForAllocation());
}
inline std::string* Contract::release_exchange() {
  // @@protoc_insertion_point(field_release:protobuf.Contract.exchange)
  if ((_impl_._has_bits_[0] & 0x00000010u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000010u;
  auto* released = _impl_.exchange_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.exchange_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void Contract::set_allocated_exchange(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000010u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000010u;
  }
  _impl_.exchange_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.exchange_.IsDefault()) {
          _impl_.exchange_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.Contract.exchange)
}

// optional string primaryExch = 9;
inline bool Contract::has_primaryexch() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline void Contract::clear_primaryexch() {
  _impl_.primaryexch_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline const std::string& Contract::primaryexch() const {
  // @@protoc_insertion_point(field_get:protobuf.Contract.primaryExch)
  return _internal_primaryexch();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Contract::set_primaryexch(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000020u;
  _impl_.primaryexch_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.Contract.primaryExch)
}
inline std::string* Contract::mutable_primaryexch() {
  std::string* _s = _internal_mutable_primaryexch();
  // @@protoc_insertion_point(field_mutable:protobuf.Contract.primaryExch)
  return _s;
}
inline const std::string& Contract::_internal_primaryexch() const {
  return _impl_.primaryexch_.Get();
}
inline void Contract::_internal_set_primaryexch(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000020u;


  _impl_.primaryexch_.Set(value, GetArenaForAllocation());
}
inline std::string* Contract::_internal_mutable_primaryexch() {
  _impl_._has_bits_[0] |= 0x00000020u;
  return _impl_.primaryexch_.Mutable( GetArenaForAllocation());
}
inline std::string* Contract::release_primaryexch() {
  // @@protoc_insertion_point(field_release:protobuf.Contract.primaryExch)
  if ((_impl_._has_bits_[0] & 0x00000020u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000020u;
  auto* released = _impl_.primaryexch_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.primaryexch_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void Contract::set_allocated_primaryexch(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000020u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000020u;
  }
  _impl_.primaryexch_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.primaryexch_.IsDefault()) {
          _impl_.primaryexch_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.Contract.primaryExch)
}

// optional string currency = 10;
inline bool Contract::has_currency() const {
  bool value = (_impl_._has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline void Contract::clear_currency() {
  _impl_.currency_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000040u;
}
inline const std::string& Contract::currency() const {
  // @@protoc_insertion_point(field_get:protobuf.Contract.currency)
  return _internal_currency();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Contract::set_currency(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000040u;
  _impl_.currency_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.Contract.currency)
}
inline std::string* Contract::mutable_currency() {
  std::string* _s = _internal_mutable_currency();
  // @@protoc_insertion_point(field_mutable:protobuf.Contract.currency)
  return _s;
}
inline const std::string& Contract::_internal_currency() const {
  return _impl_.currency_.Get();
}
inline void Contract::_internal_set_currency(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000040u;


  _impl_.currency_.Set(value, GetArenaForAllocation());
}
inline std::string* Contract::_internal_mutable_currency() {
  _impl_._has_bits_[0] |= 0x00000040u;
  return _impl_.currency_.Mutable( GetArenaForAllocation());
}
inline std::string* Contract::release_currency() {
  // @@protoc_insertion_point(field_release:protobuf.Contract.currency)
  if ((_impl_._has_bits_[0] & 0x00000040u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000040u;
  auto* released = _impl_.currency_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.currency_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void Contract::set_allocated_currency(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000040u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000040u;
  }
  _impl_.currency_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.currency_.IsDefault()) {
          _impl_.currency_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.Contract.currency)
}

// optional string localSymbol = 11;
inline bool Contract::has_localsymbol() const {
  bool value = (_impl_._has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline void Contract::clear_localsymbol() {
  _impl_.localsymbol_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000080u;
}
inline const std::string& Contract::localsymbol() const {
  // @@protoc_insertion_point(field_get:protobuf.Contract.localSymbol)
  return _internal_localsymbol();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Contract::set_localsymbol(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000080u;
  _impl_.localsymbol_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.Contract.localSymbol)
}
inline std::string* Contract::mutable_localsymbol() {
  std::string* _s = _internal_mutable_localsymbol();
  // @@protoc_insertion_point(field_mutable:protobuf.Contract.localSymbol)
  return _s;
}
inline const std::string& Contract::_internal_localsymbol() const {
  return _impl_.localsymbol_.Get();
}
inline void Contract::_internal_set_localsymbol(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000080u;


  _impl_.localsymbol_.Set(value, GetArenaForAllocation());
}
inline std::string* Contract::_internal_mutable_localsymbol() {
  _impl_._has_bits_[0] |= 0x00000080u;
  return _impl_.localsymbol_.Mutable( GetArenaForAllocation());
}
inline std::string* Contract::release_localsymbol() {
  // @@protoc_insertion_point(field_release:protobuf.Contract.localSymbol)
  if ((_impl_._has_bits_[0] & 0x00000080u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000080u;
  auto* released = _impl_.localsymbol_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.localsymbol_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void Contract::set_allocated_localsymbol(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000080u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000080u;
  }
  _impl_.localsymbol_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.localsymbol_.IsDefault()) {
          _impl_.localsymbol_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.Contract.localSymbol)
}

// optional string tradingClass = 12;
inline bool Contract::has_tradingclass() const {
  bool value = (_impl_._has_bits_[0] & 0x00000100u) != 0;
  return value;
}
inline void Contract::clear_tradingclass() {
  _impl_.tradingclass_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000100u;
}
inline const std::string& Contract::tradingclass() const {
  // @@protoc_insertion_point(field_get:protobuf.Contract.tradingClass)
  return _internal_tradingclass();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Contract::set_tradingclass(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000100u;
  _impl_.tradingclass_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.Contract.tradingClass)
}
inline std::string* Contract::mutable_tradingclass() {
  std::string* _s = _internal_mutable_tradingclass();
  // @@protoc_insertion_point(field_mutable:protobuf.Contract.tradingClass)
  return _s;
}
inline const std::string& Contract::_internal_tradingclass() const {
  return _impl_.tradingclass_.Get();
}
inline void Contract::_internal_set_tradingclass(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000100u;


  _impl_.tradingclass_.Set(value, GetArenaForAllocation());
}
inline std::string* Contract::_internal_mutable_tradingclass() {
  _impl_._has_bits_[0] |= 0x00000100u;
  return _impl_.tradingclass_.Mutable( GetArenaForAllocation());
}
inline std::string* Contract::release_tradingclass() {
  // @@protoc_insertion_point(field_release:protobuf.Contract.tradingClass)
  if ((_impl_._has_bits_[0] & 0x00000100u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000100u;
  auto* released = _impl_.tradingclass_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.tradingclass_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void Contract::set_allocated_tradingclass(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000100u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000100u;
  }
  _impl_.tradingclass_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.tradingclass_.IsDefault()) {
          _impl_.tradingclass_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.Contract.tradingClass)
}

// optional string secIdType = 13;
inline bool Contract::has_secidtype() const {
  bool value = (_impl_._has_bits_[0] & 0x00000200u) != 0;
  return value;
}
inline void Contract::clear_secidtype() {
  _impl_.secidtype_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000200u;
}
inline const std::string& Contract::secidtype() const {
  // @@protoc_insertion_point(field_get:protobuf.Contract.secIdType)
  return _internal_secidtype();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Contract::set_secidtype(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000200u;
  _impl_.secidtype_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.Contract.secIdType)
}
inline std::string* Contract::mutable_secidtype() {
  std::string* _s = _internal_mutable_secidtype();
  // @@protoc_insertion_point(field_mutable:protobuf.Contract.secIdType)
  return _s;
}
inline const std::string& Contract::_internal_secidtype() const {
  return _impl_.secidtype_.Get();
}
inline void Contract::_internal_set_secidtype(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000200u;


  _impl_.secidtype_.Set(value, GetArenaForAllocation());
}
inline std::string* Contract::_internal_mutable_secidtype() {
  _impl_._has_bits_[0] |= 0x00000200u;
  return _impl_.secidtype_.Mutable( GetArenaForAllocation());
}
inline std::string* Contract::release_secidtype() {
  // @@protoc_insertion_point(field_release:protobuf.Contract.secIdType)
  if ((_impl_._has_bits_[0] & 0x00000200u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000200u;
  auto* released = _impl_.secidtype_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.secidtype_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void Contract::set_allocated_secidtype(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000200u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000200u;
  }
  _impl_.secidtype_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.secidtype_.IsDefault()) {
          _impl_.secidtype_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.Contract.secIdType)
}

// optional string secId = 14;
inline bool Contract::has_secid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000400u) != 0;
  return value;
}
inline void Contract::clear_secid() {
  _impl_.secid_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000400u;
}
inline const std::string& Contract::secid() const {
  // @@protoc_insertion_point(field_get:protobuf.Contract.secId)
  return _internal_secid();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Contract::set_secid(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000400u;
  _impl_.secid_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.Contract.secId)
}
inline std::string* Contract::mutable_secid() {
  std::string* _s = _internal_mutable_secid();
  // @@protoc_insertion_point(field_mutable:protobuf.Contract.secId)
  return _s;
}
inline const std::string& Contract::_internal_secid() const {
  return _impl_.secid_.Get();
}
inline void Contract::_internal_set_secid(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000400u;


  _impl_.secid_.Set(value, GetArenaForAllocation());
}
inline std::string* Contract::_internal_mutable_secid() {
  _impl_._has_bits_[0] |= 0x00000400u;
  return _impl_.secid_.Mutable( GetArenaForAllocation());
}
inline std::string* Contract::release_secid() {
  // @@protoc_insertion_point(field_release:protobuf.Contract.secId)
  if ((_impl_._has_bits_[0] & 0x00000400u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000400u;
  auto* released = _impl_.secid_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.secid_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void Contract::set_allocated_secid(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000400u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000400u;
  }
  _impl_.secid_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.secid_.IsDefault()) {
          _impl_.secid_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.Contract.secId)
}

// optional string description = 15;
inline bool Contract::has_description() const {
  bool value = (_impl_._has_bits_[0] & 0x00000800u) != 0;
  return value;
}
inline void Contract::clear_description() {
  _impl_.description_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000800u;
}
inline const std::string& Contract::description() const {
  // @@protoc_insertion_point(field_get:protobuf.Contract.description)
  return _internal_description();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Contract::set_description(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000800u;
  _impl_.description_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.Contract.description)
}
inline std::string* Contract::mutable_description() {
  std::string* _s = _internal_mutable_description();
  // @@protoc_insertion_point(field_mutable:protobuf.Contract.description)
  return _s;
}
inline const std::string& Contract::_internal_description() const {
  return _impl_.description_.Get();
}
inline void Contract::_internal_set_description(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000800u;


  _impl_.description_.Set(value, GetArenaForAllocation());
}
inline std::string* Contract::_internal_mutable_description() {
  _impl_._has_bits_[0] |= 0x00000800u;
  return _impl_.description_.Mutable( GetArenaForAllocation());
}
inline std::string* Contract::release_description() {
  // @@protoc_insertion_point(field_release:protobuf.Contract.description)
  if ((_impl_._has_bits_[0] & 0x00000800u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000800u;
  auto* released = _impl_.description_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.description_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void Contract::set_allocated_description(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000800u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000800u;
  }
  _impl_.description_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.description_.IsDefault()) {
          _impl_.description_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.Contract.description)
}

// optional string issuerId = 16;
inline bool Contract::has_issuerid() const {
  bool value = (_impl_._has_bits_[0] & 0x00001000u) != 0;
  return value;
}
inline void Contract::clear_issuerid() {
  _impl_.issuerid_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00001000u;
}
inline const std::string& Contract::issuerid() const {
  // @@protoc_insertion_point(field_get:protobuf.Contract.issuerId)
  return _internal_issuerid();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Contract::set_issuerid(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00001000u;
  _impl_.issuerid_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.Contract.issuerId)
}
inline std::string* Contract::mutable_issuerid() {
  std::string* _s = _internal_mutable_issuerid();
  // @@protoc_insertion_point(field_mutable:protobuf.Contract.issuerId)
  return _s;
}
inline const std::string& Contract::_internal_issuerid() const {
  return _impl_.issuerid_.Get();
}
inline void Contract::_internal_set_issuerid(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00001000u;


  _impl_.issuerid_.Set(value, GetArenaForAllocation());
}
inline std::string* Contract::_internal_mutable_issuerid() {
  _impl_._has_bits_[0] |= 0x00001000u;
  return _impl_.issuerid_.Mutable( GetArenaForAllocation());
}
inline std::string* Contract::release_issuerid() {
  // @@protoc_insertion_point(field_release:protobuf.Contract.issuerId)
  if ((_impl_._has_bits_[0] & 0x00001000u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00001000u;
  auto* released = _impl_.issuerid_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.issuerid_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void Contract::set_allocated_issuerid(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00001000u;
  } else {
    _impl_._has_bits_[0] &= ~0x00001000u;
  }
  _impl_.issuerid_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.issuerid_.IsDefault()) {
          _impl_.issuerid_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.Contract.issuerId)
}

// optional .protobuf.DeltaNeutralContract deltaNeutralContract = 17;
inline bool Contract::has_deltaneutralcontract() const {
  bool value = (_impl_._has_bits_[0] & 0x00004000u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.deltaneutralcontract_ != nullptr);
  return value;
}
inline const ::protobuf::DeltaNeutralContract& Contract::_internal_deltaneutralcontract() const {
  const ::protobuf::DeltaNeutralContract* p = _impl_.deltaneutralcontract_;
  return p != nullptr ? *p : reinterpret_cast<const ::protobuf::DeltaNeutralContract&>(
      ::protobuf::_DeltaNeutralContract_default_instance_);
}
inline const ::protobuf::DeltaNeutralContract& Contract::deltaneutralcontract() const {
  // @@protoc_insertion_point(field_get:protobuf.Contract.deltaNeutralContract)
  return _internal_deltaneutralcontract();
}
inline void Contract::unsafe_arena_set_allocated_deltaneutralcontract(
    ::protobuf::DeltaNeutralContract* deltaneutralcontract) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.deltaneutralcontract_);
  }
  _impl_.deltaneutralcontract_ = deltaneutralcontract;
  if (deltaneutralcontract) {
    _impl_._has_bits_[0] |= 0x00004000u;
  } else {
    _impl_._has_bits_[0] &= ~0x00004000u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protobuf.Contract.deltaNeutralContract)
}
inline ::protobuf::DeltaNeutralContract* Contract::release_deltaneutralcontract() {
  _impl_._has_bits_[0] &= ~0x00004000u;
  ::protobuf::DeltaNeutralContract* temp = _impl_.deltaneutralcontract_;
  _impl_.deltaneutralcontract_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::protobuf::DeltaNeutralContract* Contract::unsafe_arena_release_deltaneutralcontract() {
  // @@protoc_insertion_point(field_release:protobuf.Contract.deltaNeutralContract)
  _impl_._has_bits_[0] &= ~0x00004000u;
  ::protobuf::DeltaNeutralContract* temp = _impl_.deltaneutralcontract_;
  _impl_.deltaneutralcontract_ = nullptr;
  return temp;
}
inline ::protobuf::DeltaNeutralContract* Contract::_internal_mutable_deltaneutralcontract() {
  _impl_._has_bits_[0] |= 0x00004000u;
  if (_impl_.deltaneutralcontract_ == nullptr) {
    auto* p = CreateMaybeMessage<::protobuf::DeltaNeutralContract>(GetArenaForAllocation());
    _impl_.deltaneutralcontract_ = p;
  }
  return _impl_.deltaneutralcontract_;
}
inline ::protobuf::DeltaNeutralContract* Contract::mutable_deltaneutralcontract() {
  ::protobuf::DeltaNeutralContract* _msg = _internal_mutable_deltaneutralcontract();
  // @@protoc_insertion_point(field_mutable:protobuf.Contract.deltaNeutralContract)
  return _msg;
}
inline void Contract::set_allocated_deltaneutralcontract(::protobuf::DeltaNeutralContract* deltaneutralcontract) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.deltaneutralcontract_);
  }
  if (deltaneutralcontract) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(deltaneutralcontract));
    if (message_arena != submessage_arena) {
      deltaneutralcontract = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, deltaneutralcontract, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00004000u;
  } else {
    _impl_._has_bits_[0] &= ~0x00004000u;
  }
  _impl_.deltaneutralcontract_ = deltaneutralcontract;
  // @@protoc_insertion_point(field_set_allocated:protobuf.Contract.deltaNeutralContract)
}

// optional bool includeExpired = 18;
inline bool Contract::has_includeexpired() const {
  bool value = (_impl_._has_bits_[0] & 0x00040000u) != 0;
  return value;
}
inline void Contract::clear_includeexpired() {
  _impl_.includeexpired_ = false;
  _impl_._has_bits_[0] &= ~0x00040000u;
}
inline bool Contract::includeexpired() const {
  // @@protoc_insertion_point(field_get:protobuf.Contract.includeExpired)
  return _internal_includeexpired();
}
inline void Contract::set_includeexpired(bool value) {
  _internal_set_includeexpired(value);
  // @@protoc_insertion_point(field_set:protobuf.Contract.includeExpired)
}
inline bool Contract::_internal_includeexpired() const {
  return _impl_.includeexpired_;
}
inline void Contract::_internal_set_includeexpired(bool value) {
  _impl_._has_bits_[0] |= 0x00040000u;
  _impl_.includeexpired_ = value;
}

// optional string comboLegsDescrip = 19;
inline bool Contract::has_combolegsdescrip() const {
  bool value = (_impl_._has_bits_[0] & 0x00002000u) != 0;
  return value;
}
inline void Contract::clear_combolegsdescrip() {
  _impl_.combolegsdescrip_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00002000u;
}
inline const std::string& Contract::combolegsdescrip() const {
  // @@protoc_insertion_point(field_get:protobuf.Contract.comboLegsDescrip)
  return _internal_combolegsdescrip();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Contract::set_combolegsdescrip(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00002000u;
  _impl_.combolegsdescrip_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.Contract.comboLegsDescrip)
}
inline std::string* Contract::mutable_combolegsdescrip() {
  std::string* _s = _internal_mutable_combolegsdescrip();
  // @@protoc_insertion_point(field_mutable:protobuf.Contract.comboLegsDescrip)
  return _s;
}
inline const std::string& Contract::_internal_combolegsdescrip() const {
  return _impl_.combolegsdescrip_.Get();
}
inline void Contract::_internal_set_combolegsdescrip(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00002000u;


  _impl_.combolegsdescrip_.Set(value, GetArenaForAllocation());
}
inline std::string* Contract::_internal_mutable_combolegsdescrip() {
  _impl_._has_bits_[0] |= 0x00002000u;
  return _impl_.combolegsdescrip_.Mutable( GetArenaForAllocation());
}
inline std::string* Contract::release_combolegsdescrip() {
  // @@protoc_insertion_point(field_release:protobuf.Contract.comboLegsDescrip)
  if ((_impl_._has_bits_[0] & 0x00002000u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00002000u;
  auto* released = _impl_.combolegsdescrip_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.combolegsdescrip_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void Contract::set_allocated_combolegsdescrip(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00002000u;
  } else {
    _impl_._has_bits_[0] &= ~0x00002000u;
  }
  _impl_.combolegsdescrip_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.combolegsdescrip_.IsDefault()) {
          _impl_.combolegsdescrip_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.Contract.comboLegsDescrip)
}

// repeated .protobuf.ComboLeg comboLegs = 20;
inline int Contract::_internal_combolegs_size() const {
  return _impl_.combolegs_.size();
}
inline int Contract::combolegs_size() const {
  return _internal_combolegs_size();
}
inline ::protobuf::ComboLeg* Contract::mutable_combolegs(int index) {
  // @@protoc_insertion_point(field_mutable:protobuf.Contract.comboLegs)
  return _internal_mutable_combolegs()->Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protobuf::ComboLeg >*
Contract::mutable_combolegs() {
  // @@protoc_insertion_point(field_mutable_list:protobuf.Contract.comboLegs)
  return _internal_mutable_combolegs();
}
inline const ::protobuf::ComboLeg& Contract::_internal_combolegs(int index) const {
  return _internal_combolegs().Get(index);
}
inline const ::protobuf::ComboLeg& Contract::combolegs(int index) const {
  // @@protoc_insertion_point(field_get:protobuf.Contract.comboLegs)
  return _internal_combolegs(index);
}
inline ::protobuf::ComboLeg* Contract::_internal_add_combolegs() {
  return _internal_mutable_combolegs()->Add();
}
inline ::protobuf::ComboLeg* Contract::add_combolegs() {
  ::protobuf::ComboLeg* _add = _internal_add_combolegs();
  // @@protoc_insertion_point(field_add:protobuf.Contract.comboLegs)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::protobuf::ComboLeg >&
Contract::combolegs() const {
  // @@protoc_insertion_point(field_list:protobuf.Contract.comboLegs)
  return _internal_combolegs();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::protobuf::ComboLeg>&
Contract::_internal_combolegs() const {
  return _impl_.combolegs_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<::protobuf::ComboLeg>*
Contract::_internal_mutable_combolegs() {
  return &_impl_.combolegs_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_Contract_2eproto_2epb_2eh
