// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ErrorMessage.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ErrorMessage_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_ErrorMessage_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4023000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4023004 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ErrorMessage_2eproto

PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ErrorMessage_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable
    descriptor_table_ErrorMessage_2eproto;
namespace protobuf {
class ErrorMessage;
struct ErrorMessageDefaultTypeInternal;
extern ErrorMessageDefaultTypeInternal _ErrorMessage_default_instance_;
}  // namespace protobuf
PROTOBUF_NAMESPACE_OPEN
template <>
::protobuf::ErrorMessage* Arena::CreateMaybeMessage<::protobuf::ErrorMessage>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

namespace protobuf {

// ===================================================================


// -------------------------------------------------------------------

class ErrorMessage final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protobuf.ErrorMessage) */ {
 public:
  inline ErrorMessage() : ErrorMessage(nullptr) {}
  ~ErrorMessage() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR ErrorMessage(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ErrorMessage(const ErrorMessage& from);
  ErrorMessage(ErrorMessage&& from) noexcept
    : ErrorMessage() {
    *this = ::std::move(from);
  }

  inline ErrorMessage& operator=(const ErrorMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline ErrorMessage& operator=(ErrorMessage&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ErrorMessage& default_instance() {
    return *internal_default_instance();
  }
  static inline const ErrorMessage* internal_default_instance() {
    return reinterpret_cast<const ErrorMessage*>(
               &_ErrorMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ErrorMessage& a, ErrorMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(ErrorMessage* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ErrorMessage* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ErrorMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ErrorMessage>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ErrorMessage& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ErrorMessage& from) {
    ErrorMessage::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ErrorMessage* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "protobuf.ErrorMessage";
  }
  protected:
  explicit ErrorMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kErrorMsgFieldNumber = 4,
    kAdvancedOrderRejectJsonFieldNumber = 5,
    kErrorTimeFieldNumber = 2,
    kIdFieldNumber = 1,
    kErrorCodeFieldNumber = 3,
  };
  // optional string errorMsg = 4;
  bool has_errormsg() const;
  void clear_errormsg() ;
  const std::string& errormsg() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_errormsg(Arg_&& arg, Args_... args);
  std::string* mutable_errormsg();
  PROTOBUF_NODISCARD std::string* release_errormsg();
  void set_allocated_errormsg(std::string* ptr);

  private:
  const std::string& _internal_errormsg() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_errormsg(
      const std::string& value);
  std::string* _internal_mutable_errormsg();

  public:
  // optional string advancedOrderRejectJson = 5;
  bool has_advancedorderrejectjson() const;
  void clear_advancedorderrejectjson() ;
  const std::string& advancedorderrejectjson() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_advancedorderrejectjson(Arg_&& arg, Args_... args);
  std::string* mutable_advancedorderrejectjson();
  PROTOBUF_NODISCARD std::string* release_advancedorderrejectjson();
  void set_allocated_advancedorderrejectjson(std::string* ptr);

  private:
  const std::string& _internal_advancedorderrejectjson() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_advancedorderrejectjson(
      const std::string& value);
  std::string* _internal_mutable_advancedorderrejectjson();

  public:
  // optional int64 errorTime = 2;
  bool has_errortime() const;
  void clear_errortime() ;
  ::int64_t errortime() const;
  void set_errortime(::int64_t value);

  private:
  ::int64_t _internal_errortime() const;
  void _internal_set_errortime(::int64_t value);

  public:
  // optional int32 id = 1;
  bool has_id() const;
  void clear_id() ;
  ::int32_t id() const;
  void set_id(::int32_t value);

  private:
  ::int32_t _internal_id() const;
  void _internal_set_id(::int32_t value);

  public:
  // optional int32 errorCode = 3;
  bool has_errorcode() const;
  void clear_errorcode() ;
  ::int32_t errorcode() const;
  void set_errorcode(::int32_t value);

  private:
  ::int32_t _internal_errorcode() const;
  void _internal_set_errorcode(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:protobuf.ErrorMessage)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr errormsg_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr advancedorderrejectjson_;
    ::int64_t errortime_;
    ::int32_t id_;
    ::int32_t errorcode_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ErrorMessage_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ErrorMessage

// optional int32 id = 1;
inline bool ErrorMessage::has_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void ErrorMessage::clear_id() {
  _impl_.id_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline ::int32_t ErrorMessage::id() const {
  // @@protoc_insertion_point(field_get:protobuf.ErrorMessage.id)
  return _internal_id();
}
inline void ErrorMessage::set_id(::int32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:protobuf.ErrorMessage.id)
}
inline ::int32_t ErrorMessage::_internal_id() const {
  return _impl_.id_;
}
inline void ErrorMessage::_internal_set_id(::int32_t value) {
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.id_ = value;
}

// optional int64 errorTime = 2;
inline bool ErrorMessage::has_errortime() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void ErrorMessage::clear_errortime() {
  _impl_.errortime_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::int64_t ErrorMessage::errortime() const {
  // @@protoc_insertion_point(field_get:protobuf.ErrorMessage.errorTime)
  return _internal_errortime();
}
inline void ErrorMessage::set_errortime(::int64_t value) {
  _internal_set_errortime(value);
  // @@protoc_insertion_point(field_set:protobuf.ErrorMessage.errorTime)
}
inline ::int64_t ErrorMessage::_internal_errortime() const {
  return _impl_.errortime_;
}
inline void ErrorMessage::_internal_set_errortime(::int64_t value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.errortime_ = value;
}

// optional int32 errorCode = 3;
inline bool ErrorMessage::has_errorcode() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline void ErrorMessage::clear_errorcode() {
  _impl_.errorcode_ = 0;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline ::int32_t ErrorMessage::errorcode() const {
  // @@protoc_insertion_point(field_get:protobuf.ErrorMessage.errorCode)
  return _internal_errorcode();
}
inline void ErrorMessage::set_errorcode(::int32_t value) {
  _internal_set_errorcode(value);
  // @@protoc_insertion_point(field_set:protobuf.ErrorMessage.errorCode)
}
inline ::int32_t ErrorMessage::_internal_errorcode() const {
  return _impl_.errorcode_;
}
inline void ErrorMessage::_internal_set_errorcode(::int32_t value) {
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.errorcode_ = value;
}

// optional string errorMsg = 4;
inline bool ErrorMessage::has_errormsg() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void ErrorMessage::clear_errormsg() {
  _impl_.errormsg_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& ErrorMessage::errormsg() const {
  // @@protoc_insertion_point(field_get:protobuf.ErrorMessage.errorMsg)
  return _internal_errormsg();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ErrorMessage::set_errormsg(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.errormsg_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.ErrorMessage.errorMsg)
}
inline std::string* ErrorMessage::mutable_errormsg() {
  std::string* _s = _internal_mutable_errormsg();
  // @@protoc_insertion_point(field_mutable:protobuf.ErrorMessage.errorMsg)
  return _s;
}
inline const std::string& ErrorMessage::_internal_errormsg() const {
  return _impl_.errormsg_.Get();
}
inline void ErrorMessage::_internal_set_errormsg(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;


  _impl_.errormsg_.Set(value, GetArenaForAllocation());
}
inline std::string* ErrorMessage::_internal_mutable_errormsg() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.errormsg_.Mutable( GetArenaForAllocation());
}
inline std::string* ErrorMessage::release_errormsg() {
  // @@protoc_insertion_point(field_release:protobuf.ErrorMessage.errorMsg)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.errormsg_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.errormsg_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void ErrorMessage::set_allocated_errormsg(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.errormsg_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.errormsg_.IsDefault()) {
          _impl_.errormsg_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.ErrorMessage.errorMsg)
}

// optional string advancedOrderRejectJson = 5;
inline bool ErrorMessage::has_advancedorderrejectjson() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void ErrorMessage::clear_advancedorderrejectjson() {
  _impl_.advancedorderrejectjson_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& ErrorMessage::advancedorderrejectjson() const {
  // @@protoc_insertion_point(field_get:protobuf.ErrorMessage.advancedOrderRejectJson)
  return _internal_advancedorderrejectjson();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ErrorMessage::set_advancedorderrejectjson(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.advancedorderrejectjson_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.ErrorMessage.advancedOrderRejectJson)
}
inline std::string* ErrorMessage::mutable_advancedorderrejectjson() {
  std::string* _s = _internal_mutable_advancedorderrejectjson();
  // @@protoc_insertion_point(field_mutable:protobuf.ErrorMessage.advancedOrderRejectJson)
  return _s;
}
inline const std::string& ErrorMessage::_internal_advancedorderrejectjson() const {
  return _impl_.advancedorderrejectjson_.Get();
}
inline void ErrorMessage::_internal_set_advancedorderrejectjson(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000002u;


  _impl_.advancedorderrejectjson_.Set(value, GetArenaForAllocation());
}
inline std::string* ErrorMessage::_internal_mutable_advancedorderrejectjson() {
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.advancedorderrejectjson_.Mutable( GetArenaForAllocation());
}
inline std::string* ErrorMessage::release_advancedorderrejectjson() {
  // @@protoc_insertion_point(field_release:protobuf.ErrorMessage.advancedOrderRejectJson)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.advancedorderrejectjson_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.advancedorderrejectjson_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void ErrorMessage::set_allocated_advancedorderrejectjson(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.advancedorderrejectjson_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.advancedorderrejectjson_.IsDefault()) {
          _impl_.advancedorderrejectjson_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.ErrorMessage.advancedOrderRejectJson)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_ErrorMessage_2eproto_2epb_2eh
