// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExecutionFilter.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ExecutionFilter_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_ExecutionFilter_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4023000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4023004 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ExecutionFilter_2eproto

PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ExecutionFilter_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable
    descriptor_table_ExecutionFilter_2eproto;
namespace protobuf {
class ExecutionFilter;
struct ExecutionFilterDefaultTypeInternal;
extern ExecutionFilterDefaultTypeInternal _ExecutionFilter_default_instance_;
}  // namespace protobuf
PROTOBUF_NAMESPACE_OPEN
template <>
::protobuf::ExecutionFilter* Arena::CreateMaybeMessage<::protobuf::ExecutionFilter>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

namespace protobuf {

// ===================================================================


// -------------------------------------------------------------------

class ExecutionFilter final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protobuf.ExecutionFilter) */ {
 public:
  inline ExecutionFilter() : ExecutionFilter(nullptr) {}
  ~ExecutionFilter() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR ExecutionFilter(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ExecutionFilter(const ExecutionFilter& from);
  ExecutionFilter(ExecutionFilter&& from) noexcept
    : ExecutionFilter() {
    *this = ::std::move(from);
  }

  inline ExecutionFilter& operator=(const ExecutionFilter& from) {
    CopyFrom(from);
    return *this;
  }
  inline ExecutionFilter& operator=(ExecutionFilter&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ExecutionFilter& default_instance() {
    return *internal_default_instance();
  }
  static inline const ExecutionFilter* internal_default_instance() {
    return reinterpret_cast<const ExecutionFilter*>(
               &_ExecutionFilter_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ExecutionFilter& a, ExecutionFilter& b) {
    a.Swap(&b);
  }
  inline void Swap(ExecutionFilter* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ExecutionFilter* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ExecutionFilter* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ExecutionFilter>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ExecutionFilter& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ExecutionFilter& from) {
    ExecutionFilter::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ExecutionFilter* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "protobuf.ExecutionFilter";
  }
  protected:
  explicit ExecutionFilter(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSpecificDatesFieldNumber = 9,
    kAcctCodeFieldNumber = 2,
    kTimeFieldNumber = 3,
    kSymbolFieldNumber = 4,
    kSecTypeFieldNumber = 5,
    kExchangeFieldNumber = 6,
    kSideFieldNumber = 7,
    kClientIdFieldNumber = 1,
    kLastNDaysFieldNumber = 8,
  };
  // repeated int32 specificDates = 9;
  int specificdates_size() const;
  private:
  int _internal_specificdates_size() const;

  public:
  void clear_specificdates() ;
  ::int32_t specificdates(int index) const;
  void set_specificdates(int index, ::int32_t value);
  void add_specificdates(::int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField<::int32_t>& specificdates() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<::int32_t>* mutable_specificdates();

  private:
  ::int32_t _internal_specificdates(int index) const;
  void _internal_add_specificdates(::int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField<::int32_t>& _internal_specificdates() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<::int32_t>* _internal_mutable_specificdates();

  public:
  // optional string acctCode = 2;
  bool has_acctcode() const;
  void clear_acctcode() ;
  const std::string& acctcode() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_acctcode(Arg_&& arg, Args_... args);
  std::string* mutable_acctcode();
  PROTOBUF_NODISCARD std::string* release_acctcode();
  void set_allocated_acctcode(std::string* ptr);

  private:
  const std::string& _internal_acctcode() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_acctcode(
      const std::string& value);
  std::string* _internal_mutable_acctcode();

  public:
  // optional string time = 3;
  bool has_time() const;
  void clear_time() ;
  const std::string& time() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_time(Arg_&& arg, Args_... args);
  std::string* mutable_time();
  PROTOBUF_NODISCARD std::string* release_time();
  void set_allocated_time(std::string* ptr);

  private:
  const std::string& _internal_time() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_time(
      const std::string& value);
  std::string* _internal_mutable_time();

  public:
  // optional string symbol = 4;
  bool has_symbol() const;
  void clear_symbol() ;
  const std::string& symbol() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_symbol(Arg_&& arg, Args_... args);
  std::string* mutable_symbol();
  PROTOBUF_NODISCARD std::string* release_symbol();
  void set_allocated_symbol(std::string* ptr);

  private:
  const std::string& _internal_symbol() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_symbol(
      const std::string& value);
  std::string* _internal_mutable_symbol();

  public:
  // optional string secType = 5;
  bool has_sectype() const;
  void clear_sectype() ;
  const std::string& sectype() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_sectype(Arg_&& arg, Args_... args);
  std::string* mutable_sectype();
  PROTOBUF_NODISCARD std::string* release_sectype();
  void set_allocated_sectype(std::string* ptr);

  private:
  const std::string& _internal_sectype() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sectype(
      const std::string& value);
  std::string* _internal_mutable_sectype();

  public:
  // optional string exchange = 6;
  bool has_exchange() const;
  void clear_exchange() ;
  const std::string& exchange() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_exchange(Arg_&& arg, Args_... args);
  std::string* mutable_exchange();
  PROTOBUF_NODISCARD std::string* release_exchange();
  void set_allocated_exchange(std::string* ptr);

  private:
  const std::string& _internal_exchange() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_exchange(
      const std::string& value);
  std::string* _internal_mutable_exchange();

  public:
  // optional string side = 7;
  bool has_side() const;
  void clear_side() ;
  const std::string& side() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_side(Arg_&& arg, Args_... args);
  std::string* mutable_side();
  PROTOBUF_NODISCARD std::string* release_side();
  void set_allocated_side(std::string* ptr);

  private:
  const std::string& _internal_side() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_side(
      const std::string& value);
  std::string* _internal_mutable_side();

  public:
  // optional int32 clientId = 1;
  bool has_clientid() const;
  void clear_clientid() ;
  ::int32_t clientid() const;
  void set_clientid(::int32_t value);

  private:
  ::int32_t _internal_clientid() const;
  void _internal_set_clientid(::int32_t value);

  public:
  // optional int32 lastNDays = 8;
  bool has_lastndays() const;
  void clear_lastndays() ;
  ::int32_t lastndays() const;
  void set_lastndays(::int32_t value);

  private:
  ::int32_t _internal_lastndays() const;
  void _internal_set_lastndays(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:protobuf.ExecutionFilter)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField<::int32_t> specificdates_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _specificdates_cached_byte_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr acctcode_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr time_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr symbol_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sectype_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr exchange_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr side_;
    ::int32_t clientid_;
    ::int32_t lastndays_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ExecutionFilter_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ExecutionFilter

// optional int32 clientId = 1;
inline bool ExecutionFilter::has_clientid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline void ExecutionFilter::clear_clientid() {
  _impl_.clientid_ = 0;
  _impl_._has_bits_[0] &= ~0x00000040u;
}
inline ::int32_t ExecutionFilter::clientid() const {
  // @@protoc_insertion_point(field_get:protobuf.ExecutionFilter.clientId)
  return _internal_clientid();
}
inline void ExecutionFilter::set_clientid(::int32_t value) {
  _internal_set_clientid(value);
  // @@protoc_insertion_point(field_set:protobuf.ExecutionFilter.clientId)
}
inline ::int32_t ExecutionFilter::_internal_clientid() const {
  return _impl_.clientid_;
}
inline void ExecutionFilter::_internal_set_clientid(::int32_t value) {
  _impl_._has_bits_[0] |= 0x00000040u;
  _impl_.clientid_ = value;
}

// optional string acctCode = 2;
inline bool ExecutionFilter::has_acctcode() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void ExecutionFilter::clear_acctcode() {
  _impl_.acctcode_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& ExecutionFilter::acctcode() const {
  // @@protoc_insertion_point(field_get:protobuf.ExecutionFilter.acctCode)
  return _internal_acctcode();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ExecutionFilter::set_acctcode(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.acctcode_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.ExecutionFilter.acctCode)
}
inline std::string* ExecutionFilter::mutable_acctcode() {
  std::string* _s = _internal_mutable_acctcode();
  // @@protoc_insertion_point(field_mutable:protobuf.ExecutionFilter.acctCode)
  return _s;
}
inline const std::string& ExecutionFilter::_internal_acctcode() const {
  return _impl_.acctcode_.Get();
}
inline void ExecutionFilter::_internal_set_acctcode(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;


  _impl_.acctcode_.Set(value, GetArenaForAllocation());
}
inline std::string* ExecutionFilter::_internal_mutable_acctcode() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.acctcode_.Mutable( GetArenaForAllocation());
}
inline std::string* ExecutionFilter::release_acctcode() {
  // @@protoc_insertion_point(field_release:protobuf.ExecutionFilter.acctCode)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.acctcode_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.acctcode_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void ExecutionFilter::set_allocated_acctcode(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.acctcode_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.acctcode_.IsDefault()) {
          _impl_.acctcode_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.ExecutionFilter.acctCode)
}

// optional string time = 3;
inline bool ExecutionFilter::has_time() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void ExecutionFilter::clear_time() {
  _impl_.time_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& ExecutionFilter::time() const {
  // @@protoc_insertion_point(field_get:protobuf.ExecutionFilter.time)
  return _internal_time();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ExecutionFilter::set_time(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.time_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.ExecutionFilter.time)
}
inline std::string* ExecutionFilter::mutable_time() {
  std::string* _s = _internal_mutable_time();
  // @@protoc_insertion_point(field_mutable:protobuf.ExecutionFilter.time)
  return _s;
}
inline const std::string& ExecutionFilter::_internal_time() const {
  return _impl_.time_.Get();
}
inline void ExecutionFilter::_internal_set_time(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000002u;


  _impl_.time_.Set(value, GetArenaForAllocation());
}
inline std::string* ExecutionFilter::_internal_mutable_time() {
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.time_.Mutable( GetArenaForAllocation());
}
inline std::string* ExecutionFilter::release_time() {
  // @@protoc_insertion_point(field_release:protobuf.ExecutionFilter.time)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.time_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.time_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void ExecutionFilter::set_allocated_time(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.time_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.time_.IsDefault()) {
          _impl_.time_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.ExecutionFilter.time)
}

// optional string symbol = 4;
inline bool ExecutionFilter::has_symbol() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void ExecutionFilter::clear_symbol() {
  _impl_.symbol_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const std::string& ExecutionFilter::symbol() const {
  // @@protoc_insertion_point(field_get:protobuf.ExecutionFilter.symbol)
  return _internal_symbol();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ExecutionFilter::set_symbol(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.symbol_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.ExecutionFilter.symbol)
}
inline std::string* ExecutionFilter::mutable_symbol() {
  std::string* _s = _internal_mutable_symbol();
  // @@protoc_insertion_point(field_mutable:protobuf.ExecutionFilter.symbol)
  return _s;
}
inline const std::string& ExecutionFilter::_internal_symbol() const {
  return _impl_.symbol_.Get();
}
inline void ExecutionFilter::_internal_set_symbol(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000004u;


  _impl_.symbol_.Set(value, GetArenaForAllocation());
}
inline std::string* ExecutionFilter::_internal_mutable_symbol() {
  _impl_._has_bits_[0] |= 0x00000004u;
  return _impl_.symbol_.Mutable( GetArenaForAllocation());
}
inline std::string* ExecutionFilter::release_symbol() {
  // @@protoc_insertion_point(field_release:protobuf.ExecutionFilter.symbol)
  if ((_impl_._has_bits_[0] & 0x00000004u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004u;
  auto* released = _impl_.symbol_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.symbol_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void ExecutionFilter::set_allocated_symbol(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.symbol_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.symbol_.IsDefault()) {
          _impl_.symbol_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.ExecutionFilter.symbol)
}

// optional string secType = 5;
inline bool ExecutionFilter::has_sectype() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void ExecutionFilter::clear_sectype() {
  _impl_.sectype_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline const std::string& ExecutionFilter::sectype() const {
  // @@protoc_insertion_point(field_get:protobuf.ExecutionFilter.secType)
  return _internal_sectype();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ExecutionFilter::set_sectype(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.sectype_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.ExecutionFilter.secType)
}
inline std::string* ExecutionFilter::mutable_sectype() {
  std::string* _s = _internal_mutable_sectype();
  // @@protoc_insertion_point(field_mutable:protobuf.ExecutionFilter.secType)
  return _s;
}
inline const std::string& ExecutionFilter::_internal_sectype() const {
  return _impl_.sectype_.Get();
}
inline void ExecutionFilter::_internal_set_sectype(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000008u;


  _impl_.sectype_.Set(value, GetArenaForAllocation());
}
inline std::string* ExecutionFilter::_internal_mutable_sectype() {
  _impl_._has_bits_[0] |= 0x00000008u;
  return _impl_.sectype_.Mutable( GetArenaForAllocation());
}
inline std::string* ExecutionFilter::release_sectype() {
  // @@protoc_insertion_point(field_release:protobuf.ExecutionFilter.secType)
  if ((_impl_._has_bits_[0] & 0x00000008u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000008u;
  auto* released = _impl_.sectype_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.sectype_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void ExecutionFilter::set_allocated_sectype(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  _impl_.sectype_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.sectype_.IsDefault()) {
          _impl_.sectype_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.ExecutionFilter.secType)
}

// optional string exchange = 6;
inline bool ExecutionFilter::has_exchange() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline void ExecutionFilter::clear_exchange() {
  _impl_.exchange_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline const std::string& ExecutionFilter::exchange() const {
  // @@protoc_insertion_point(field_get:protobuf.ExecutionFilter.exchange)
  return _internal_exchange();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ExecutionFilter::set_exchange(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.exchange_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.ExecutionFilter.exchange)
}
inline std::string* ExecutionFilter::mutable_exchange() {
  std::string* _s = _internal_mutable_exchange();
  // @@protoc_insertion_point(field_mutable:protobuf.ExecutionFilter.exchange)
  return _s;
}
inline const std::string& ExecutionFilter::_internal_exchange() const {
  return _impl_.exchange_.Get();
}
inline void ExecutionFilter::_internal_set_exchange(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000010u;


  _impl_.exchange_.Set(value, GetArenaForAllocation());
}
inline std::string* ExecutionFilter::_internal_mutable_exchange() {
  _impl_._has_bits_[0] |= 0x00000010u;
  return _impl_.exchange_.Mutable( GetArenaForAllocation());
}
inline std::string* ExecutionFilter::release_exchange() {
  // @@protoc_insertion_point(field_release:protobuf.ExecutionFilter.exchange)
  if ((_impl_._has_bits_[0] & 0x00000010u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000010u;
  auto* released = _impl_.exchange_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.exchange_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void ExecutionFilter::set_allocated_exchange(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000010u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000010u;
  }
  _impl_.exchange_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.exchange_.IsDefault()) {
          _impl_.exchange_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.ExecutionFilter.exchange)
}

// optional string side = 7;
inline bool ExecutionFilter::has_side() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline void ExecutionFilter::clear_side() {
  _impl_.side_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline const std::string& ExecutionFilter::side() const {
  // @@protoc_insertion_point(field_get:protobuf.ExecutionFilter.side)
  return _internal_side();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ExecutionFilter::set_side(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000020u;
  _impl_.side_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.ExecutionFilter.side)
}
inline std::string* ExecutionFilter::mutable_side() {
  std::string* _s = _internal_mutable_side();
  // @@protoc_insertion_point(field_mutable:protobuf.ExecutionFilter.side)
  return _s;
}
inline const std::string& ExecutionFilter::_internal_side() const {
  return _impl_.side_.Get();
}
inline void ExecutionFilter::_internal_set_side(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000020u;


  _impl_.side_.Set(value, GetArenaForAllocation());
}
inline std::string* ExecutionFilter::_internal_mutable_side() {
  _impl_._has_bits_[0] |= 0x00000020u;
  return _impl_.side_.Mutable( GetArenaForAllocation());
}
inline std::string* ExecutionFilter::release_side() {
  // @@protoc_insertion_point(field_release:protobuf.ExecutionFilter.side)
  if ((_impl_._has_bits_[0] & 0x00000020u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000020u;
  auto* released = _impl_.side_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.side_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void ExecutionFilter::set_allocated_side(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000020u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000020u;
  }
  _impl_.side_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.side_.IsDefault()) {
          _impl_.side_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.ExecutionFilter.side)
}

// optional int32 lastNDays = 8;
inline bool ExecutionFilter::has_lastndays() const {
  bool value = (_impl_._has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline void ExecutionFilter::clear_lastndays() {
  _impl_.lastndays_ = 0;
  _impl_._has_bits_[0] &= ~0x00000080u;
}
inline ::int32_t ExecutionFilter::lastndays() const {
  // @@protoc_insertion_point(field_get:protobuf.ExecutionFilter.lastNDays)
  return _internal_lastndays();
}
inline void ExecutionFilter::set_lastndays(::int32_t value) {
  _internal_set_lastndays(value);
  // @@protoc_insertion_point(field_set:protobuf.ExecutionFilter.lastNDays)
}
inline ::int32_t ExecutionFilter::_internal_lastndays() const {
  return _impl_.lastndays_;
}
inline void ExecutionFilter::_internal_set_lastndays(::int32_t value) {
  _impl_._has_bits_[0] |= 0x00000080u;
  _impl_.lastndays_ = value;
}

// repeated int32 specificDates = 9;
inline int ExecutionFilter::_internal_specificdates_size() const {
  return _impl_.specificdates_.size();
}
inline int ExecutionFilter::specificdates_size() const {
  return _internal_specificdates_size();
}
inline void ExecutionFilter::clear_specificdates() {
  _internal_mutable_specificdates()->Clear();
}
inline ::int32_t ExecutionFilter::specificdates(int index) const {
  // @@protoc_insertion_point(field_get:protobuf.ExecutionFilter.specificDates)
  return _internal_specificdates(index);
}
inline void ExecutionFilter::set_specificdates(int index, ::int32_t value) {
  _internal_mutable_specificdates()->Set(index, value);
  // @@protoc_insertion_point(field_set:protobuf.ExecutionFilter.specificDates)
}
inline void ExecutionFilter::add_specificdates(::int32_t value) {
  _internal_add_specificdates(value);
  // @@protoc_insertion_point(field_add:protobuf.ExecutionFilter.specificDates)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField<::int32_t>& ExecutionFilter::specificdates() const {
  // @@protoc_insertion_point(field_list:protobuf.ExecutionFilter.specificDates)
  return _internal_specificdates();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<::int32_t>* ExecutionFilter::mutable_specificdates() {
  // @@protoc_insertion_point(field_mutable_list:protobuf.ExecutionFilter.specificDates)
  return _internal_mutable_specificdates();
}

inline ::int32_t ExecutionFilter::_internal_specificdates(int index) const {
  return _internal_specificdates().Get(index);
}
inline void ExecutionFilter::_internal_add_specificdates(::int32_t value) {
  _internal_mutable_specificdates()->Add(value);
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField<::int32_t>& ExecutionFilter::_internal_specificdates() const {
  return _impl_.specificdates_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<::int32_t>* ExecutionFilter::_internal_mutable_specificdates() {
  return &_impl_.specificdates_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_ExecutionFilter_2eproto_2epb_2eh
