// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Execution.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Execution_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_Execution_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4023000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4023004 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_Execution_2eproto

PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Execution_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable
    descriptor_table_Execution_2eproto;
namespace protobuf {
class Execution;
struct ExecutionDefaultTypeInternal;
extern ExecutionDefaultTypeInternal _Execution_default_instance_;
}  // namespace protobuf
PROTOBUF_NAMESPACE_OPEN
template <>
::protobuf::Execution* Arena::CreateMaybeMessage<::protobuf::Execution>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

namespace protobuf {

// ===================================================================


// -------------------------------------------------------------------

class Execution final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protobuf.Execution) */ {
 public:
  inline Execution() : Execution(nullptr) {}
  ~Execution() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR Execution(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Execution(const Execution& from);
  Execution(Execution&& from) noexcept
    : Execution() {
    *this = ::std::move(from);
  }

  inline Execution& operator=(const Execution& from) {
    CopyFrom(from);
    return *this;
  }
  inline Execution& operator=(Execution&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Execution& default_instance() {
    return *internal_default_instance();
  }
  static inline const Execution* internal_default_instance() {
    return reinterpret_cast<const Execution*>(
               &_Execution_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Execution& a, Execution& b) {
    a.Swap(&b);
  }
  inline void Swap(Execution* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Execution* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Execution* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Execution>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Execution& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Execution& from) {
    Execution::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Execution* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "protobuf.Execution";
  }
  protected:
  explicit Execution(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kExecIdFieldNumber = 2,
    kTimeFieldNumber = 3,
    kAcctNumberFieldNumber = 4,
    kExchangeFieldNumber = 5,
    kSideFieldNumber = 6,
    kSharesFieldNumber = 7,
    kCumQtyFieldNumber = 12,
    kOrderRefFieldNumber = 14,
    kEvRuleFieldNumber = 15,
    kModelCodeFieldNumber = 17,
    kSubmitterFieldNumber = 20,
    kOrderIdFieldNumber = 1,
    kClientIdFieldNumber = 10,
    kPriceFieldNumber = 8,
    kPermIdFieldNumber = 9,
    kAvgPriceFieldNumber = 13,
    kEvMultiplierFieldNumber = 16,
    kIsLiquidationFieldNumber = 11,
    kIsPriceRevisionPendingFieldNumber = 19,
    kLastLiquidityFieldNumber = 18,
    kOptExerciseOrLapseTypeFieldNumber = 21,
  };
  // optional string execId = 2;
  bool has_execid() const;
  void clear_execid() ;
  const std::string& execid() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_execid(Arg_&& arg, Args_... args);
  std::string* mutable_execid();
  PROTOBUF_NODISCARD std::string* release_execid();
  void set_allocated_execid(std::string* ptr);

  private:
  const std::string& _internal_execid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_execid(
      const std::string& value);
  std::string* _internal_mutable_execid();

  public:
  // optional string time = 3;
  bool has_time() const;
  void clear_time() ;
  const std::string& time() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_time(Arg_&& arg, Args_... args);
  std::string* mutable_time();
  PROTOBUF_NODISCARD std::string* release_time();
  void set_allocated_time(std::string* ptr);

  private:
  const std::string& _internal_time() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_time(
      const std::string& value);
  std::string* _internal_mutable_time();

  public:
  // optional string acctNumber = 4;
  bool has_acctnumber() const;
  void clear_acctnumber() ;
  const std::string& acctnumber() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_acctnumber(Arg_&& arg, Args_... args);
  std::string* mutable_acctnumber();
  PROTOBUF_NODISCARD std::string* release_acctnumber();
  void set_allocated_acctnumber(std::string* ptr);

  private:
  const std::string& _internal_acctnumber() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_acctnumber(
      const std::string& value);
  std::string* _internal_mutable_acctnumber();

  public:
  // optional string exchange = 5;
  bool has_exchange() const;
  void clear_exchange() ;
  const std::string& exchange() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_exchange(Arg_&& arg, Args_... args);
  std::string* mutable_exchange();
  PROTOBUF_NODISCARD std::string* release_exchange();
  void set_allocated_exchange(std::string* ptr);

  private:
  const std::string& _internal_exchange() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_exchange(
      const std::string& value);
  std::string* _internal_mutable_exchange();

  public:
  // optional string side = 6;
  bool has_side() const;
  void clear_side() ;
  const std::string& side() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_side(Arg_&& arg, Args_... args);
  std::string* mutable_side();
  PROTOBUF_NODISCARD std::string* release_side();
  void set_allocated_side(std::string* ptr);

  private:
  const std::string& _internal_side() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_side(
      const std::string& value);
  std::string* _internal_mutable_side();

  public:
  // optional string shares = 7;
  bool has_shares() const;
  void clear_shares() ;
  const std::string& shares() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_shares(Arg_&& arg, Args_... args);
  std::string* mutable_shares();
  PROTOBUF_NODISCARD std::string* release_shares();
  void set_allocated_shares(std::string* ptr);

  private:
  const std::string& _internal_shares() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_shares(
      const std::string& value);
  std::string* _internal_mutable_shares();

  public:
  // optional string cumQty = 12;
  bool has_cumqty() const;
  void clear_cumqty() ;
  const std::string& cumqty() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_cumqty(Arg_&& arg, Args_... args);
  std::string* mutable_cumqty();
  PROTOBUF_NODISCARD std::string* release_cumqty();
  void set_allocated_cumqty(std::string* ptr);

  private:
  const std::string& _internal_cumqty() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_cumqty(
      const std::string& value);
  std::string* _internal_mutable_cumqty();

  public:
  // optional string orderRef = 14;
  bool has_orderref() const;
  void clear_orderref() ;
  const std::string& orderref() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_orderref(Arg_&& arg, Args_... args);
  std::string* mutable_orderref();
  PROTOBUF_NODISCARD std::string* release_orderref();
  void set_allocated_orderref(std::string* ptr);

  private:
  const std::string& _internal_orderref() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_orderref(
      const std::string& value);
  std::string* _internal_mutable_orderref();

  public:
  // optional string evRule = 15;
  bool has_evrule() const;
  void clear_evrule() ;
  const std::string& evrule() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_evrule(Arg_&& arg, Args_... args);
  std::string* mutable_evrule();
  PROTOBUF_NODISCARD std::string* release_evrule();
  void set_allocated_evrule(std::string* ptr);

  private:
  const std::string& _internal_evrule() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_evrule(
      const std::string& value);
  std::string* _internal_mutable_evrule();

  public:
  // optional string modelCode = 17;
  bool has_modelcode() const;
  void clear_modelcode() ;
  const std::string& modelcode() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_modelcode(Arg_&& arg, Args_... args);
  std::string* mutable_modelcode();
  PROTOBUF_NODISCARD std::string* release_modelcode();
  void set_allocated_modelcode(std::string* ptr);

  private:
  const std::string& _internal_modelcode() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_modelcode(
      const std::string& value);
  std::string* _internal_mutable_modelcode();

  public:
  // optional string submitter = 20;
  bool has_submitter() const;
  void clear_submitter() ;
  const std::string& submitter() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_submitter(Arg_&& arg, Args_... args);
  std::string* mutable_submitter();
  PROTOBUF_NODISCARD std::string* release_submitter();
  void set_allocated_submitter(std::string* ptr);

  private:
  const std::string& _internal_submitter() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_submitter(
      const std::string& value);
  std::string* _internal_mutable_submitter();

  public:
  // optional int32 orderId = 1;
  bool has_orderid() const;
  void clear_orderid() ;
  ::int32_t orderid() const;
  void set_orderid(::int32_t value);

  private:
  ::int32_t _internal_orderid() const;
  void _internal_set_orderid(::int32_t value);

  public:
  // optional int32 clientId = 10;
  bool has_clientid() const;
  void clear_clientid() ;
  ::int32_t clientid() const;
  void set_clientid(::int32_t value);

  private:
  ::int32_t _internal_clientid() const;
  void _internal_set_clientid(::int32_t value);

  public:
  // optional double price = 8;
  bool has_price() const;
  void clear_price() ;
  double price() const;
  void set_price(double value);

  private:
  double _internal_price() const;
  void _internal_set_price(double value);

  public:
  // optional int64 permId = 9;
  bool has_permid() const;
  void clear_permid() ;
  ::int64_t permid() const;
  void set_permid(::int64_t value);

  private:
  ::int64_t _internal_permid() const;
  void _internal_set_permid(::int64_t value);

  public:
  // optional double avgPrice = 13;
  bool has_avgprice() const;
  void clear_avgprice() ;
  double avgprice() const;
  void set_avgprice(double value);

  private:
  double _internal_avgprice() const;
  void _internal_set_avgprice(double value);

  public:
  // optional double evMultiplier = 16;
  bool has_evmultiplier() const;
  void clear_evmultiplier() ;
  double evmultiplier() const;
  void set_evmultiplier(double value);

  private:
  double _internal_evmultiplier() const;
  void _internal_set_evmultiplier(double value);

  public:
  // optional bool isLiquidation = 11;
  bool has_isliquidation() const;
  void clear_isliquidation() ;
  bool isliquidation() const;
  void set_isliquidation(bool value);

  private:
  bool _internal_isliquidation() const;
  void _internal_set_isliquidation(bool value);

  public:
  // optional bool isPriceRevisionPending = 19;
  bool has_ispricerevisionpending() const;
  void clear_ispricerevisionpending() ;
  bool ispricerevisionpending() const;
  void set_ispricerevisionpending(bool value);

  private:
  bool _internal_ispricerevisionpending() const;
  void _internal_set_ispricerevisionpending(bool value);

  public:
  // optional int32 lastLiquidity = 18;
  bool has_lastliquidity() const;
  void clear_lastliquidity() ;
  ::int32_t lastliquidity() const;
  void set_lastliquidity(::int32_t value);

  private:
  ::int32_t _internal_lastliquidity() const;
  void _internal_set_lastliquidity(::int32_t value);

  public:
  // optional int32 optExerciseOrLapseType = 21;
  bool has_optexerciseorlapsetype() const;
  void clear_optexerciseorlapsetype() ;
  ::int32_t optexerciseorlapsetype() const;
  void set_optexerciseorlapsetype(::int32_t value);

  private:
  ::int32_t _internal_optexerciseorlapsetype() const;
  void _internal_set_optexerciseorlapsetype(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:protobuf.Execution)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr execid_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr time_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr acctnumber_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr exchange_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr side_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr shares_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr cumqty_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr orderref_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr evrule_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr modelcode_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr submitter_;
    ::int32_t orderid_;
    ::int32_t clientid_;
    double price_;
    ::int64_t permid_;
    double avgprice_;
    double evmultiplier_;
    bool isliquidation_;
    bool ispricerevisionpending_;
    ::int32_t lastliquidity_;
    ::int32_t optexerciseorlapsetype_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Execution_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Execution

// optional int32 orderId = 1;
inline bool Execution::has_orderid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000800u) != 0;
  return value;
}
inline void Execution::clear_orderid() {
  _impl_.orderid_ = 0;
  _impl_._has_bits_[0] &= ~0x00000800u;
}
inline ::int32_t Execution::orderid() const {
  // @@protoc_insertion_point(field_get:protobuf.Execution.orderId)
  return _internal_orderid();
}
inline void Execution::set_orderid(::int32_t value) {
  _internal_set_orderid(value);
  // @@protoc_insertion_point(field_set:protobuf.Execution.orderId)
}
inline ::int32_t Execution::_internal_orderid() const {
  return _impl_.orderid_;
}
inline void Execution::_internal_set_orderid(::int32_t value) {
  _impl_._has_bits_[0] |= 0x00000800u;
  _impl_.orderid_ = value;
}

// optional string execId = 2;
inline bool Execution::has_execid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void Execution::clear_execid() {
  _impl_.execid_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Execution::execid() const {
  // @@protoc_insertion_point(field_get:protobuf.Execution.execId)
  return _internal_execid();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Execution::set_execid(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.execid_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.Execution.execId)
}
inline std::string* Execution::mutable_execid() {
  std::string* _s = _internal_mutable_execid();
  // @@protoc_insertion_point(field_mutable:protobuf.Execution.execId)
  return _s;
}
inline const std::string& Execution::_internal_execid() const {
  return _impl_.execid_.Get();
}
inline void Execution::_internal_set_execid(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;


  _impl_.execid_.Set(value, GetArenaForAllocation());
}
inline std::string* Execution::_internal_mutable_execid() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.execid_.Mutable( GetArenaForAllocation());
}
inline std::string* Execution::release_execid() {
  // @@protoc_insertion_point(field_release:protobuf.Execution.execId)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.execid_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.execid_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void Execution::set_allocated_execid(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.execid_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.execid_.IsDefault()) {
          _impl_.execid_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.Execution.execId)
}

// optional string time = 3;
inline bool Execution::has_time() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void Execution::clear_time() {
  _impl_.time_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& Execution::time() const {
  // @@protoc_insertion_point(field_get:protobuf.Execution.time)
  return _internal_time();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Execution::set_time(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.time_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.Execution.time)
}
inline std::string* Execution::mutable_time() {
  std::string* _s = _internal_mutable_time();
  // @@protoc_insertion_point(field_mutable:protobuf.Execution.time)
  return _s;
}
inline const std::string& Execution::_internal_time() const {
  return _impl_.time_.Get();
}
inline void Execution::_internal_set_time(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000002u;


  _impl_.time_.Set(value, GetArenaForAllocation());
}
inline std::string* Execution::_internal_mutable_time() {
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.time_.Mutable( GetArenaForAllocation());
}
inline std::string* Execution::release_time() {
  // @@protoc_insertion_point(field_release:protobuf.Execution.time)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.time_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.time_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void Execution::set_allocated_time(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.time_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.time_.IsDefault()) {
          _impl_.time_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.Execution.time)
}

// optional string acctNumber = 4;
inline bool Execution::has_acctnumber() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void Execution::clear_acctnumber() {
  _impl_.acctnumber_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const std::string& Execution::acctnumber() const {
  // @@protoc_insertion_point(field_get:protobuf.Execution.acctNumber)
  return _internal_acctnumber();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Execution::set_acctnumber(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.acctnumber_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.Execution.acctNumber)
}
inline std::string* Execution::mutable_acctnumber() {
  std::string* _s = _internal_mutable_acctnumber();
  // @@protoc_insertion_point(field_mutable:protobuf.Execution.acctNumber)
  return _s;
}
inline const std::string& Execution::_internal_acctnumber() const {
  return _impl_.acctnumber_.Get();
}
inline void Execution::_internal_set_acctnumber(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000004u;


  _impl_.acctnumber_.Set(value, GetArenaForAllocation());
}
inline std::string* Execution::_internal_mutable_acctnumber() {
  _impl_._has_bits_[0] |= 0x00000004u;
  return _impl_.acctnumber_.Mutable( GetArenaForAllocation());
}
inline std::string* Execution::release_acctnumber() {
  // @@protoc_insertion_point(field_release:protobuf.Execution.acctNumber)
  if ((_impl_._has_bits_[0] & 0x00000004u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004u;
  auto* released = _impl_.acctnumber_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.acctnumber_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void Execution::set_allocated_acctnumber(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.acctnumber_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.acctnumber_.IsDefault()) {
          _impl_.acctnumber_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.Execution.acctNumber)
}

// optional string exchange = 5;
inline bool Execution::has_exchange() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void Execution::clear_exchange() {
  _impl_.exchange_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline const std::string& Execution::exchange() const {
  // @@protoc_insertion_point(field_get:protobuf.Execution.exchange)
  return _internal_exchange();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Execution::set_exchange(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.exchange_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.Execution.exchange)
}
inline std::string* Execution::mutable_exchange() {
  std::string* _s = _internal_mutable_exchange();
  // @@protoc_insertion_point(field_mutable:protobuf.Execution.exchange)
  return _s;
}
inline const std::string& Execution::_internal_exchange() const {
  return _impl_.exchange_.Get();
}
inline void Execution::_internal_set_exchange(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000008u;


  _impl_.exchange_.Set(value, GetArenaForAllocation());
}
inline std::string* Execution::_internal_mutable_exchange() {
  _impl_._has_bits_[0] |= 0x00000008u;
  return _impl_.exchange_.Mutable( GetArenaForAllocation());
}
inline std::string* Execution::release_exchange() {
  // @@protoc_insertion_point(field_release:protobuf.Execution.exchange)
  if ((_impl_._has_bits_[0] & 0x00000008u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000008u;
  auto* released = _impl_.exchange_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.exchange_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void Execution::set_allocated_exchange(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  _impl_.exchange_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.exchange_.IsDefault()) {
          _impl_.exchange_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.Execution.exchange)
}

// optional string side = 6;
inline bool Execution::has_side() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline void Execution::clear_side() {
  _impl_.side_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline const std::string& Execution::side() const {
  // @@protoc_insertion_point(field_get:protobuf.Execution.side)
  return _internal_side();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Execution::set_side(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.side_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.Execution.side)
}
inline std::string* Execution::mutable_side() {
  std::string* _s = _internal_mutable_side();
  // @@protoc_insertion_point(field_mutable:protobuf.Execution.side)
  return _s;
}
inline const std::string& Execution::_internal_side() const {
  return _impl_.side_.Get();
}
inline void Execution::_internal_set_side(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000010u;


  _impl_.side_.Set(value, GetArenaForAllocation());
}
inline std::string* Execution::_internal_mutable_side() {
  _impl_._has_bits_[0] |= 0x00000010u;
  return _impl_.side_.Mutable( GetArenaForAllocation());
}
inline std::string* Execution::release_side() {
  // @@protoc_insertion_point(field_release:protobuf.Execution.side)
  if ((_impl_._has_bits_[0] & 0x00000010u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000010u;
  auto* released = _impl_.side_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.side_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void Execution::set_allocated_side(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000010u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000010u;
  }
  _impl_.side_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.side_.IsDefault()) {
          _impl_.side_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.Execution.side)
}

// optional string shares = 7;
inline bool Execution::has_shares() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline void Execution::clear_shares() {
  _impl_.shares_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline const std::string& Execution::shares() const {
  // @@protoc_insertion_point(field_get:protobuf.Execution.shares)
  return _internal_shares();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Execution::set_shares(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000020u;
  _impl_.shares_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.Execution.shares)
}
inline std::string* Execution::mutable_shares() {
  std::string* _s = _internal_mutable_shares();
  // @@protoc_insertion_point(field_mutable:protobuf.Execution.shares)
  return _s;
}
inline const std::string& Execution::_internal_shares() const {
  return _impl_.shares_.Get();
}
inline void Execution::_internal_set_shares(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000020u;


  _impl_.shares_.Set(value, GetArenaForAllocation());
}
inline std::string* Execution::_internal_mutable_shares() {
  _impl_._has_bits_[0] |= 0x00000020u;
  return _impl_.shares_.Mutable( GetArenaForAllocation());
}
inline std::string* Execution::release_shares() {
  // @@protoc_insertion_point(field_release:protobuf.Execution.shares)
  if ((_impl_._has_bits_[0] & 0x00000020u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000020u;
  auto* released = _impl_.shares_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.shares_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void Execution::set_allocated_shares(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000020u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000020u;
  }
  _impl_.shares_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.shares_.IsDefault()) {
          _impl_.shares_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.Execution.shares)
}

// optional double price = 8;
inline bool Execution::has_price() const {
  bool value = (_impl_._has_bits_[0] & 0x00002000u) != 0;
  return value;
}
inline void Execution::clear_price() {
  _impl_.price_ = 0;
  _impl_._has_bits_[0] &= ~0x00002000u;
}
inline double Execution::price() const {
  // @@protoc_insertion_point(field_get:protobuf.Execution.price)
  return _internal_price();
}
inline void Execution::set_price(double value) {
  _internal_set_price(value);
  // @@protoc_insertion_point(field_set:protobuf.Execution.price)
}
inline double Execution::_internal_price() const {
  return _impl_.price_;
}
inline void Execution::_internal_set_price(double value) {
  _impl_._has_bits_[0] |= 0x00002000u;
  _impl_.price_ = value;
}

// optional int64 permId = 9;
inline bool Execution::has_permid() const {
  bool value = (_impl_._has_bits_[0] & 0x00004000u) != 0;
  return value;
}
inline void Execution::clear_permid() {
  _impl_.permid_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00004000u;
}
inline ::int64_t Execution::permid() const {
  // @@protoc_insertion_point(field_get:protobuf.Execution.permId)
  return _internal_permid();
}
inline void Execution::set_permid(::int64_t value) {
  _internal_set_permid(value);
  // @@protoc_insertion_point(field_set:protobuf.Execution.permId)
}
inline ::int64_t Execution::_internal_permid() const {
  return _impl_.permid_;
}
inline void Execution::_internal_set_permid(::int64_t value) {
  _impl_._has_bits_[0] |= 0x00004000u;
  _impl_.permid_ = value;
}

// optional int32 clientId = 10;
inline bool Execution::has_clientid() const {
  bool value = (_impl_._has_bits_[0] & 0x00001000u) != 0;
  return value;
}
inline void Execution::clear_clientid() {
  _impl_.clientid_ = 0;
  _impl_._has_bits_[0] &= ~0x00001000u;
}
inline ::int32_t Execution::clientid() const {
  // @@protoc_insertion_point(field_get:protobuf.Execution.clientId)
  return _internal_clientid();
}
inline void Execution::set_clientid(::int32_t value) {
  _internal_set_clientid(value);
  // @@protoc_insertion_point(field_set:protobuf.Execution.clientId)
}
inline ::int32_t Execution::_internal_clientid() const {
  return _impl_.clientid_;
}
inline void Execution::_internal_set_clientid(::int32_t value) {
  _impl_._has_bits_[0] |= 0x00001000u;
  _impl_.clientid_ = value;
}

// optional bool isLiquidation = 11;
inline bool Execution::has_isliquidation() const {
  bool value = (_impl_._has_bits_[0] & 0x00020000u) != 0;
  return value;
}
inline void Execution::clear_isliquidation() {
  _impl_.isliquidation_ = false;
  _impl_._has_bits_[0] &= ~0x00020000u;
}
inline bool Execution::isliquidation() const {
  // @@protoc_insertion_point(field_get:protobuf.Execution.isLiquidation)
  return _internal_isliquidation();
}
inline void Execution::set_isliquidation(bool value) {
  _internal_set_isliquidation(value);
  // @@protoc_insertion_point(field_set:protobuf.Execution.isLiquidation)
}
inline bool Execution::_internal_isliquidation() const {
  return _impl_.isliquidation_;
}
inline void Execution::_internal_set_isliquidation(bool value) {
  _impl_._has_bits_[0] |= 0x00020000u;
  _impl_.isliquidation_ = value;
}

// optional string cumQty = 12;
inline bool Execution::has_cumqty() const {
  bool value = (_impl_._has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline void Execution::clear_cumqty() {
  _impl_.cumqty_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000040u;
}
inline const std::string& Execution::cumqty() const {
  // @@protoc_insertion_point(field_get:protobuf.Execution.cumQty)
  return _internal_cumqty();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Execution::set_cumqty(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000040u;
  _impl_.cumqty_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.Execution.cumQty)
}
inline std::string* Execution::mutable_cumqty() {
  std::string* _s = _internal_mutable_cumqty();
  // @@protoc_insertion_point(field_mutable:protobuf.Execution.cumQty)
  return _s;
}
inline const std::string& Execution::_internal_cumqty() const {
  return _impl_.cumqty_.Get();
}
inline void Execution::_internal_set_cumqty(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000040u;


  _impl_.cumqty_.Set(value, GetArenaForAllocation());
}
inline std::string* Execution::_internal_mutable_cumqty() {
  _impl_._has_bits_[0] |= 0x00000040u;
  return _impl_.cumqty_.Mutable( GetArenaForAllocation());
}
inline std::string* Execution::release_cumqty() {
  // @@protoc_insertion_point(field_release:protobuf.Execution.cumQty)
  if ((_impl_._has_bits_[0] & 0x00000040u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000040u;
  auto* released = _impl_.cumqty_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.cumqty_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void Execution::set_allocated_cumqty(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000040u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000040u;
  }
  _impl_.cumqty_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.cumqty_.IsDefault()) {
          _impl_.cumqty_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.Execution.cumQty)
}

// optional double avgPrice = 13;
inline bool Execution::has_avgprice() const {
  bool value = (_impl_._has_bits_[0] & 0x00008000u) != 0;
  return value;
}
inline void Execution::clear_avgprice() {
  _impl_.avgprice_ = 0;
  _impl_._has_bits_[0] &= ~0x00008000u;
}
inline double Execution::avgprice() const {
  // @@protoc_insertion_point(field_get:protobuf.Execution.avgPrice)
  return _internal_avgprice();
}
inline void Execution::set_avgprice(double value) {
  _internal_set_avgprice(value);
  // @@protoc_insertion_point(field_set:protobuf.Execution.avgPrice)
}
inline double Execution::_internal_avgprice() const {
  return _impl_.avgprice_;
}
inline void Execution::_internal_set_avgprice(double value) {
  _impl_._has_bits_[0] |= 0x00008000u;
  _impl_.avgprice_ = value;
}

// optional string orderRef = 14;
inline bool Execution::has_orderref() const {
  bool value = (_impl_._has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline void Execution::clear_orderref() {
  _impl_.orderref_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000080u;
}
inline const std::string& Execution::orderref() const {
  // @@protoc_insertion_point(field_get:protobuf.Execution.orderRef)
  return _internal_orderref();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Execution::set_orderref(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000080u;
  _impl_.orderref_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.Execution.orderRef)
}
inline std::string* Execution::mutable_orderref() {
  std::string* _s = _internal_mutable_orderref();
  // @@protoc_insertion_point(field_mutable:protobuf.Execution.orderRef)
  return _s;
}
inline const std::string& Execution::_internal_orderref() const {
  return _impl_.orderref_.Get();
}
inline void Execution::_internal_set_orderref(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000080u;


  _impl_.orderref_.Set(value, GetArenaForAllocation());
}
inline std::string* Execution::_internal_mutable_orderref() {
  _impl_._has_bits_[0] |= 0x00000080u;
  return _impl_.orderref_.Mutable( GetArenaForAllocation());
}
inline std::string* Execution::release_orderref() {
  // @@protoc_insertion_point(field_release:protobuf.Execution.orderRef)
  if ((_impl_._has_bits_[0] & 0x00000080u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000080u;
  auto* released = _impl_.orderref_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.orderref_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void Execution::set_allocated_orderref(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000080u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000080u;
  }
  _impl_.orderref_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.orderref_.IsDefault()) {
          _impl_.orderref_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.Execution.orderRef)
}

// optional string evRule = 15;
inline bool Execution::has_evrule() const {
  bool value = (_impl_._has_bits_[0] & 0x00000100u) != 0;
  return value;
}
inline void Execution::clear_evrule() {
  _impl_.evrule_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000100u;
}
inline const std::string& Execution::evrule() const {
  // @@protoc_insertion_point(field_get:protobuf.Execution.evRule)
  return _internal_evrule();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Execution::set_evrule(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000100u;
  _impl_.evrule_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.Execution.evRule)
}
inline std::string* Execution::mutable_evrule() {
  std::string* _s = _internal_mutable_evrule();
  // @@protoc_insertion_point(field_mutable:protobuf.Execution.evRule)
  return _s;
}
inline const std::string& Execution::_internal_evrule() const {
  return _impl_.evrule_.Get();
}
inline void Execution::_internal_set_evrule(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000100u;


  _impl_.evrule_.Set(value, GetArenaForAllocation());
}
inline std::string* Execution::_internal_mutable_evrule() {
  _impl_._has_bits_[0] |= 0x00000100u;
  return _impl_.evrule_.Mutable( GetArenaForAllocation());
}
inline std::string* Execution::release_evrule() {
  // @@protoc_insertion_point(field_release:protobuf.Execution.evRule)
  if ((_impl_._has_bits_[0] & 0x00000100u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000100u;
  auto* released = _impl_.evrule_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.evrule_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void Execution::set_allocated_evrule(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000100u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000100u;
  }
  _impl_.evrule_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.evrule_.IsDefault()) {
          _impl_.evrule_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.Execution.evRule)
}

// optional double evMultiplier = 16;
inline bool Execution::has_evmultiplier() const {
  bool value = (_impl_._has_bits_[0] & 0x00010000u) != 0;
  return value;
}
inline void Execution::clear_evmultiplier() {
  _impl_.evmultiplier_ = 0;
  _impl_._has_bits_[0] &= ~0x00010000u;
}
inline double Execution::evmultiplier() const {
  // @@protoc_insertion_point(field_get:protobuf.Execution.evMultiplier)
  return _internal_evmultiplier();
}
inline void Execution::set_evmultiplier(double value) {
  _internal_set_evmultiplier(value);
  // @@protoc_insertion_point(field_set:protobuf.Execution.evMultiplier)
}
inline double Execution::_internal_evmultiplier() const {
  return _impl_.evmultiplier_;
}
inline void Execution::_internal_set_evmultiplier(double value) {
  _impl_._has_bits_[0] |= 0x00010000u;
  _impl_.evmultiplier_ = value;
}

// optional string modelCode = 17;
inline bool Execution::has_modelcode() const {
  bool value = (_impl_._has_bits_[0] & 0x00000200u) != 0;
  return value;
}
inline void Execution::clear_modelcode() {
  _impl_.modelcode_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000200u;
}
inline const std::string& Execution::modelcode() const {
  // @@protoc_insertion_point(field_get:protobuf.Execution.modelCode)
  return _internal_modelcode();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Execution::set_modelcode(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000200u;
  _impl_.modelcode_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.Execution.modelCode)
}
inline std::string* Execution::mutable_modelcode() {
  std::string* _s = _internal_mutable_modelcode();
  // @@protoc_insertion_point(field_mutable:protobuf.Execution.modelCode)
  return _s;
}
inline const std::string& Execution::_internal_modelcode() const {
  return _impl_.modelcode_.Get();
}
inline void Execution::_internal_set_modelcode(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000200u;


  _impl_.modelcode_.Set(value, GetArenaForAllocation());
}
inline std::string* Execution::_internal_mutable_modelcode() {
  _impl_._has_bits_[0] |= 0x00000200u;
  return _impl_.modelcode_.Mutable( GetArenaForAllocation());
}
inline std::string* Execution::release_modelcode() {
  // @@protoc_insertion_point(field_release:protobuf.Execution.modelCode)
  if ((_impl_._has_bits_[0] & 0x00000200u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000200u;
  auto* released = _impl_.modelcode_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.modelcode_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void Execution::set_allocated_modelcode(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000200u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000200u;
  }
  _impl_.modelcode_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.modelcode_.IsDefault()) {
          _impl_.modelcode_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.Execution.modelCode)
}

// optional int32 lastLiquidity = 18;
inline bool Execution::has_lastliquidity() const {
  bool value = (_impl_._has_bits_[0] & 0x00080000u) != 0;
  return value;
}
inline void Execution::clear_lastliquidity() {
  _impl_.lastliquidity_ = 0;
  _impl_._has_bits_[0] &= ~0x00080000u;
}
inline ::int32_t Execution::lastliquidity() const {
  // @@protoc_insertion_point(field_get:protobuf.Execution.lastLiquidity)
  return _internal_lastliquidity();
}
inline void Execution::set_lastliquidity(::int32_t value) {
  _internal_set_lastliquidity(value);
  // @@protoc_insertion_point(field_set:protobuf.Execution.lastLiquidity)
}
inline ::int32_t Execution::_internal_lastliquidity() const {
  return _impl_.lastliquidity_;
}
inline void Execution::_internal_set_lastliquidity(::int32_t value) {
  _impl_._has_bits_[0] |= 0x00080000u;
  _impl_.lastliquidity_ = value;
}

// optional bool isPriceRevisionPending = 19;
inline bool Execution::has_ispricerevisionpending() const {
  bool value = (_impl_._has_bits_[0] & 0x00040000u) != 0;
  return value;
}
inline void Execution::clear_ispricerevisionpending() {
  _impl_.ispricerevisionpending_ = false;
  _impl_._has_bits_[0] &= ~0x00040000u;
}
inline bool Execution::ispricerevisionpending() const {
  // @@protoc_insertion_point(field_get:protobuf.Execution.isPriceRevisionPending)
  return _internal_ispricerevisionpending();
}
inline void Execution::set_ispricerevisionpending(bool value) {
  _internal_set_ispricerevisionpending(value);
  // @@protoc_insertion_point(field_set:protobuf.Execution.isPriceRevisionPending)
}
inline bool Execution::_internal_ispricerevisionpending() const {
  return _impl_.ispricerevisionpending_;
}
inline void Execution::_internal_set_ispricerevisionpending(bool value) {
  _impl_._has_bits_[0] |= 0x00040000u;
  _impl_.ispricerevisionpending_ = value;
}

// optional string submitter = 20;
inline bool Execution::has_submitter() const {
  bool value = (_impl_._has_bits_[0] & 0x00000400u) != 0;
  return value;
}
inline void Execution::clear_submitter() {
  _impl_.submitter_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000400u;
}
inline const std::string& Execution::submitter() const {
  // @@protoc_insertion_point(field_get:protobuf.Execution.submitter)
  return _internal_submitter();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Execution::set_submitter(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000400u;
  _impl_.submitter_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.Execution.submitter)
}
inline std::string* Execution::mutable_submitter() {
  std::string* _s = _internal_mutable_submitter();
  // @@protoc_insertion_point(field_mutable:protobuf.Execution.submitter)
  return _s;
}
inline const std::string& Execution::_internal_submitter() const {
  return _impl_.submitter_.Get();
}
inline void Execution::_internal_set_submitter(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000400u;


  _impl_.submitter_.Set(value, GetArenaForAllocation());
}
inline std::string* Execution::_internal_mutable_submitter() {
  _impl_._has_bits_[0] |= 0x00000400u;
  return _impl_.submitter_.Mutable( GetArenaForAllocation());
}
inline std::string* Execution::release_submitter() {
  // @@protoc_insertion_point(field_release:protobuf.Execution.submitter)
  if ((_impl_._has_bits_[0] & 0x00000400u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000400u;
  auto* released = _impl_.submitter_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.submitter_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void Execution::set_allocated_submitter(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000400u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000400u;
  }
  _impl_.submitter_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.submitter_.IsDefault()) {
          _impl_.submitter_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.Execution.submitter)
}

// optional int32 optExerciseOrLapseType = 21;
inline bool Execution::has_optexerciseorlapsetype() const {
  bool value = (_impl_._has_bits_[0] & 0x00100000u) != 0;
  return value;
}
inline void Execution::clear_optexerciseorlapsetype() {
  _impl_.optexerciseorlapsetype_ = 0;
  _impl_._has_bits_[0] &= ~0x00100000u;
}
inline ::int32_t Execution::optexerciseorlapsetype() const {
  // @@protoc_insertion_point(field_get:protobuf.Execution.optExerciseOrLapseType)
  return _internal_optexerciseorlapsetype();
}
inline void Execution::set_optexerciseorlapsetype(::int32_t value) {
  _internal_set_optexerciseorlapsetype(value);
  // @@protoc_insertion_point(field_set:protobuf.Execution.optExerciseOrLapseType)
}
inline ::int32_t Execution::_internal_optexerciseorlapsetype() const {
  return _impl_.optexerciseorlapsetype_;
}
inline void Execution::_internal_set_optexerciseorlapsetype(::int32_t value) {
  _impl_._has_bits_[0] |= 0x00100000u;
  _impl_.optexerciseorlapsetype_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_Execution_2eproto_2epb_2eh
