// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OrderAllocation.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_OrderAllocation_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_OrderAllocation_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4023000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4023004 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_OrderAllocation_2eproto

PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_OrderAllocation_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable
    descriptor_table_OrderAllocation_2eproto;
namespace protobuf {
class OrderAllocation;
struct OrderAllocationDefaultTypeInternal;
extern OrderAllocationDefaultTypeInternal _OrderAllocation_default_instance_;
}  // namespace protobuf
PROTOBUF_NAMESPACE_OPEN
template <>
::protobuf::OrderAllocation* Arena::CreateMaybeMessage<::protobuf::OrderAllocation>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

namespace protobuf {

// ===================================================================


// -------------------------------------------------------------------

class OrderAllocation final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protobuf.OrderAllocation) */ {
 public:
  inline OrderAllocation() : OrderAllocation(nullptr) {}
  ~OrderAllocation() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR OrderAllocation(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  OrderAllocation(const OrderAllocation& from);
  OrderAllocation(OrderAllocation&& from) noexcept
    : OrderAllocation() {
    *this = ::std::move(from);
  }

  inline OrderAllocation& operator=(const OrderAllocation& from) {
    CopyFrom(from);
    return *this;
  }
  inline OrderAllocation& operator=(OrderAllocation&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const OrderAllocation& default_instance() {
    return *internal_default_instance();
  }
  static inline const OrderAllocation* internal_default_instance() {
    return reinterpret_cast<const OrderAllocation*>(
               &_OrderAllocation_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(OrderAllocation& a, OrderAllocation& b) {
    a.Swap(&b);
  }
  inline void Swap(OrderAllocation* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OrderAllocation* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  OrderAllocation* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<OrderAllocation>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const OrderAllocation& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const OrderAllocation& from) {
    OrderAllocation::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(OrderAllocation* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "protobuf.OrderAllocation";
  }
  protected:
  explicit OrderAllocation(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAccountFieldNumber = 1,
    kPositionFieldNumber = 2,
    kPositionDesiredFieldNumber = 3,
    kPositionAfterFieldNumber = 4,
    kDesiredAllocQtyFieldNumber = 5,
    kAllowedAllocQtyFieldNumber = 6,
    kIsMonetaryFieldNumber = 7,
  };
  // optional string account = 1;
  bool has_account() const;
  void clear_account() ;
  const std::string& account() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_account(Arg_&& arg, Args_... args);
  std::string* mutable_account();
  PROTOBUF_NODISCARD std::string* release_account();
  void set_allocated_account(std::string* ptr);

  private:
  const std::string& _internal_account() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_account(
      const std::string& value);
  std::string* _internal_mutable_account();

  public:
  // optional string position = 2;
  bool has_position() const;
  void clear_position() ;
  const std::string& position() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_position(Arg_&& arg, Args_... args);
  std::string* mutable_position();
  PROTOBUF_NODISCARD std::string* release_position();
  void set_allocated_position(std::string* ptr);

  private:
  const std::string& _internal_position() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_position(
      const std::string& value);
  std::string* _internal_mutable_position();

  public:
  // optional string positionDesired = 3;
  bool has_positiondesired() const;
  void clear_positiondesired() ;
  const std::string& positiondesired() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_positiondesired(Arg_&& arg, Args_... args);
  std::string* mutable_positiondesired();
  PROTOBUF_NODISCARD std::string* release_positiondesired();
  void set_allocated_positiondesired(std::string* ptr);

  private:
  const std::string& _internal_positiondesired() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_positiondesired(
      const std::string& value);
  std::string* _internal_mutable_positiondesired();

  public:
  // optional string positionAfter = 4;
  bool has_positionafter() const;
  void clear_positionafter() ;
  const std::string& positionafter() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_positionafter(Arg_&& arg, Args_... args);
  std::string* mutable_positionafter();
  PROTOBUF_NODISCARD std::string* release_positionafter();
  void set_allocated_positionafter(std::string* ptr);

  private:
  const std::string& _internal_positionafter() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_positionafter(
      const std::string& value);
  std::string* _internal_mutable_positionafter();

  public:
  // optional string desiredAllocQty = 5;
  bool has_desiredallocqty() const;
  void clear_desiredallocqty() ;
  const std::string& desiredallocqty() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_desiredallocqty(Arg_&& arg, Args_... args);
  std::string* mutable_desiredallocqty();
  PROTOBUF_NODISCARD std::string* release_desiredallocqty();
  void set_allocated_desiredallocqty(std::string* ptr);

  private:
  const std::string& _internal_desiredallocqty() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_desiredallocqty(
      const std::string& value);
  std::string* _internal_mutable_desiredallocqty();

  public:
  // optional string allowedAllocQty = 6;
  bool has_allowedallocqty() const;
  void clear_allowedallocqty() ;
  const std::string& allowedallocqty() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_allowedallocqty(Arg_&& arg, Args_... args);
  std::string* mutable_allowedallocqty();
  PROTOBUF_NODISCARD std::string* release_allowedallocqty();
  void set_allocated_allowedallocqty(std::string* ptr);

  private:
  const std::string& _internal_allowedallocqty() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_allowedallocqty(
      const std::string& value);
  std::string* _internal_mutable_allowedallocqty();

  public:
  // optional bool isMonetary = 7;
  bool has_ismonetary() const;
  void clear_ismonetary() ;
  bool ismonetary() const;
  void set_ismonetary(bool value);

  private:
  bool _internal_ismonetary() const;
  void _internal_set_ismonetary(bool value);

  public:
  // @@protoc_insertion_point(class_scope:protobuf.OrderAllocation)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr account_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr position_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr positiondesired_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr positionafter_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr desiredallocqty_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr allowedallocqty_;
    bool ismonetary_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_OrderAllocation_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// OrderAllocation

// optional string account = 1;
inline bool OrderAllocation::has_account() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void OrderAllocation::clear_account() {
  _impl_.account_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& OrderAllocation::account() const {
  // @@protoc_insertion_point(field_get:protobuf.OrderAllocation.account)
  return _internal_account();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void OrderAllocation::set_account(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.account_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.OrderAllocation.account)
}
inline std::string* OrderAllocation::mutable_account() {
  std::string* _s = _internal_mutable_account();
  // @@protoc_insertion_point(field_mutable:protobuf.OrderAllocation.account)
  return _s;
}
inline const std::string& OrderAllocation::_internal_account() const {
  return _impl_.account_.Get();
}
inline void OrderAllocation::_internal_set_account(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;


  _impl_.account_.Set(value, GetArenaForAllocation());
}
inline std::string* OrderAllocation::_internal_mutable_account() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.account_.Mutable( GetArenaForAllocation());
}
inline std::string* OrderAllocation::release_account() {
  // @@protoc_insertion_point(field_release:protobuf.OrderAllocation.account)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.account_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.account_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void OrderAllocation::set_allocated_account(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.account_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.account_.IsDefault()) {
          _impl_.account_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.OrderAllocation.account)
}

// optional string position = 2;
inline bool OrderAllocation::has_position() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void OrderAllocation::clear_position() {
  _impl_.position_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& OrderAllocation::position() const {
  // @@protoc_insertion_point(field_get:protobuf.OrderAllocation.position)
  return _internal_position();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void OrderAllocation::set_position(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.position_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.OrderAllocation.position)
}
inline std::string* OrderAllocation::mutable_position() {
  std::string* _s = _internal_mutable_position();
  // @@protoc_insertion_point(field_mutable:protobuf.OrderAllocation.position)
  return _s;
}
inline const std::string& OrderAllocation::_internal_position() const {
  return _impl_.position_.Get();
}
inline void OrderAllocation::_internal_set_position(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000002u;


  _impl_.position_.Set(value, GetArenaForAllocation());
}
inline std::string* OrderAllocation::_internal_mutable_position() {
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.position_.Mutable( GetArenaForAllocation());
}
inline std::string* OrderAllocation::release_position() {
  // @@protoc_insertion_point(field_release:protobuf.OrderAllocation.position)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.position_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.position_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void OrderAllocation::set_allocated_position(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.position_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.position_.IsDefault()) {
          _impl_.position_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.OrderAllocation.position)
}

// optional string positionDesired = 3;
inline bool OrderAllocation::has_positiondesired() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void OrderAllocation::clear_positiondesired() {
  _impl_.positiondesired_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const std::string& OrderAllocation::positiondesired() const {
  // @@protoc_insertion_point(field_get:protobuf.OrderAllocation.positionDesired)
  return _internal_positiondesired();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void OrderAllocation::set_positiondesired(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.positiondesired_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.OrderAllocation.positionDesired)
}
inline std::string* OrderAllocation::mutable_positiondesired() {
  std::string* _s = _internal_mutable_positiondesired();
  // @@protoc_insertion_point(field_mutable:protobuf.OrderAllocation.positionDesired)
  return _s;
}
inline const std::string& OrderAllocation::_internal_positiondesired() const {
  return _impl_.positiondesired_.Get();
}
inline void OrderAllocation::_internal_set_positiondesired(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000004u;


  _impl_.positiondesired_.Set(value, GetArenaForAllocation());
}
inline std::string* OrderAllocation::_internal_mutable_positiondesired() {
  _impl_._has_bits_[0] |= 0x00000004u;
  return _impl_.positiondesired_.Mutable( GetArenaForAllocation());
}
inline std::string* OrderAllocation::release_positiondesired() {
  // @@protoc_insertion_point(field_release:protobuf.OrderAllocation.positionDesired)
  if ((_impl_._has_bits_[0] & 0x00000004u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004u;
  auto* released = _impl_.positiondesired_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.positiondesired_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void OrderAllocation::set_allocated_positiondesired(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.positiondesired_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.positiondesired_.IsDefault()) {
          _impl_.positiondesired_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.OrderAllocation.positionDesired)
}

// optional string positionAfter = 4;
inline bool OrderAllocation::has_positionafter() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void OrderAllocation::clear_positionafter() {
  _impl_.positionafter_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline const std::string& OrderAllocation::positionafter() const {
  // @@protoc_insertion_point(field_get:protobuf.OrderAllocation.positionAfter)
  return _internal_positionafter();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void OrderAllocation::set_positionafter(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.positionafter_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.OrderAllocation.positionAfter)
}
inline std::string* OrderAllocation::mutable_positionafter() {
  std::string* _s = _internal_mutable_positionafter();
  // @@protoc_insertion_point(field_mutable:protobuf.OrderAllocation.positionAfter)
  return _s;
}
inline const std::string& OrderAllocation::_internal_positionafter() const {
  return _impl_.positionafter_.Get();
}
inline void OrderAllocation::_internal_set_positionafter(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000008u;


  _impl_.positionafter_.Set(value, GetArenaForAllocation());
}
inline std::string* OrderAllocation::_internal_mutable_positionafter() {
  _impl_._has_bits_[0] |= 0x00000008u;
  return _impl_.positionafter_.Mutable( GetArenaForAllocation());
}
inline std::string* OrderAllocation::release_positionafter() {
  // @@protoc_insertion_point(field_release:protobuf.OrderAllocation.positionAfter)
  if ((_impl_._has_bits_[0] & 0x00000008u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000008u;
  auto* released = _impl_.positionafter_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.positionafter_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void OrderAllocation::set_allocated_positionafter(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  _impl_.positionafter_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.positionafter_.IsDefault()) {
          _impl_.positionafter_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.OrderAllocation.positionAfter)
}

// optional string desiredAllocQty = 5;
inline bool OrderAllocation::has_desiredallocqty() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline void OrderAllocation::clear_desiredallocqty() {
  _impl_.desiredallocqty_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline const std::string& OrderAllocation::desiredallocqty() const {
  // @@protoc_insertion_point(field_get:protobuf.OrderAllocation.desiredAllocQty)
  return _internal_desiredallocqty();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void OrderAllocation::set_desiredallocqty(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.desiredallocqty_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.OrderAllocation.desiredAllocQty)
}
inline std::string* OrderAllocation::mutable_desiredallocqty() {
  std::string* _s = _internal_mutable_desiredallocqty();
  // @@protoc_insertion_point(field_mutable:protobuf.OrderAllocation.desiredAllocQty)
  return _s;
}
inline const std::string& OrderAllocation::_internal_desiredallocqty() const {
  return _impl_.desiredallocqty_.Get();
}
inline void OrderAllocation::_internal_set_desiredallocqty(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000010u;


  _impl_.desiredallocqty_.Set(value, GetArenaForAllocation());
}
inline std::string* OrderAllocation::_internal_mutable_desiredallocqty() {
  _impl_._has_bits_[0] |= 0x00000010u;
  return _impl_.desiredallocqty_.Mutable( GetArenaForAllocation());
}
inline std::string* OrderAllocation::release_desiredallocqty() {
  // @@protoc_insertion_point(field_release:protobuf.OrderAllocation.desiredAllocQty)
  if ((_impl_._has_bits_[0] & 0x00000010u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000010u;
  auto* released = _impl_.desiredallocqty_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.desiredallocqty_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void OrderAllocation::set_allocated_desiredallocqty(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000010u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000010u;
  }
  _impl_.desiredallocqty_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.desiredallocqty_.IsDefault()) {
          _impl_.desiredallocqty_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.OrderAllocation.desiredAllocQty)
}

// optional string allowedAllocQty = 6;
inline bool OrderAllocation::has_allowedallocqty() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline void OrderAllocation::clear_allowedallocqty() {
  _impl_.allowedallocqty_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline const std::string& OrderAllocation::allowedallocqty() const {
  // @@protoc_insertion_point(field_get:protobuf.OrderAllocation.allowedAllocQty)
  return _internal_allowedallocqty();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void OrderAllocation::set_allowedallocqty(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000020u;
  _impl_.allowedallocqty_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.OrderAllocation.allowedAllocQty)
}
inline std::string* OrderAllocation::mutable_allowedallocqty() {
  std::string* _s = _internal_mutable_allowedallocqty();
  // @@protoc_insertion_point(field_mutable:protobuf.OrderAllocation.allowedAllocQty)
  return _s;
}
inline const std::string& OrderAllocation::_internal_allowedallocqty() const {
  return _impl_.allowedallocqty_.Get();
}
inline void OrderAllocation::_internal_set_allowedallocqty(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000020u;


  _impl_.allowedallocqty_.Set(value, GetArenaForAllocation());
}
inline std::string* OrderAllocation::_internal_mutable_allowedallocqty() {
  _impl_._has_bits_[0] |= 0x00000020u;
  return _impl_.allowedallocqty_.Mutable( GetArenaForAllocation());
}
inline std::string* OrderAllocation::release_allowedallocqty() {
  // @@protoc_insertion_point(field_release:protobuf.OrderAllocation.allowedAllocQty)
  if ((_impl_._has_bits_[0] & 0x00000020u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000020u;
  auto* released = _impl_.allowedallocqty_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.allowedallocqty_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void OrderAllocation::set_allocated_allowedallocqty(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000020u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000020u;
  }
  _impl_.allowedallocqty_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.allowedallocqty_.IsDefault()) {
          _impl_.allowedallocqty_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.OrderAllocation.allowedAllocQty)
}

// optional bool isMonetary = 7;
inline bool OrderAllocation::has_ismonetary() const {
  bool value = (_impl_._has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline void OrderAllocation::clear_ismonetary() {
  _impl_.ismonetary_ = false;
  _impl_._has_bits_[0] &= ~0x00000040u;
}
inline bool OrderAllocation::ismonetary() const {
  // @@protoc_insertion_point(field_get:protobuf.OrderAllocation.isMonetary)
  return _internal_ismonetary();
}
inline void OrderAllocation::set_ismonetary(bool value) {
  _internal_set_ismonetary(value);
  // @@protoc_insertion_point(field_set:protobuf.OrderAllocation.isMonetary)
}
inline bool OrderAllocation::_internal_ismonetary() const {
  return _impl_.ismonetary_;
}
inline void OrderAllocation::_internal_set_ismonetary(bool value) {
  _impl_._has_bits_[0] |= 0x00000040u;
  _impl_.ismonetary_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_OrderAllocation_2eproto_2epb_2eh
