// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CancelOrderRequest.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_CancelOrderRequest_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_CancelOrderRequest_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4023000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4023004 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "OrderCancel.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_CancelOrderRequest_2eproto

PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_CancelOrderRequest_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable
    descriptor_table_CancelOrderRequest_2eproto;
namespace protobuf {
class CancelOrderRequest;
struct CancelOrderRequestDefaultTypeInternal;
extern CancelOrderRequestDefaultTypeInternal _CancelOrderRequest_default_instance_;
}  // namespace protobuf
PROTOBUF_NAMESPACE_OPEN
template <>
::protobuf::CancelOrderRequest* Arena::CreateMaybeMessage<::protobuf::CancelOrderRequest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

namespace protobuf {

// ===================================================================


// -------------------------------------------------------------------

class CancelOrderRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protobuf.CancelOrderRequest) */ {
 public:
  inline CancelOrderRequest() : CancelOrderRequest(nullptr) {}
  ~CancelOrderRequest() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR CancelOrderRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CancelOrderRequest(const CancelOrderRequest& from);
  CancelOrderRequest(CancelOrderRequest&& from) noexcept
    : CancelOrderRequest() {
    *this = ::std::move(from);
  }

  inline CancelOrderRequest& operator=(const CancelOrderRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline CancelOrderRequest& operator=(CancelOrderRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CancelOrderRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const CancelOrderRequest* internal_default_instance() {
    return reinterpret_cast<const CancelOrderRequest*>(
               &_CancelOrderRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CancelOrderRequest& a, CancelOrderRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(CancelOrderRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CancelOrderRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CancelOrderRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CancelOrderRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CancelOrderRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CancelOrderRequest& from) {
    CancelOrderRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CancelOrderRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "protobuf.CancelOrderRequest";
  }
  protected:
  explicit CancelOrderRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kOrderCancelFieldNumber = 2,
    kOrderIdFieldNumber = 1,
  };
  // optional .protobuf.OrderCancel orderCancel = 2;
  bool has_ordercancel() const;
  void clear_ordercancel() ;
  const ::protobuf::OrderCancel& ordercancel() const;
  PROTOBUF_NODISCARD ::protobuf::OrderCancel* release_ordercancel();
  ::protobuf::OrderCancel* mutable_ordercancel();
  void set_allocated_ordercancel(::protobuf::OrderCancel* ordercancel);
  private:
  const ::protobuf::OrderCancel& _internal_ordercancel() const;
  ::protobuf::OrderCancel* _internal_mutable_ordercancel();
  public:
  void unsafe_arena_set_allocated_ordercancel(
      ::protobuf::OrderCancel* ordercancel);
  ::protobuf::OrderCancel* unsafe_arena_release_ordercancel();
  // optional int32 orderId = 1;
  bool has_orderid() const;
  void clear_orderid() ;
  ::int32_t orderid() const;
  void set_orderid(::int32_t value);

  private:
  ::int32_t _internal_orderid() const;
  void _internal_set_orderid(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:protobuf.CancelOrderRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::protobuf::OrderCancel* ordercancel_;
    ::int32_t orderid_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_CancelOrderRequest_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// CancelOrderRequest

// optional int32 orderId = 1;
inline bool CancelOrderRequest::has_orderid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void CancelOrderRequest::clear_orderid() {
  _impl_.orderid_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::int32_t CancelOrderRequest::orderid() const {
  // @@protoc_insertion_point(field_get:protobuf.CancelOrderRequest.orderId)
  return _internal_orderid();
}
inline void CancelOrderRequest::set_orderid(::int32_t value) {
  _internal_set_orderid(value);
  // @@protoc_insertion_point(field_set:protobuf.CancelOrderRequest.orderId)
}
inline ::int32_t CancelOrderRequest::_internal_orderid() const {
  return _impl_.orderid_;
}
inline void CancelOrderRequest::_internal_set_orderid(::int32_t value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.orderid_ = value;
}

// optional .protobuf.OrderCancel orderCancel = 2;
inline bool CancelOrderRequest::has_ordercancel() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.ordercancel_ != nullptr);
  return value;
}
inline const ::protobuf::OrderCancel& CancelOrderRequest::_internal_ordercancel() const {
  const ::protobuf::OrderCancel* p = _impl_.ordercancel_;
  return p != nullptr ? *p : reinterpret_cast<const ::protobuf::OrderCancel&>(
      ::protobuf::_OrderCancel_default_instance_);
}
inline const ::protobuf::OrderCancel& CancelOrderRequest::ordercancel() const {
  // @@protoc_insertion_point(field_get:protobuf.CancelOrderRequest.orderCancel)
  return _internal_ordercancel();
}
inline void CancelOrderRequest::unsafe_arena_set_allocated_ordercancel(
    ::protobuf::OrderCancel* ordercancel) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.ordercancel_);
  }
  _impl_.ordercancel_ = ordercancel;
  if (ordercancel) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:protobuf.CancelOrderRequest.orderCancel)
}
inline ::protobuf::OrderCancel* CancelOrderRequest::release_ordercancel() {
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::protobuf::OrderCancel* temp = _impl_.ordercancel_;
  _impl_.ordercancel_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::protobuf::OrderCancel* CancelOrderRequest::unsafe_arena_release_ordercancel() {
  // @@protoc_insertion_point(field_release:protobuf.CancelOrderRequest.orderCancel)
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::protobuf::OrderCancel* temp = _impl_.ordercancel_;
  _impl_.ordercancel_ = nullptr;
  return temp;
}
inline ::protobuf::OrderCancel* CancelOrderRequest::_internal_mutable_ordercancel() {
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.ordercancel_ == nullptr) {
    auto* p = CreateMaybeMessage<::protobuf::OrderCancel>(GetArenaForAllocation());
    _impl_.ordercancel_ = p;
  }
  return _impl_.ordercancel_;
}
inline ::protobuf::OrderCancel* CancelOrderRequest::mutable_ordercancel() {
  ::protobuf::OrderCancel* _msg = _internal_mutable_ordercancel();
  // @@protoc_insertion_point(field_mutable:protobuf.CancelOrderRequest.orderCancel)
  return _msg;
}
inline void CancelOrderRequest::set_allocated_ordercancel(::protobuf::OrderCancel* ordercancel) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.ordercancel_);
  }
  if (ordercancel) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(ordercancel));
    if (message_arena != submessage_arena) {
      ordercancel = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, ordercancel, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.ordercancel_ = ordercancel;
  // @@protoc_insertion_point(field_set_allocated:protobuf.CancelOrderRequest.orderCancel)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_CancelOrderRequest_2eproto_2epb_2eh
