// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ComboLeg.proto

#include "ComboLeg.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = ::PROTOBUF_NAMESPACE_ID::internal;
namespace protobuf {
template <typename>
PROTOBUF_CONSTEXPR ComboLeg::ComboLeg(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.action_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.exchange_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.designatedlocation_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.conid_)*/ 0

  , /*decltype(_impl_.ratio_)*/ 0

  , /*decltype(_impl_.openclose_)*/ 0

  , /*decltype(_impl_.shortsalesslot_)*/ 0

  , /*decltype(_impl_.perlegprice_)*/ 0

  , /*decltype(_impl_.exemptcode_)*/ 0
} {}
struct ComboLegDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ComboLegDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ComboLegDefaultTypeInternal() {}
  union {
    ComboLeg _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ComboLegDefaultTypeInternal _ComboLeg_default_instance_;
}  // namespace protobuf
static ::_pb::Metadata file_level_metadata_ComboLeg_2eproto[1];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_ComboLeg_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_ComboLeg_2eproto = nullptr;
const ::uint32_t TableStruct_ComboLeg_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    PROTOBUF_FIELD_OFFSET(::protobuf::ComboLeg, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::protobuf::ComboLeg, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::protobuf::ComboLeg, _impl_.conid_),
    PROTOBUF_FIELD_OFFSET(::protobuf::ComboLeg, _impl_.ratio_),
    PROTOBUF_FIELD_OFFSET(::protobuf::ComboLeg, _impl_.action_),
    PROTOBUF_FIELD_OFFSET(::protobuf::ComboLeg, _impl_.exchange_),
    PROTOBUF_FIELD_OFFSET(::protobuf::ComboLeg, _impl_.openclose_),
    PROTOBUF_FIELD_OFFSET(::protobuf::ComboLeg, _impl_.shortsalesslot_),
    PROTOBUF_FIELD_OFFSET(::protobuf::ComboLeg, _impl_.designatedlocation_),
    PROTOBUF_FIELD_OFFSET(::protobuf::ComboLeg, _impl_.exemptcode_),
    PROTOBUF_FIELD_OFFSET(::protobuf::ComboLeg, _impl_.perlegprice_),
    3,
    4,
    0,
    1,
    5,
    6,
    2,
    8,
    7,
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        { 0, 17, -1, sizeof(::protobuf::ComboLeg)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::protobuf::_ComboLeg_default_instance_._instance,
};
const char descriptor_table_protodef_ComboLeg_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\016ComboLeg.proto\022\010protobuf\"\352\002\n\010ComboLeg\022"
    "\022\n\005conId\030\001 \001(\005H\000\210\001\001\022\022\n\005ratio\030\002 \001(\005H\001\210\001\001\022"
    "\023\n\006action\030\003 \001(\tH\002\210\001\001\022\025\n\010exchange\030\004 \001(\tH\003"
    "\210\001\001\022\026\n\topenClose\030\005 \001(\005H\004\210\001\001\022\033\n\016shortSale"
    "sSlot\030\006 \001(\005H\005\210\001\001\022\037\n\022designatedLocation\030\007"
    " \001(\tH\006\210\001\001\022\027\n\nexemptCode\030\010 \001(\005H\007\210\001\001\022\030\n\013pe"
    "rLegPrice\030\t \001(\001H\010\210\001\001B\010\n\006_conIdB\010\n\006_ratio"
    "B\t\n\007_actionB\013\n\t_exchangeB\014\n\n_openCloseB\021"
    "\n\017_shortSalesSlotB\025\n\023_designatedLocation"
    "B\r\n\013_exemptCodeB\016\n\014_perLegPriceb\006proto3"
};
static ::absl::once_flag descriptor_table_ComboLeg_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_ComboLeg_2eproto = {
    false,
    false,
    399,
    descriptor_table_protodef_ComboLeg_2eproto,
    "ComboLeg.proto",
    &descriptor_table_ComboLeg_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_ComboLeg_2eproto::offsets,
    file_level_metadata_ComboLeg_2eproto,
    file_level_enum_descriptors_ComboLeg_2eproto,
    file_level_service_descriptors_ComboLeg_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_ComboLeg_2eproto_getter() {
  return &descriptor_table_ComboLeg_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_ComboLeg_2eproto(&descriptor_table_ComboLeg_2eproto);
namespace protobuf {
// ===================================================================

class ComboLeg::_Internal {
 public:
  using HasBits = decltype(std::declval<ComboLeg>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(ComboLeg, _impl_._has_bits_);
  static void set_has_conid(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_ratio(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static void set_has_action(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_exchange(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_openclose(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
  static void set_has_shortsalesslot(HasBits* has_bits) {
    (*has_bits)[0] |= 64u;
  }
  static void set_has_designatedlocation(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_exemptcode(HasBits* has_bits) {
    (*has_bits)[0] |= 256u;
  }
  static void set_has_perlegprice(HasBits* has_bits) {
    (*has_bits)[0] |= 128u;
  }
};

ComboLeg::ComboLeg(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:protobuf.ComboLeg)
}
ComboLeg::ComboLeg(const ComboLeg& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ComboLeg* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.action_) {}

    , decltype(_impl_.exchange_) {}

    , decltype(_impl_.designatedlocation_) {}

    , decltype(_impl_.conid_) {}

    , decltype(_impl_.ratio_) {}

    , decltype(_impl_.openclose_) {}

    , decltype(_impl_.shortsalesslot_) {}

    , decltype(_impl_.perlegprice_) {}

    , decltype(_impl_.exemptcode_) {}
  };

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.action_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.action_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_impl_.action_.Set(from._internal_action(), _this->GetArenaForAllocation());
  }
  _impl_.exchange_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.exchange_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if ((from._impl_._has_bits_[0] & 0x00000002u) != 0) {
    _this->_impl_.exchange_.Set(from._internal_exchange(), _this->GetArenaForAllocation());
  }
  _impl_.designatedlocation_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.designatedlocation_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if ((from._impl_._has_bits_[0] & 0x00000004u) != 0) {
    _this->_impl_.designatedlocation_.Set(from._internal_designatedlocation(), _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.conid_, &from._impl_.conid_,
    static_cast<::size_t>(reinterpret_cast<char*>(&_impl_.exemptcode_) -
    reinterpret_cast<char*>(&_impl_.conid_)) + sizeof(_impl_.exemptcode_));
  // @@protoc_insertion_point(copy_constructor:protobuf.ComboLeg)
}

inline void ComboLeg::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.action_) {}

    , decltype(_impl_.exchange_) {}

    , decltype(_impl_.designatedlocation_) {}

    , decltype(_impl_.conid_) { 0 }

    , decltype(_impl_.ratio_) { 0 }

    , decltype(_impl_.openclose_) { 0 }

    , decltype(_impl_.shortsalesslot_) { 0 }

    , decltype(_impl_.perlegprice_) { 0 }

    , decltype(_impl_.exemptcode_) { 0 }

  };
  _impl_.action_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.action_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.exchange_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.exchange_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.designatedlocation_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.designatedlocation_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ComboLeg::~ComboLeg() {
  // @@protoc_insertion_point(destructor:protobuf.ComboLeg)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ComboLeg::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.action_.Destroy();
  _impl_.exchange_.Destroy();
  _impl_.designatedlocation_.Destroy();
}

void ComboLeg::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ComboLeg::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.ComboLeg)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.action_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.exchange_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000004u) {
      _impl_.designatedlocation_.ClearNonDefaultToEmpty();
    }
  }
  if (cached_has_bits & 0x000000f8u) {
    ::memset(&_impl_.conid_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.perlegprice_) -
        reinterpret_cast<char*>(&_impl_.conid_)) + sizeof(_impl_.perlegprice_));
  }
  _impl_.exemptcode_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ComboLeg::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional int32 conId = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 8)) {
          _Internal::set_has_conid(&has_bits);
          _impl_.conid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // optional int32 ratio = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 16)) {
          _Internal::set_has_ratio(&has_bits);
          _impl_.ratio_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // optional string action = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_action();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "protobuf.ComboLeg.action"));
        } else {
          goto handle_unusual;
        }
        continue;
      // optional string exchange = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_exchange();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "protobuf.ComboLeg.exchange"));
        } else {
          goto handle_unusual;
        }
        continue;
      // optional int32 openClose = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 40)) {
          _Internal::set_has_openclose(&has_bits);
          _impl_.openclose_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // optional int32 shortSalesSlot = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 48)) {
          _Internal::set_has_shortsalesslot(&has_bits);
          _impl_.shortsalesslot_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // optional string designatedLocation = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 58)) {
          auto str = _internal_mutable_designatedlocation();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "protobuf.ComboLeg.designatedLocation"));
        } else {
          goto handle_unusual;
        }
        continue;
      // optional int32 exemptCode = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 64)) {
          _Internal::set_has_exemptcode(&has_bits);
          _impl_.exemptcode_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // optional double perLegPrice = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 73)) {
          _Internal::set_has_perlegprice(&has_bits);
          _impl_.perlegprice_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* ComboLeg::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protobuf.ComboLeg)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional int32 conId = 1;
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(
        1, this->_internal_conid(), target);
  }

  // optional int32 ratio = 2;
  if (cached_has_bits & 0x00000010u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(
        2, this->_internal_ratio(), target);
  }

  // optional string action = 3;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_action();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "protobuf.ComboLeg.action");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // optional string exchange = 4;
  if (cached_has_bits & 0x00000002u) {
    const std::string& _s = this->_internal_exchange();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "protobuf.ComboLeg.exchange");
    target = stream->WriteStringMaybeAliased(4, _s, target);
  }

  // optional int32 openClose = 5;
  if (cached_has_bits & 0x00000020u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(
        5, this->_internal_openclose(), target);
  }

  // optional int32 shortSalesSlot = 6;
  if (cached_has_bits & 0x00000040u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(
        6, this->_internal_shortsalesslot(), target);
  }

  // optional string designatedLocation = 7;
  if (cached_has_bits & 0x00000004u) {
    const std::string& _s = this->_internal_designatedlocation();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "protobuf.ComboLeg.designatedLocation");
    target = stream->WriteStringMaybeAliased(7, _s, target);
  }

  // optional int32 exemptCode = 8;
  if (cached_has_bits & 0x00000100u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(
        8, this->_internal_exemptcode(), target);
  }

  // optional double perLegPrice = 9;
  if (cached_has_bits & 0x00000080u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(
        9, this->_internal_perlegprice(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protobuf.ComboLeg)
  return target;
}

::size_t ComboLeg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protobuf.ComboLeg)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    // optional string action = 3;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                      this->_internal_action());
    }

    // optional string exchange = 4;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                      this->_internal_exchange());
    }

    // optional string designatedLocation = 7;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                      this->_internal_designatedlocation());
    }

    // optional int32 conId = 1;
    if (cached_has_bits & 0x00000008u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_conid());
    }

    // optional int32 ratio = 2;
    if (cached_has_bits & 0x00000010u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_ratio());
    }

    // optional int32 openClose = 5;
    if (cached_has_bits & 0x00000020u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_openclose());
    }

    // optional int32 shortSalesSlot = 6;
    if (cached_has_bits & 0x00000040u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_shortsalesslot());
    }

    // optional double perLegPrice = 9;
    if (cached_has_bits & 0x00000080u) {
      total_size += 9;
    }

  }
  // optional int32 exemptCode = 8;
  if (cached_has_bits & 0x00000100u) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_exemptcode());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ComboLeg::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ComboLeg::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ComboLeg::GetClassData() const { return &_class_data_; }


void ComboLeg::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ComboLeg*>(&to_msg);
  auto& from = static_cast<const ComboLeg&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:protobuf.ComboLeg)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_action(from._internal_action());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_exchange(from._internal_exchange());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_internal_set_designatedlocation(from._internal_designatedlocation());
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.conid_ = from._impl_.conid_;
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_impl_.ratio_ = from._impl_.ratio_;
    }
    if (cached_has_bits & 0x00000020u) {
      _this->_impl_.openclose_ = from._impl_.openclose_;
    }
    if (cached_has_bits & 0x00000040u) {
      _this->_impl_.shortsalesslot_ = from._impl_.shortsalesslot_;
    }
    if (cached_has_bits & 0x00000080u) {
      _this->_impl_.perlegprice_ = from._impl_.perlegprice_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  if (cached_has_bits & 0x00000100u) {
    _this->_internal_set_exemptcode(from._internal_exemptcode());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ComboLeg::CopyFrom(const ComboLeg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.ComboLeg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ComboLeg::IsInitialized() const {
  return true;
}

void ComboLeg::InternalSwap(ComboLeg* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.action_, lhs_arena,
                                       &other->_impl_.action_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.exchange_, lhs_arena,
                                       &other->_impl_.exchange_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.designatedlocation_, lhs_arena,
                                       &other->_impl_.designatedlocation_, rhs_arena);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ComboLeg, _impl_.exemptcode_)
      + sizeof(ComboLeg::_impl_.exemptcode_)
      - PROTOBUF_FIELD_OFFSET(ComboLeg, _impl_.conid_)>(
          reinterpret_cast<char*>(&_impl_.conid_),
          reinterpret_cast<char*>(&other->_impl_.conid_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ComboLeg::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ComboLeg_2eproto_getter, &descriptor_table_ComboLeg_2eproto_once,
      file_level_metadata_ComboLeg_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::protobuf::ComboLeg*
Arena::CreateMaybeMessage< ::protobuf::ComboLeg >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobuf::ComboLeg >(arena);
}
PROTOBUF_NAMESPACE_CLOSE
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
