// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DeltaNeutralContract.proto

#include "DeltaNeutralContract.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = ::PROTOBUF_NAMESPACE_ID::internal;
namespace protobuf {
template <typename>
PROTOBUF_CONSTEXPR DeltaNeutralContract::DeltaNeutralContract(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.delta_)*/ 0

  , /*decltype(_impl_.price_)*/ 0

  , /*decltype(_impl_.conid_)*/ 0
} {}
struct DeltaNeutralContractDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DeltaNeutralContractDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DeltaNeutralContractDefaultTypeInternal() {}
  union {
    DeltaNeutralContract _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DeltaNeutralContractDefaultTypeInternal _DeltaNeutralContract_default_instance_;
}  // namespace protobuf
static ::_pb::Metadata file_level_metadata_DeltaNeutralContract_2eproto[1];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_DeltaNeutralContract_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_DeltaNeutralContract_2eproto = nullptr;
const ::uint32_t TableStruct_DeltaNeutralContract_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    PROTOBUF_FIELD_OFFSET(::protobuf::DeltaNeutralContract, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::protobuf::DeltaNeutralContract, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::protobuf::DeltaNeutralContract, _impl_.conid_),
    PROTOBUF_FIELD_OFFSET(::protobuf::DeltaNeutralContract, _impl_.delta_),
    PROTOBUF_FIELD_OFFSET(::protobuf::DeltaNeutralContract, _impl_.price_),
    2,
    0,
    1,
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        { 0, 11, -1, sizeof(::protobuf::DeltaNeutralContract)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::protobuf::_DeltaNeutralContract_default_instance_._instance,
};
const char descriptor_table_protodef_DeltaNeutralContract_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\032DeltaNeutralContract.proto\022\010protobuf\"p"
    "\n\024DeltaNeutralContract\022\022\n\005conId\030\001 \001(\005H\000\210"
    "\001\001\022\022\n\005delta\030\002 \001(\001H\001\210\001\001\022\022\n\005price\030\003 \001(\001H\002\210"
    "\001\001B\010\n\006_conIdB\010\n\006_deltaB\010\n\006_priceb\006proto3"
};
static ::absl::once_flag descriptor_table_DeltaNeutralContract_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_DeltaNeutralContract_2eproto = {
    false,
    false,
    160,
    descriptor_table_protodef_DeltaNeutralContract_2eproto,
    "DeltaNeutralContract.proto",
    &descriptor_table_DeltaNeutralContract_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_DeltaNeutralContract_2eproto::offsets,
    file_level_metadata_DeltaNeutralContract_2eproto,
    file_level_enum_descriptors_DeltaNeutralContract_2eproto,
    file_level_service_descriptors_DeltaNeutralContract_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_DeltaNeutralContract_2eproto_getter() {
  return &descriptor_table_DeltaNeutralContract_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_DeltaNeutralContract_2eproto(&descriptor_table_DeltaNeutralContract_2eproto);
namespace protobuf {
// ===================================================================

class DeltaNeutralContract::_Internal {
 public:
  using HasBits = decltype(std::declval<DeltaNeutralContract>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(DeltaNeutralContract, _impl_._has_bits_);
  static void set_has_conid(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_delta(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_price(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

DeltaNeutralContract::DeltaNeutralContract(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:protobuf.DeltaNeutralContract)
}
DeltaNeutralContract::DeltaNeutralContract(const DeltaNeutralContract& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(), _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(
      from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:protobuf.DeltaNeutralContract)
}

inline void DeltaNeutralContract::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.delta_) { 0 }

    , decltype(_impl_.price_) { 0 }

    , decltype(_impl_.conid_) { 0 }

  };
}

DeltaNeutralContract::~DeltaNeutralContract() {
  // @@protoc_insertion_point(destructor:protobuf.DeltaNeutralContract)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void DeltaNeutralContract::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
}

void DeltaNeutralContract::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void DeltaNeutralContract::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.DeltaNeutralContract)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    ::memset(&_impl_.delta_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.conid_) -
        reinterpret_cast<char*>(&_impl_.delta_)) + sizeof(_impl_.conid_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DeltaNeutralContract::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional int32 conId = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 8)) {
          _Internal::set_has_conid(&has_bits);
          _impl_.conid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // optional double delta = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 17)) {
          _Internal::set_has_delta(&has_bits);
          _impl_.delta_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else {
          goto handle_unusual;
        }
        continue;
      // optional double price = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 25)) {
          _Internal::set_has_price(&has_bits);
          _impl_.price_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* DeltaNeutralContract::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protobuf.DeltaNeutralContract)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional int32 conId = 1;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(
        1, this->_internal_conid(), target);
  }

  // optional double delta = 2;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(
        2, this->_internal_delta(), target);
  }

  // optional double price = 3;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(
        3, this->_internal_price(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protobuf.DeltaNeutralContract)
  return target;
}

::size_t DeltaNeutralContract::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protobuf.DeltaNeutralContract)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    // optional double delta = 2;
    if (cached_has_bits & 0x00000001u) {
      total_size += 9;
    }

    // optional double price = 3;
    if (cached_has_bits & 0x00000002u) {
      total_size += 9;
    }

    // optional int32 conId = 1;
    if (cached_has_bits & 0x00000004u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_conid());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData DeltaNeutralContract::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    DeltaNeutralContract::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*DeltaNeutralContract::GetClassData() const { return &_class_data_; }


void DeltaNeutralContract::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<DeltaNeutralContract*>(&to_msg);
  auto& from = static_cast<const DeltaNeutralContract&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:protobuf.DeltaNeutralContract)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.delta_ = from._impl_.delta_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.price_ = from._impl_.price_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.conid_ = from._impl_.conid_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void DeltaNeutralContract::CopyFrom(const DeltaNeutralContract& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.DeltaNeutralContract)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DeltaNeutralContract::IsInitialized() const {
  return true;
}

void DeltaNeutralContract::InternalSwap(DeltaNeutralContract* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(DeltaNeutralContract, _impl_.conid_)
      + sizeof(DeltaNeutralContract::_impl_.conid_)
      - PROTOBUF_FIELD_OFFSET(DeltaNeutralContract, _impl_.delta_)>(
          reinterpret_cast<char*>(&_impl_.delta_),
          reinterpret_cast<char*>(&other->_impl_.delta_));
}

::PROTOBUF_NAMESPACE_ID::Metadata DeltaNeutralContract::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_DeltaNeutralContract_2eproto_getter, &descriptor_table_DeltaNeutralContract_2eproto_once,
      file_level_metadata_DeltaNeutralContract_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::protobuf::DeltaNeutralContract*
Arena::CreateMaybeMessage< ::protobuf::DeltaNeutralContract >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobuf::DeltaNeutralContract >(arena);
}
PROTOBUF_NAMESPACE_CLOSE
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
