// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Execution.proto

#include "Execution.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = ::PROTOBUF_NAMESPACE_ID::internal;
namespace protobuf {
template <typename>
PROTOBUF_CONSTEXPR Execution::Execution(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.execid_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.time_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.acctnumber_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.exchange_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.side_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.shares_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.cumqty_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.orderref_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.evrule_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.modelcode_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.submitter_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.orderid_)*/ 0

  , /*decltype(_impl_.clientid_)*/ 0

  , /*decltype(_impl_.price_)*/ 0

  , /*decltype(_impl_.permid_)*/ ::int64_t{0}

  , /*decltype(_impl_.avgprice_)*/ 0

  , /*decltype(_impl_.evmultiplier_)*/ 0

  , /*decltype(_impl_.isliquidation_)*/ false

  , /*decltype(_impl_.ispricerevisionpending_)*/ false

  , /*decltype(_impl_.lastliquidity_)*/ 0

  , /*decltype(_impl_.optexerciseorlapsetype_)*/ 0
} {}
struct ExecutionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ExecutionDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ExecutionDefaultTypeInternal() {}
  union {
    Execution _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ExecutionDefaultTypeInternal _Execution_default_instance_;
}  // namespace protobuf
static ::_pb::Metadata file_level_metadata_Execution_2eproto[1];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_Execution_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_Execution_2eproto = nullptr;
const ::uint32_t TableStruct_Execution_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    PROTOBUF_FIELD_OFFSET(::protobuf::Execution, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::protobuf::Execution, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::protobuf::Execution, _impl_.orderid_),
    PROTOBUF_FIELD_OFFSET(::protobuf::Execution, _impl_.execid_),
    PROTOBUF_FIELD_OFFSET(::protobuf::Execution, _impl_.time_),
    PROTOBUF_FIELD_OFFSET(::protobuf::Execution, _impl_.acctnumber_),
    PROTOBUF_FIELD_OFFSET(::protobuf::Execution, _impl_.exchange_),
    PROTOBUF_FIELD_OFFSET(::protobuf::Execution, _impl_.side_),
    PROTOBUF_FIELD_OFFSET(::protobuf::Execution, _impl_.shares_),
    PROTOBUF_FIELD_OFFSET(::protobuf::Execution, _impl_.price_),
    PROTOBUF_FIELD_OFFSET(::protobuf::Execution, _impl_.permid_),
    PROTOBUF_FIELD_OFFSET(::protobuf::Execution, _impl_.clientid_),
    PROTOBUF_FIELD_OFFSET(::protobuf::Execution, _impl_.isliquidation_),
    PROTOBUF_FIELD_OFFSET(::protobuf::Execution, _impl_.cumqty_),
    PROTOBUF_FIELD_OFFSET(::protobuf::Execution, _impl_.avgprice_),
    PROTOBUF_FIELD_OFFSET(::protobuf::Execution, _impl_.orderref_),
    PROTOBUF_FIELD_OFFSET(::protobuf::Execution, _impl_.evrule_),
    PROTOBUF_FIELD_OFFSET(::protobuf::Execution, _impl_.evmultiplier_),
    PROTOBUF_FIELD_OFFSET(::protobuf::Execution, _impl_.modelcode_),
    PROTOBUF_FIELD_OFFSET(::protobuf::Execution, _impl_.lastliquidity_),
    PROTOBUF_FIELD_OFFSET(::protobuf::Execution, _impl_.ispricerevisionpending_),
    PROTOBUF_FIELD_OFFSET(::protobuf::Execution, _impl_.submitter_),
    PROTOBUF_FIELD_OFFSET(::protobuf::Execution, _impl_.optexerciseorlapsetype_),
    11,
    0,
    1,
    2,
    3,
    4,
    5,
    13,
    14,
    12,
    17,
    6,
    15,
    7,
    8,
    16,
    9,
    19,
    18,
    10,
    20,
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        { 0, 29, -1, sizeof(::protobuf::Execution)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::protobuf::_Execution_default_instance_._instance,
};
const char descriptor_table_protodef_Execution_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\017Execution.proto\022\010protobuf\"\257\006\n\tExecutio"
    "n\022\024\n\007orderId\030\001 \001(\005H\000\210\001\001\022\023\n\006execId\030\002 \001(\tH"
    "\001\210\001\001\022\021\n\004time\030\003 \001(\tH\002\210\001\001\022\027\n\nacctNumber\030\004 "
    "\001(\tH\003\210\001\001\022\025\n\010exchange\030\005 \001(\tH\004\210\001\001\022\021\n\004side\030"
    "\006 \001(\tH\005\210\001\001\022\023\n\006shares\030\007 \001(\tH\006\210\001\001\022\022\n\005price"
    "\030\010 \001(\001H\007\210\001\001\022\023\n\006permId\030\t \001(\003H\010\210\001\001\022\025\n\010clie"
    "ntId\030\n \001(\005H\t\210\001\001\022\032\n\risLiquidation\030\013 \001(\010H\n"
    "\210\001\001\022\023\n\006cumQty\030\014 \001(\tH\013\210\001\001\022\025\n\010avgPrice\030\r \001"
    "(\001H\014\210\001\001\022\025\n\010orderRef\030\016 \001(\tH\r\210\001\001\022\023\n\006evRule"
    "\030\017 \001(\tH\016\210\001\001\022\031\n\014evMultiplier\030\020 \001(\001H\017\210\001\001\022\026"
    "\n\tmodelCode\030\021 \001(\tH\020\210\001\001\022\032\n\rlastLiquidity\030"
    "\022 \001(\005H\021\210\001\001\022#\n\026isPriceRevisionPending\030\023 \001"
    "(\010H\022\210\001\001\022\026\n\tsubmitter\030\024 \001(\tH\023\210\001\001\022#\n\026optEx"
    "erciseOrLapseType\030\025 \001(\005H\024\210\001\001B\n\n\010_orderId"
    "B\t\n\007_execIdB\007\n\005_timeB\r\n\013_acctNumberB\013\n\t_"
    "exchangeB\007\n\005_sideB\t\n\007_sharesB\010\n\006_priceB\t"
    "\n\007_permIdB\013\n\t_clientIdB\020\n\016_isLiquidation"
    "B\t\n\007_cumQtyB\013\n\t_avgPriceB\013\n\t_orderRefB\t\n"
    "\007_evRuleB\017\n\r_evMultiplierB\014\n\n_modelCodeB"
    "\020\n\016_lastLiquidityB\031\n\027_isPriceRevisionPen"
    "dingB\014\n\n_submitterB\031\n\027_optExerciseOrLaps"
    "eTypeb\006proto3"
};
static ::absl::once_flag descriptor_table_Execution_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Execution_2eproto = {
    false,
    false,
    853,
    descriptor_table_protodef_Execution_2eproto,
    "Execution.proto",
    &descriptor_table_Execution_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_Execution_2eproto::offsets,
    file_level_metadata_Execution_2eproto,
    file_level_enum_descriptors_Execution_2eproto,
    file_level_service_descriptors_Execution_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Execution_2eproto_getter() {
  return &descriptor_table_Execution_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Execution_2eproto(&descriptor_table_Execution_2eproto);
namespace protobuf {
// ===================================================================

class Execution::_Internal {
 public:
  using HasBits = decltype(std::declval<Execution>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(Execution, _impl_._has_bits_);
  static void set_has_orderid(HasBits* has_bits) {
    (*has_bits)[0] |= 2048u;
  }
  static void set_has_execid(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_time(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_acctnumber(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_exchange(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_side(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static void set_has_shares(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
  static void set_has_price(HasBits* has_bits) {
    (*has_bits)[0] |= 8192u;
  }
  static void set_has_permid(HasBits* has_bits) {
    (*has_bits)[0] |= 16384u;
  }
  static void set_has_clientid(HasBits* has_bits) {
    (*has_bits)[0] |= 4096u;
  }
  static void set_has_isliquidation(HasBits* has_bits) {
    (*has_bits)[0] |= 131072u;
  }
  static void set_has_cumqty(HasBits* has_bits) {
    (*has_bits)[0] |= 64u;
  }
  static void set_has_avgprice(HasBits* has_bits) {
    (*has_bits)[0] |= 32768u;
  }
  static void set_has_orderref(HasBits* has_bits) {
    (*has_bits)[0] |= 128u;
  }
  static void set_has_evrule(HasBits* has_bits) {
    (*has_bits)[0] |= 256u;
  }
  static void set_has_evmultiplier(HasBits* has_bits) {
    (*has_bits)[0] |= 65536u;
  }
  static void set_has_modelcode(HasBits* has_bits) {
    (*has_bits)[0] |= 512u;
  }
  static void set_has_lastliquidity(HasBits* has_bits) {
    (*has_bits)[0] |= 524288u;
  }
  static void set_has_ispricerevisionpending(HasBits* has_bits) {
    (*has_bits)[0] |= 262144u;
  }
  static void set_has_submitter(HasBits* has_bits) {
    (*has_bits)[0] |= 1024u;
  }
  static void set_has_optexerciseorlapsetype(HasBits* has_bits) {
    (*has_bits)[0] |= 1048576u;
  }
};

Execution::Execution(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:protobuf.Execution)
}
Execution::Execution(const Execution& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Execution* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.execid_) {}

    , decltype(_impl_.time_) {}

    , decltype(_impl_.acctnumber_) {}

    , decltype(_impl_.exchange_) {}

    , decltype(_impl_.side_) {}

    , decltype(_impl_.shares_) {}

    , decltype(_impl_.cumqty_) {}

    , decltype(_impl_.orderref_) {}

    , decltype(_impl_.evrule_) {}

    , decltype(_impl_.modelcode_) {}

    , decltype(_impl_.submitter_) {}

    , decltype(_impl_.orderid_) {}

    , decltype(_impl_.clientid_) {}

    , decltype(_impl_.price_) {}

    , decltype(_impl_.permid_) {}

    , decltype(_impl_.avgprice_) {}

    , decltype(_impl_.evmultiplier_) {}

    , decltype(_impl_.isliquidation_) {}

    , decltype(_impl_.ispricerevisionpending_) {}

    , decltype(_impl_.lastliquidity_) {}

    , decltype(_impl_.optexerciseorlapsetype_) {}
  };

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.execid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.execid_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_impl_.execid_.Set(from._internal_execid(), _this->GetArenaForAllocation());
  }
  _impl_.time_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.time_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if ((from._impl_._has_bits_[0] & 0x00000002u) != 0) {
    _this->_impl_.time_.Set(from._internal_time(), _this->GetArenaForAllocation());
  }
  _impl_.acctnumber_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.acctnumber_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if ((from._impl_._has_bits_[0] & 0x00000004u) != 0) {
    _this->_impl_.acctnumber_.Set(from._internal_acctnumber(), _this->GetArenaForAllocation());
  }
  _impl_.exchange_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.exchange_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if ((from._impl_._has_bits_[0] & 0x00000008u) != 0) {
    _this->_impl_.exchange_.Set(from._internal_exchange(), _this->GetArenaForAllocation());
  }
  _impl_.side_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.side_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if ((from._impl_._has_bits_[0] & 0x00000010u) != 0) {
    _this->_impl_.side_.Set(from._internal_side(), _this->GetArenaForAllocation());
  }
  _impl_.shares_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.shares_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if ((from._impl_._has_bits_[0] & 0x00000020u) != 0) {
    _this->_impl_.shares_.Set(from._internal_shares(), _this->GetArenaForAllocation());
  }
  _impl_.cumqty_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.cumqty_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if ((from._impl_._has_bits_[0] & 0x00000040u) != 0) {
    _this->_impl_.cumqty_.Set(from._internal_cumqty(), _this->GetArenaForAllocation());
  }
  _impl_.orderref_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.orderref_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if ((from._impl_._has_bits_[0] & 0x00000080u) != 0) {
    _this->_impl_.orderref_.Set(from._internal_orderref(), _this->GetArenaForAllocation());
  }
  _impl_.evrule_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.evrule_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if ((from._impl_._has_bits_[0] & 0x00000100u) != 0) {
    _this->_impl_.evrule_.Set(from._internal_evrule(), _this->GetArenaForAllocation());
  }
  _impl_.modelcode_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.modelcode_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if ((from._impl_._has_bits_[0] & 0x00000200u) != 0) {
    _this->_impl_.modelcode_.Set(from._internal_modelcode(), _this->GetArenaForAllocation());
  }
  _impl_.submitter_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.submitter_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if ((from._impl_._has_bits_[0] & 0x00000400u) != 0) {
    _this->_impl_.submitter_.Set(from._internal_submitter(), _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.orderid_, &from._impl_.orderid_,
    static_cast<::size_t>(reinterpret_cast<char*>(&_impl_.optexerciseorlapsetype_) -
    reinterpret_cast<char*>(&_impl_.orderid_)) + sizeof(_impl_.optexerciseorlapsetype_));
  // @@protoc_insertion_point(copy_constructor:protobuf.Execution)
}

inline void Execution::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.execid_) {}

    , decltype(_impl_.time_) {}

    , decltype(_impl_.acctnumber_) {}

    , decltype(_impl_.exchange_) {}

    , decltype(_impl_.side_) {}

    , decltype(_impl_.shares_) {}

    , decltype(_impl_.cumqty_) {}

    , decltype(_impl_.orderref_) {}

    , decltype(_impl_.evrule_) {}

    , decltype(_impl_.modelcode_) {}

    , decltype(_impl_.submitter_) {}

    , decltype(_impl_.orderid_) { 0 }

    , decltype(_impl_.clientid_) { 0 }

    , decltype(_impl_.price_) { 0 }

    , decltype(_impl_.permid_) { ::int64_t{0} }

    , decltype(_impl_.avgprice_) { 0 }

    , decltype(_impl_.evmultiplier_) { 0 }

    , decltype(_impl_.isliquidation_) { false }

    , decltype(_impl_.ispricerevisionpending_) { false }

    , decltype(_impl_.lastliquidity_) { 0 }

    , decltype(_impl_.optexerciseorlapsetype_) { 0 }

  };
  _impl_.execid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.execid_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.time_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.time_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.acctnumber_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.acctnumber_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.exchange_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.exchange_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.side_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.side_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.shares_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.shares_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.cumqty_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.cumqty_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.orderref_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.orderref_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.evrule_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.evrule_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.modelcode_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.modelcode_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.submitter_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.submitter_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Execution::~Execution() {
  // @@protoc_insertion_point(destructor:protobuf.Execution)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Execution::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.execid_.Destroy();
  _impl_.time_.Destroy();
  _impl_.acctnumber_.Destroy();
  _impl_.exchange_.Destroy();
  _impl_.side_.Destroy();
  _impl_.shares_.Destroy();
  _impl_.cumqty_.Destroy();
  _impl_.orderref_.Destroy();
  _impl_.evrule_.Destroy();
  _impl_.modelcode_.Destroy();
  _impl_.submitter_.Destroy();
}

void Execution::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Execution::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.Execution)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.execid_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.time_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000004u) {
      _impl_.acctnumber_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000008u) {
      _impl_.exchange_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000010u) {
      _impl_.side_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000020u) {
      _impl_.shares_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000040u) {
      _impl_.cumqty_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000080u) {
      _impl_.orderref_.ClearNonDefaultToEmpty();
    }
  }
  if (cached_has_bits & 0x00000700u) {
    if (cached_has_bits & 0x00000100u) {
      _impl_.evrule_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000200u) {
      _impl_.modelcode_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000400u) {
      _impl_.submitter_.ClearNonDefaultToEmpty();
    }
  }
  if (cached_has_bits & 0x0000f800u) {
    ::memset(&_impl_.orderid_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.avgprice_) -
        reinterpret_cast<char*>(&_impl_.orderid_)) + sizeof(_impl_.avgprice_));
  }
  if (cached_has_bits & 0x001f0000u) {
    ::memset(&_impl_.evmultiplier_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.optexerciseorlapsetype_) -
        reinterpret_cast<char*>(&_impl_.evmultiplier_)) + sizeof(_impl_.optexerciseorlapsetype_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Execution::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional int32 orderId = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 8)) {
          _Internal::set_has_orderid(&has_bits);
          _impl_.orderid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // optional string execId = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_execid();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "protobuf.Execution.execId"));
        } else {
          goto handle_unusual;
        }
        continue;
      // optional string time = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_time();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "protobuf.Execution.time"));
        } else {
          goto handle_unusual;
        }
        continue;
      // optional string acctNumber = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_acctnumber();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "protobuf.Execution.acctNumber"));
        } else {
          goto handle_unusual;
        }
        continue;
      // optional string exchange = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_exchange();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "protobuf.Execution.exchange"));
        } else {
          goto handle_unusual;
        }
        continue;
      // optional string side = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 50)) {
          auto str = _internal_mutable_side();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "protobuf.Execution.side"));
        } else {
          goto handle_unusual;
        }
        continue;
      // optional string shares = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 58)) {
          auto str = _internal_mutable_shares();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "protobuf.Execution.shares"));
        } else {
          goto handle_unusual;
        }
        continue;
      // optional double price = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 65)) {
          _Internal::set_has_price(&has_bits);
          _impl_.price_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else {
          goto handle_unusual;
        }
        continue;
      // optional int64 permId = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 72)) {
          _Internal::set_has_permid(&has_bits);
          _impl_.permid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // optional int32 clientId = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 80)) {
          _Internal::set_has_clientid(&has_bits);
          _impl_.clientid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // optional bool isLiquidation = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 88)) {
          _Internal::set_has_isliquidation(&has_bits);
          _impl_.isliquidation_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // optional string cumQty = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 98)) {
          auto str = _internal_mutable_cumqty();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "protobuf.Execution.cumQty"));
        } else {
          goto handle_unusual;
        }
        continue;
      // optional double avgPrice = 13;
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 105)) {
          _Internal::set_has_avgprice(&has_bits);
          _impl_.avgprice_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else {
          goto handle_unusual;
        }
        continue;
      // optional string orderRef = 14;
      case 14:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 114)) {
          auto str = _internal_mutable_orderref();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "protobuf.Execution.orderRef"));
        } else {
          goto handle_unusual;
        }
        continue;
      // optional string evRule = 15;
      case 15:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 122)) {
          auto str = _internal_mutable_evrule();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "protobuf.Execution.evRule"));
        } else {
          goto handle_unusual;
        }
        continue;
      // optional double evMultiplier = 16;
      case 16:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 129)) {
          _Internal::set_has_evmultiplier(&has_bits);
          _impl_.evmultiplier_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else {
          goto handle_unusual;
        }
        continue;
      // optional string modelCode = 17;
      case 17:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 138)) {
          auto str = _internal_mutable_modelcode();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "protobuf.Execution.modelCode"));
        } else {
          goto handle_unusual;
        }
        continue;
      // optional int32 lastLiquidity = 18;
      case 18:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 144)) {
          _Internal::set_has_lastliquidity(&has_bits);
          _impl_.lastliquidity_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // optional bool isPriceRevisionPending = 19;
      case 19:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 152)) {
          _Internal::set_has_ispricerevisionpending(&has_bits);
          _impl_.ispricerevisionpending_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // optional string submitter = 20;
      case 20:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 162)) {
          auto str = _internal_mutable_submitter();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "protobuf.Execution.submitter"));
        } else {
          goto handle_unusual;
        }
        continue;
      // optional int32 optExerciseOrLapseType = 21;
      case 21:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 168)) {
          _Internal::set_has_optexerciseorlapsetype(&has_bits);
          _impl_.optexerciseorlapsetype_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* Execution::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protobuf.Execution)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional int32 orderId = 1;
  if (cached_has_bits & 0x00000800u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(
        1, this->_internal_orderid(), target);
  }

  // optional string execId = 2;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_execid();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "protobuf.Execution.execId");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // optional string time = 3;
  if (cached_has_bits & 0x00000002u) {
    const std::string& _s = this->_internal_time();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "protobuf.Execution.time");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // optional string acctNumber = 4;
  if (cached_has_bits & 0x00000004u) {
    const std::string& _s = this->_internal_acctnumber();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "protobuf.Execution.acctNumber");
    target = stream->WriteStringMaybeAliased(4, _s, target);
  }

  // optional string exchange = 5;
  if (cached_has_bits & 0x00000008u) {
    const std::string& _s = this->_internal_exchange();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "protobuf.Execution.exchange");
    target = stream->WriteStringMaybeAliased(5, _s, target);
  }

  // optional string side = 6;
  if (cached_has_bits & 0x00000010u) {
    const std::string& _s = this->_internal_side();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "protobuf.Execution.side");
    target = stream->WriteStringMaybeAliased(6, _s, target);
  }

  // optional string shares = 7;
  if (cached_has_bits & 0x00000020u) {
    const std::string& _s = this->_internal_shares();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "protobuf.Execution.shares");
    target = stream->WriteStringMaybeAliased(7, _s, target);
  }

  // optional double price = 8;
  if (cached_has_bits & 0x00002000u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(
        8, this->_internal_price(), target);
  }

  // optional int64 permId = 9;
  if (cached_has_bits & 0x00004000u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(
        9, this->_internal_permid(), target);
  }

  // optional int32 clientId = 10;
  if (cached_has_bits & 0x00001000u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(
        10, this->_internal_clientid(), target);
  }

  // optional bool isLiquidation = 11;
  if (cached_has_bits & 0x00020000u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        11, this->_internal_isliquidation(), target);
  }

  // optional string cumQty = 12;
  if (cached_has_bits & 0x00000040u) {
    const std::string& _s = this->_internal_cumqty();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "protobuf.Execution.cumQty");
    target = stream->WriteStringMaybeAliased(12, _s, target);
  }

  // optional double avgPrice = 13;
  if (cached_has_bits & 0x00008000u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(
        13, this->_internal_avgprice(), target);
  }

  // optional string orderRef = 14;
  if (cached_has_bits & 0x00000080u) {
    const std::string& _s = this->_internal_orderref();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "protobuf.Execution.orderRef");
    target = stream->WriteStringMaybeAliased(14, _s, target);
  }

  // optional string evRule = 15;
  if (cached_has_bits & 0x00000100u) {
    const std::string& _s = this->_internal_evrule();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "protobuf.Execution.evRule");
    target = stream->WriteStringMaybeAliased(15, _s, target);
  }

  // optional double evMultiplier = 16;
  if (cached_has_bits & 0x00010000u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(
        16, this->_internal_evmultiplier(), target);
  }

  // optional string modelCode = 17;
  if (cached_has_bits & 0x00000200u) {
    const std::string& _s = this->_internal_modelcode();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "protobuf.Execution.modelCode");
    target = stream->WriteStringMaybeAliased(17, _s, target);
  }

  // optional int32 lastLiquidity = 18;
  if (cached_has_bits & 0x00080000u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(
        18, this->_internal_lastliquidity(), target);
  }

  // optional bool isPriceRevisionPending = 19;
  if (cached_has_bits & 0x00040000u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        19, this->_internal_ispricerevisionpending(), target);
  }

  // optional string submitter = 20;
  if (cached_has_bits & 0x00000400u) {
    const std::string& _s = this->_internal_submitter();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "protobuf.Execution.submitter");
    target = stream->WriteStringMaybeAliased(20, _s, target);
  }

  // optional int32 optExerciseOrLapseType = 21;
  if (cached_has_bits & 0x00100000u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(
        21, this->_internal_optexerciseorlapsetype(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protobuf.Execution)
  return target;
}

::size_t Execution::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protobuf.Execution)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    // optional string execId = 2;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                      this->_internal_execid());
    }

    // optional string time = 3;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                      this->_internal_time());
    }

    // optional string acctNumber = 4;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                      this->_internal_acctnumber());
    }

    // optional string exchange = 5;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                      this->_internal_exchange());
    }

    // optional string side = 6;
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                      this->_internal_side());
    }

    // optional string shares = 7;
    if (cached_has_bits & 0x00000020u) {
      total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                      this->_internal_shares());
    }

    // optional string cumQty = 12;
    if (cached_has_bits & 0x00000040u) {
      total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                      this->_internal_cumqty());
    }

    // optional string orderRef = 14;
    if (cached_has_bits & 0x00000080u) {
      total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                      this->_internal_orderref());
    }

  }
  if (cached_has_bits & 0x0000ff00u) {
    // optional string evRule = 15;
    if (cached_has_bits & 0x00000100u) {
      total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                      this->_internal_evrule());
    }

    // optional string modelCode = 17;
    if (cached_has_bits & 0x00000200u) {
      total_size += 2 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                      this->_internal_modelcode());
    }

    // optional string submitter = 20;
    if (cached_has_bits & 0x00000400u) {
      total_size += 2 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                      this->_internal_submitter());
    }

    // optional int32 orderId = 1;
    if (cached_has_bits & 0x00000800u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_orderid());
    }

    // optional int32 clientId = 10;
    if (cached_has_bits & 0x00001000u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_clientid());
    }

    // optional double price = 8;
    if (cached_has_bits & 0x00002000u) {
      total_size += 9;
    }

    // optional int64 permId = 9;
    if (cached_has_bits & 0x00004000u) {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
          this->_internal_permid());
    }

    // optional double avgPrice = 13;
    if (cached_has_bits & 0x00008000u) {
      total_size += 9;
    }

  }
  if (cached_has_bits & 0x001f0000u) {
    // optional double evMultiplier = 16;
    if (cached_has_bits & 0x00010000u) {
      total_size += 10;
    }

    // optional bool isLiquidation = 11;
    if (cached_has_bits & 0x00020000u) {
      total_size += 2;
    }

    // optional bool isPriceRevisionPending = 19;
    if (cached_has_bits & 0x00040000u) {
      total_size += 3;
    }

    // optional int32 lastLiquidity = 18;
    if (cached_has_bits & 0x00080000u) {
      total_size += 2 + ::_pbi::WireFormatLite::Int32Size(
                                      this->_internal_lastliquidity());
    }

    // optional int32 optExerciseOrLapseType = 21;
    if (cached_has_bits & 0x00100000u) {
      total_size += 2 + ::_pbi::WireFormatLite::Int32Size(
                                      this->_internal_optexerciseorlapsetype());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Execution::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Execution::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Execution::GetClassData() const { return &_class_data_; }


void Execution::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Execution*>(&to_msg);
  auto& from = static_cast<const Execution&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:protobuf.Execution)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_execid(from._internal_execid());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_time(from._internal_time());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_internal_set_acctnumber(from._internal_acctnumber());
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_internal_set_exchange(from._internal_exchange());
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_internal_set_side(from._internal_side());
    }
    if (cached_has_bits & 0x00000020u) {
      _this->_internal_set_shares(from._internal_shares());
    }
    if (cached_has_bits & 0x00000040u) {
      _this->_internal_set_cumqty(from._internal_cumqty());
    }
    if (cached_has_bits & 0x00000080u) {
      _this->_internal_set_orderref(from._internal_orderref());
    }
  }
  if (cached_has_bits & 0x0000ff00u) {
    if (cached_has_bits & 0x00000100u) {
      _this->_internal_set_evrule(from._internal_evrule());
    }
    if (cached_has_bits & 0x00000200u) {
      _this->_internal_set_modelcode(from._internal_modelcode());
    }
    if (cached_has_bits & 0x00000400u) {
      _this->_internal_set_submitter(from._internal_submitter());
    }
    if (cached_has_bits & 0x00000800u) {
      _this->_impl_.orderid_ = from._impl_.orderid_;
    }
    if (cached_has_bits & 0x00001000u) {
      _this->_impl_.clientid_ = from._impl_.clientid_;
    }
    if (cached_has_bits & 0x00002000u) {
      _this->_impl_.price_ = from._impl_.price_;
    }
    if (cached_has_bits & 0x00004000u) {
      _this->_impl_.permid_ = from._impl_.permid_;
    }
    if (cached_has_bits & 0x00008000u) {
      _this->_impl_.avgprice_ = from._impl_.avgprice_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  if (cached_has_bits & 0x001f0000u) {
    if (cached_has_bits & 0x00010000u) {
      _this->_impl_.evmultiplier_ = from._impl_.evmultiplier_;
    }
    if (cached_has_bits & 0x00020000u) {
      _this->_impl_.isliquidation_ = from._impl_.isliquidation_;
    }
    if (cached_has_bits & 0x00040000u) {
      _this->_impl_.ispricerevisionpending_ = from._impl_.ispricerevisionpending_;
    }
    if (cached_has_bits & 0x00080000u) {
      _this->_impl_.lastliquidity_ = from._impl_.lastliquidity_;
    }
    if (cached_has_bits & 0x00100000u) {
      _this->_impl_.optexerciseorlapsetype_ = from._impl_.optexerciseorlapsetype_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Execution::CopyFrom(const Execution& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.Execution)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Execution::IsInitialized() const {
  return true;
}

void Execution::InternalSwap(Execution* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.execid_, lhs_arena,
                                       &other->_impl_.execid_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.time_, lhs_arena,
                                       &other->_impl_.time_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.acctnumber_, lhs_arena,
                                       &other->_impl_.acctnumber_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.exchange_, lhs_arena,
                                       &other->_impl_.exchange_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.side_, lhs_arena,
                                       &other->_impl_.side_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.shares_, lhs_arena,
                                       &other->_impl_.shares_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.cumqty_, lhs_arena,
                                       &other->_impl_.cumqty_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.orderref_, lhs_arena,
                                       &other->_impl_.orderref_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.evrule_, lhs_arena,
                                       &other->_impl_.evrule_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.modelcode_, lhs_arena,
                                       &other->_impl_.modelcode_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.submitter_, lhs_arena,
                                       &other->_impl_.submitter_, rhs_arena);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Execution, _impl_.optexerciseorlapsetype_)
      + sizeof(Execution::_impl_.optexerciseorlapsetype_)
      - PROTOBUF_FIELD_OFFSET(Execution, _impl_.orderid_)>(
          reinterpret_cast<char*>(&_impl_.orderid_),
          reinterpret_cast<char*>(&other->_impl_.orderid_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Execution::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Execution_2eproto_getter, &descriptor_table_Execution_2eproto_once,
      file_level_metadata_Execution_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::protobuf::Execution*
Arena::CreateMaybeMessage< ::protobuf::Execution >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobuf::Execution >(arena);
}
PROTOBUF_NAMESPACE_CLOSE
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
