// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OrderCancel.proto

#include "OrderCancel.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = ::PROTOBUF_NAMESPACE_ID::internal;
namespace protobuf {
template <typename>
PROTOBUF_CONSTEXPR OrderCancel::OrderCancel(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.manualordercanceltime_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.extoperator_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.manualorderindicator_)*/ 0
} {}
struct OrderCancelDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OrderCancelDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~OrderCancelDefaultTypeInternal() {}
  union {
    OrderCancel _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OrderCancelDefaultTypeInternal _OrderCancel_default_instance_;
}  // namespace protobuf
static ::_pb::Metadata file_level_metadata_OrderCancel_2eproto[1];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_OrderCancel_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_OrderCancel_2eproto = nullptr;
const ::uint32_t TableStruct_OrderCancel_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    PROTOBUF_FIELD_OFFSET(::protobuf::OrderCancel, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::protobuf::OrderCancel, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::protobuf::OrderCancel, _impl_.manualordercanceltime_),
    PROTOBUF_FIELD_OFFSET(::protobuf::OrderCancel, _impl_.extoperator_),
    PROTOBUF_FIELD_OFFSET(::protobuf::OrderCancel, _impl_.manualorderindicator_),
    0,
    1,
    2,
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        { 0, 11, -1, sizeof(::protobuf::OrderCancel)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::protobuf::_OrderCancel_default_instance_._instance,
};
const char descriptor_table_protodef_OrderCancel_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\021OrderCancel.proto\022\010protobuf\"\261\001\n\013OrderC"
    "ancel\022\"\n\025manualOrderCancelTime\030\001 \001(\tH\000\210\001"
    "\001\022\030\n\013extOperator\030\002 \001(\tH\001\210\001\001\022!\n\024manualOrd"
    "erIndicator\030\003 \001(\005H\002\210\001\001B\030\n\026_manualOrderCa"
    "ncelTimeB\016\n\014_extOperatorB\027\n\025_manualOrder"
    "Indicatorb\006proto3"
};
static ::absl::once_flag descriptor_table_OrderCancel_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_OrderCancel_2eproto = {
    false,
    false,
    217,
    descriptor_table_protodef_OrderCancel_2eproto,
    "OrderCancel.proto",
    &descriptor_table_OrderCancel_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_OrderCancel_2eproto::offsets,
    file_level_metadata_OrderCancel_2eproto,
    file_level_enum_descriptors_OrderCancel_2eproto,
    file_level_service_descriptors_OrderCancel_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_OrderCancel_2eproto_getter() {
  return &descriptor_table_OrderCancel_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_OrderCancel_2eproto(&descriptor_table_OrderCancel_2eproto);
namespace protobuf {
// ===================================================================

class OrderCancel::_Internal {
 public:
  using HasBits = decltype(std::declval<OrderCancel>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(OrderCancel, _impl_._has_bits_);
  static void set_has_manualordercanceltime(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_extoperator(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_manualorderindicator(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
};

OrderCancel::OrderCancel(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:protobuf.OrderCancel)
}
OrderCancel::OrderCancel(const OrderCancel& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  OrderCancel* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.manualordercanceltime_) {}

    , decltype(_impl_.extoperator_) {}

    , decltype(_impl_.manualorderindicator_) {}
  };

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.manualordercanceltime_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.manualordercanceltime_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_impl_.manualordercanceltime_.Set(from._internal_manualordercanceltime(), _this->GetArenaForAllocation());
  }
  _impl_.extoperator_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.extoperator_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if ((from._impl_._has_bits_[0] & 0x00000002u) != 0) {
    _this->_impl_.extoperator_.Set(from._internal_extoperator(), _this->GetArenaForAllocation());
  }
  _this->_impl_.manualorderindicator_ = from._impl_.manualorderindicator_;
  // @@protoc_insertion_point(copy_constructor:protobuf.OrderCancel)
}

inline void OrderCancel::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.manualordercanceltime_) {}

    , decltype(_impl_.extoperator_) {}

    , decltype(_impl_.manualorderindicator_) { 0 }

  };
  _impl_.manualordercanceltime_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.manualordercanceltime_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.extoperator_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.extoperator_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

OrderCancel::~OrderCancel() {
  // @@protoc_insertion_point(destructor:protobuf.OrderCancel)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void OrderCancel::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.manualordercanceltime_.Destroy();
  _impl_.extoperator_.Destroy();
}

void OrderCancel::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void OrderCancel::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.OrderCancel)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.manualordercanceltime_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.extoperator_.ClearNonDefaultToEmpty();
    }
  }
  _impl_.manualorderindicator_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* OrderCancel::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional string manualOrderCancelTime = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_manualordercanceltime();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "protobuf.OrderCancel.manualOrderCancelTime"));
        } else {
          goto handle_unusual;
        }
        continue;
      // optional string extOperator = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_extoperator();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "protobuf.OrderCancel.extOperator"));
        } else {
          goto handle_unusual;
        }
        continue;
      // optional int32 manualOrderIndicator = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 24)) {
          _Internal::set_has_manualorderindicator(&has_bits);
          _impl_.manualorderindicator_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* OrderCancel::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protobuf.OrderCancel)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional string manualOrderCancelTime = 1;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_manualordercanceltime();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "protobuf.OrderCancel.manualOrderCancelTime");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // optional string extOperator = 2;
  if (cached_has_bits & 0x00000002u) {
    const std::string& _s = this->_internal_extoperator();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "protobuf.OrderCancel.extOperator");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // optional int32 manualOrderIndicator = 3;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(
        3, this->_internal_manualorderindicator(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protobuf.OrderCancel)
  return target;
}

::size_t OrderCancel::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protobuf.OrderCancel)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    // optional string manualOrderCancelTime = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                      this->_internal_manualordercanceltime());
    }

    // optional string extOperator = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                      this->_internal_extoperator());
    }

    // optional int32 manualOrderIndicator = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_manualorderindicator());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData OrderCancel::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    OrderCancel::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*OrderCancel::GetClassData() const { return &_class_data_; }


void OrderCancel::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<OrderCancel*>(&to_msg);
  auto& from = static_cast<const OrderCancel&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:protobuf.OrderCancel)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_manualordercanceltime(from._internal_manualordercanceltime());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_extoperator(from._internal_extoperator());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.manualorderindicator_ = from._impl_.manualorderindicator_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void OrderCancel::CopyFrom(const OrderCancel& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.OrderCancel)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OrderCancel::IsInitialized() const {
  return true;
}

void OrderCancel::InternalSwap(OrderCancel* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.manualordercanceltime_, lhs_arena,
                                       &other->_impl_.manualordercanceltime_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.extoperator_, lhs_arena,
                                       &other->_impl_.extoperator_, rhs_arena);

  swap(_impl_.manualorderindicator_, other->_impl_.manualorderindicator_);
}

::PROTOBUF_NAMESPACE_ID::Metadata OrderCancel::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_OrderCancel_2eproto_getter, &descriptor_table_OrderCancel_2eproto_once,
      file_level_metadata_OrderCancel_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::protobuf::OrderCancel*
Arena::CreateMaybeMessage< ::protobuf::OrderCancel >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobuf::OrderCancel >(arena);
}
PROTOBUF_NAMESPACE_CLOSE
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
