// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OrderAllocation.proto

#include "OrderAllocation.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = ::PROTOBUF_NAMESPACE_ID::internal;
namespace protobuf {
template <typename>
PROTOBUF_CONSTEXPR OrderAllocation::OrderAllocation(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.account_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.position_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.positiondesired_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.positionafter_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.desiredallocqty_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.allowedallocqty_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.ismonetary_)*/ false
} {}
struct OrderAllocationDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OrderAllocationDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~OrderAllocationDefaultTypeInternal() {}
  union {
    OrderAllocation _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OrderAllocationDefaultTypeInternal _OrderAllocation_default_instance_;
}  // namespace protobuf
static ::_pb::Metadata file_level_metadata_OrderAllocation_2eproto[1];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_OrderAllocation_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_OrderAllocation_2eproto = nullptr;
const ::uint32_t TableStruct_OrderAllocation_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    PROTOBUF_FIELD_OFFSET(::protobuf::OrderAllocation, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::protobuf::OrderAllocation, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::protobuf::OrderAllocation, _impl_.account_),
    PROTOBUF_FIELD_OFFSET(::protobuf::OrderAllocation, _impl_.position_),
    PROTOBUF_FIELD_OFFSET(::protobuf::OrderAllocation, _impl_.positiondesired_),
    PROTOBUF_FIELD_OFFSET(::protobuf::OrderAllocation, _impl_.positionafter_),
    PROTOBUF_FIELD_OFFSET(::protobuf::OrderAllocation, _impl_.desiredallocqty_),
    PROTOBUF_FIELD_OFFSET(::protobuf::OrderAllocation, _impl_.allowedallocqty_),
    PROTOBUF_FIELD_OFFSET(::protobuf::OrderAllocation, _impl_.ismonetary_),
    0,
    1,
    2,
    3,
    4,
    5,
    6,
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        { 0, 15, -1, sizeof(::protobuf::OrderAllocation)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::protobuf::_OrderAllocation_default_instance_._instance,
};
const char descriptor_table_protodef_OrderAllocation_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\025OrderAllocation.proto\022\010protobuf\"\303\002\n\017Or"
    "derAllocation\022\024\n\007account\030\001 \001(\tH\000\210\001\001\022\025\n\010p"
    "osition\030\002 \001(\tH\001\210\001\001\022\034\n\017positionDesired\030\003 "
    "\001(\tH\002\210\001\001\022\032\n\rpositionAfter\030\004 \001(\tH\003\210\001\001\022\034\n\017"
    "desiredAllocQty\030\005 \001(\tH\004\210\001\001\022\034\n\017allowedAll"
    "ocQty\030\006 \001(\tH\005\210\001\001\022\027\n\nisMonetary\030\007 \001(\010H\006\210\001"
    "\001B\n\n\010_accountB\013\n\t_positionB\022\n\020_positionD"
    "esiredB\020\n\016_positionAfterB\022\n\020_desiredAllo"
    "cQtyB\022\n\020_allowedAllocQtyB\r\n\013_isMonetaryb"
    "\006proto3"
};
static ::absl::once_flag descriptor_table_OrderAllocation_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_OrderAllocation_2eproto = {
    false,
    false,
    367,
    descriptor_table_protodef_OrderAllocation_2eproto,
    "OrderAllocation.proto",
    &descriptor_table_OrderAllocation_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_OrderAllocation_2eproto::offsets,
    file_level_metadata_OrderAllocation_2eproto,
    file_level_enum_descriptors_OrderAllocation_2eproto,
    file_level_service_descriptors_OrderAllocation_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_OrderAllocation_2eproto_getter() {
  return &descriptor_table_OrderAllocation_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_OrderAllocation_2eproto(&descriptor_table_OrderAllocation_2eproto);
namespace protobuf {
// ===================================================================

class OrderAllocation::_Internal {
 public:
  using HasBits = decltype(std::declval<OrderAllocation>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(OrderAllocation, _impl_._has_bits_);
  static void set_has_account(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_position(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_positiondesired(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_positionafter(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_desiredallocqty(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static void set_has_allowedallocqty(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
  static void set_has_ismonetary(HasBits* has_bits) {
    (*has_bits)[0] |= 64u;
  }
};

OrderAllocation::OrderAllocation(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:protobuf.OrderAllocation)
}
OrderAllocation::OrderAllocation(const OrderAllocation& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  OrderAllocation* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.account_) {}

    , decltype(_impl_.position_) {}

    , decltype(_impl_.positiondesired_) {}

    , decltype(_impl_.positionafter_) {}

    , decltype(_impl_.desiredallocqty_) {}

    , decltype(_impl_.allowedallocqty_) {}

    , decltype(_impl_.ismonetary_) {}
  };

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.account_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.account_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_impl_.account_.Set(from._internal_account(), _this->GetArenaForAllocation());
  }
  _impl_.position_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.position_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if ((from._impl_._has_bits_[0] & 0x00000002u) != 0) {
    _this->_impl_.position_.Set(from._internal_position(), _this->GetArenaForAllocation());
  }
  _impl_.positiondesired_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.positiondesired_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if ((from._impl_._has_bits_[0] & 0x00000004u) != 0) {
    _this->_impl_.positiondesired_.Set(from._internal_positiondesired(), _this->GetArenaForAllocation());
  }
  _impl_.positionafter_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.positionafter_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if ((from._impl_._has_bits_[0] & 0x00000008u) != 0) {
    _this->_impl_.positionafter_.Set(from._internal_positionafter(), _this->GetArenaForAllocation());
  }
  _impl_.desiredallocqty_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.desiredallocqty_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if ((from._impl_._has_bits_[0] & 0x00000010u) != 0) {
    _this->_impl_.desiredallocqty_.Set(from._internal_desiredallocqty(), _this->GetArenaForAllocation());
  }
  _impl_.allowedallocqty_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.allowedallocqty_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if ((from._impl_._has_bits_[0] & 0x00000020u) != 0) {
    _this->_impl_.allowedallocqty_.Set(from._internal_allowedallocqty(), _this->GetArenaForAllocation());
  }
  _this->_impl_.ismonetary_ = from._impl_.ismonetary_;
  // @@protoc_insertion_point(copy_constructor:protobuf.OrderAllocation)
}

inline void OrderAllocation::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.account_) {}

    , decltype(_impl_.position_) {}

    , decltype(_impl_.positiondesired_) {}

    , decltype(_impl_.positionafter_) {}

    , decltype(_impl_.desiredallocqty_) {}

    , decltype(_impl_.allowedallocqty_) {}

    , decltype(_impl_.ismonetary_) { false }

  };
  _impl_.account_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.account_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.position_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.position_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.positiondesired_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.positiondesired_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.positionafter_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.positionafter_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.desiredallocqty_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.desiredallocqty_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.allowedallocqty_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.allowedallocqty_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

OrderAllocation::~OrderAllocation() {
  // @@protoc_insertion_point(destructor:protobuf.OrderAllocation)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void OrderAllocation::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.account_.Destroy();
  _impl_.position_.Destroy();
  _impl_.positiondesired_.Destroy();
  _impl_.positionafter_.Destroy();
  _impl_.desiredallocqty_.Destroy();
  _impl_.allowedallocqty_.Destroy();
}

void OrderAllocation::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void OrderAllocation::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.OrderAllocation)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.account_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.position_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000004u) {
      _impl_.positiondesired_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000008u) {
      _impl_.positionafter_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000010u) {
      _impl_.desiredallocqty_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000020u) {
      _impl_.allowedallocqty_.ClearNonDefaultToEmpty();
    }
  }
  _impl_.ismonetary_ = false;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* OrderAllocation::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional string account = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_account();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "protobuf.OrderAllocation.account"));
        } else {
          goto handle_unusual;
        }
        continue;
      // optional string position = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_position();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "protobuf.OrderAllocation.position"));
        } else {
          goto handle_unusual;
        }
        continue;
      // optional string positionDesired = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_positiondesired();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "protobuf.OrderAllocation.positionDesired"));
        } else {
          goto handle_unusual;
        }
        continue;
      // optional string positionAfter = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_positionafter();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "protobuf.OrderAllocation.positionAfter"));
        } else {
          goto handle_unusual;
        }
        continue;
      // optional string desiredAllocQty = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_desiredallocqty();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "protobuf.OrderAllocation.desiredAllocQty"));
        } else {
          goto handle_unusual;
        }
        continue;
      // optional string allowedAllocQty = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 50)) {
          auto str = _internal_mutable_allowedallocqty();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "protobuf.OrderAllocation.allowedAllocQty"));
        } else {
          goto handle_unusual;
        }
        continue;
      // optional bool isMonetary = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 56)) {
          _Internal::set_has_ismonetary(&has_bits);
          _impl_.ismonetary_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* OrderAllocation::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protobuf.OrderAllocation)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional string account = 1;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_account();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "protobuf.OrderAllocation.account");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // optional string position = 2;
  if (cached_has_bits & 0x00000002u) {
    const std::string& _s = this->_internal_position();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "protobuf.OrderAllocation.position");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // optional string positionDesired = 3;
  if (cached_has_bits & 0x00000004u) {
    const std::string& _s = this->_internal_positiondesired();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "protobuf.OrderAllocation.positionDesired");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // optional string positionAfter = 4;
  if (cached_has_bits & 0x00000008u) {
    const std::string& _s = this->_internal_positionafter();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "protobuf.OrderAllocation.positionAfter");
    target = stream->WriteStringMaybeAliased(4, _s, target);
  }

  // optional string desiredAllocQty = 5;
  if (cached_has_bits & 0x00000010u) {
    const std::string& _s = this->_internal_desiredallocqty();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "protobuf.OrderAllocation.desiredAllocQty");
    target = stream->WriteStringMaybeAliased(5, _s, target);
  }

  // optional string allowedAllocQty = 6;
  if (cached_has_bits & 0x00000020u) {
    const std::string& _s = this->_internal_allowedallocqty();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "protobuf.OrderAllocation.allowedAllocQty");
    target = stream->WriteStringMaybeAliased(6, _s, target);
  }

  // optional bool isMonetary = 7;
  if (cached_has_bits & 0x00000040u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        7, this->_internal_ismonetary(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protobuf.OrderAllocation)
  return target;
}

::size_t OrderAllocation::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protobuf.OrderAllocation)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000007fu) {
    // optional string account = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                      this->_internal_account());
    }

    // optional string position = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                      this->_internal_position());
    }

    // optional string positionDesired = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                      this->_internal_positiondesired());
    }

    // optional string positionAfter = 4;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                      this->_internal_positionafter());
    }

    // optional string desiredAllocQty = 5;
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                      this->_internal_desiredallocqty());
    }

    // optional string allowedAllocQty = 6;
    if (cached_has_bits & 0x00000020u) {
      total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                      this->_internal_allowedallocqty());
    }

    // optional bool isMonetary = 7;
    if (cached_has_bits & 0x00000040u) {
      total_size += 2;
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData OrderAllocation::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    OrderAllocation::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*OrderAllocation::GetClassData() const { return &_class_data_; }


void OrderAllocation::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<OrderAllocation*>(&to_msg);
  auto& from = static_cast<const OrderAllocation&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:protobuf.OrderAllocation)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000007fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_account(from._internal_account());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_position(from._internal_position());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_internal_set_positiondesired(from._internal_positiondesired());
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_internal_set_positionafter(from._internal_positionafter());
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_internal_set_desiredallocqty(from._internal_desiredallocqty());
    }
    if (cached_has_bits & 0x00000020u) {
      _this->_internal_set_allowedallocqty(from._internal_allowedallocqty());
    }
    if (cached_has_bits & 0x00000040u) {
      _this->_impl_.ismonetary_ = from._impl_.ismonetary_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void OrderAllocation::CopyFrom(const OrderAllocation& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.OrderAllocation)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OrderAllocation::IsInitialized() const {
  return true;
}

void OrderAllocation::InternalSwap(OrderAllocation* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.account_, lhs_arena,
                                       &other->_impl_.account_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.position_, lhs_arena,
                                       &other->_impl_.position_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.positiondesired_, lhs_arena,
                                       &other->_impl_.positiondesired_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.positionafter_, lhs_arena,
                                       &other->_impl_.positionafter_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.desiredallocqty_, lhs_arena,
                                       &other->_impl_.desiredallocqty_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.allowedallocqty_, lhs_arena,
                                       &other->_impl_.allowedallocqty_, rhs_arena);

  swap(_impl_.ismonetary_, other->_impl_.ismonetary_);
}

::PROTOBUF_NAMESPACE_ID::Metadata OrderAllocation::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_OrderAllocation_2eproto_getter, &descriptor_table_OrderAllocation_2eproto_once,
      file_level_metadata_OrderAllocation_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::protobuf::OrderAllocation*
Arena::CreateMaybeMessage< ::protobuf::OrderAllocation >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobuf::OrderAllocation >(arena);
}
PROTOBUF_NAMESPACE_CLOSE
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
