// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OrderCondition.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_OrderCondition_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_OrderCondition_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4023000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4023004 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_OrderCondition_2eproto

PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_OrderCondition_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable
    descriptor_table_OrderCondition_2eproto;
namespace protobuf {
class OrderCondition;
struct OrderConditionDefaultTypeInternal;
extern OrderConditionDefaultTypeInternal _OrderCondition_default_instance_;
}  // namespace protobuf
PROTOBUF_NAMESPACE_OPEN
template <>
::protobuf::OrderCondition* Arena::CreateMaybeMessage<::protobuf::OrderCondition>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

namespace protobuf {

// ===================================================================


// -------------------------------------------------------------------

class OrderCondition final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protobuf.OrderCondition) */ {
 public:
  inline OrderCondition() : OrderCondition(nullptr) {}
  ~OrderCondition() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR OrderCondition(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  OrderCondition(const OrderCondition& from);
  OrderCondition(OrderCondition&& from) noexcept
    : OrderCondition() {
    *this = ::std::move(from);
  }

  inline OrderCondition& operator=(const OrderCondition& from) {
    CopyFrom(from);
    return *this;
  }
  inline OrderCondition& operator=(OrderCondition&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const OrderCondition& default_instance() {
    return *internal_default_instance();
  }
  static inline const OrderCondition* internal_default_instance() {
    return reinterpret_cast<const OrderCondition*>(
               &_OrderCondition_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(OrderCondition& a, OrderCondition& b) {
    a.Swap(&b);
  }
  inline void Swap(OrderCondition* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OrderCondition* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  OrderCondition* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<OrderCondition>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const OrderCondition& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const OrderCondition& from) {
    OrderCondition::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(OrderCondition* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "protobuf.OrderCondition";
  }
  protected:
  explicit OrderCondition(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kExchangeFieldNumber = 5,
    kSymbolFieldNumber = 6,
    kSecTypeFieldNumber = 7,
    kTimeFieldNumber = 12,
    kTypeFieldNumber = 1,
    kIsConjunctionConnectionFieldNumber = 2,
    kIsMoreFieldNumber = 3,
    kConIdFieldNumber = 4,
    kPercentFieldNumber = 8,
    kChangePercentFieldNumber = 9,
    kPriceFieldNumber = 10,
    kTriggerMethodFieldNumber = 11,
    kVolumeFieldNumber = 13,
  };
  // optional string exchange = 5;
  bool has_exchange() const;
  void clear_exchange() ;
  const std::string& exchange() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_exchange(Arg_&& arg, Args_... args);
  std::string* mutable_exchange();
  PROTOBUF_NODISCARD std::string* release_exchange();
  void set_allocated_exchange(std::string* ptr);

  private:
  const std::string& _internal_exchange() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_exchange(
      const std::string& value);
  std::string* _internal_mutable_exchange();

  public:
  // optional string symbol = 6;
  bool has_symbol() const;
  void clear_symbol() ;
  const std::string& symbol() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_symbol(Arg_&& arg, Args_... args);
  std::string* mutable_symbol();
  PROTOBUF_NODISCARD std::string* release_symbol();
  void set_allocated_symbol(std::string* ptr);

  private:
  const std::string& _internal_symbol() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_symbol(
      const std::string& value);
  std::string* _internal_mutable_symbol();

  public:
  // optional string secType = 7;
  bool has_sectype() const;
  void clear_sectype() ;
  const std::string& sectype() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_sectype(Arg_&& arg, Args_... args);
  std::string* mutable_sectype();
  PROTOBUF_NODISCARD std::string* release_sectype();
  void set_allocated_sectype(std::string* ptr);

  private:
  const std::string& _internal_sectype() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sectype(
      const std::string& value);
  std::string* _internal_mutable_sectype();

  public:
  // optional string time = 12;
  bool has_time() const;
  void clear_time() ;
  const std::string& time() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_time(Arg_&& arg, Args_... args);
  std::string* mutable_time();
  PROTOBUF_NODISCARD std::string* release_time();
  void set_allocated_time(std::string* ptr);

  private:
  const std::string& _internal_time() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_time(
      const std::string& value);
  std::string* _internal_mutable_time();

  public:
  // optional int32 type = 1;
  bool has_type() const;
  void clear_type() ;
  ::int32_t type() const;
  void set_type(::int32_t value);

  private:
  ::int32_t _internal_type() const;
  void _internal_set_type(::int32_t value);

  public:
  // optional bool isConjunctionConnection = 2;
  bool has_isconjunctionconnection() const;
  void clear_isconjunctionconnection() ;
  bool isconjunctionconnection() const;
  void set_isconjunctionconnection(bool value);

  private:
  bool _internal_isconjunctionconnection() const;
  void _internal_set_isconjunctionconnection(bool value);

  public:
  // optional bool isMore = 3;
  bool has_ismore() const;
  void clear_ismore() ;
  bool ismore() const;
  void set_ismore(bool value);

  private:
  bool _internal_ismore() const;
  void _internal_set_ismore(bool value);

  public:
  // optional int32 conId = 4;
  bool has_conid() const;
  void clear_conid() ;
  ::int32_t conid() const;
  void set_conid(::int32_t value);

  private:
  ::int32_t _internal_conid() const;
  void _internal_set_conid(::int32_t value);

  public:
  // optional int32 percent = 8;
  bool has_percent() const;
  void clear_percent() ;
  ::int32_t percent() const;
  void set_percent(::int32_t value);

  private:
  ::int32_t _internal_percent() const;
  void _internal_set_percent(::int32_t value);

  public:
  // optional double changePercent = 9;
  bool has_changepercent() const;
  void clear_changepercent() ;
  double changepercent() const;
  void set_changepercent(double value);

  private:
  double _internal_changepercent() const;
  void _internal_set_changepercent(double value);

  public:
  // optional double price = 10;
  bool has_price() const;
  void clear_price() ;
  double price() const;
  void set_price(double value);

  private:
  double _internal_price() const;
  void _internal_set_price(double value);

  public:
  // optional int32 triggerMethod = 11;
  bool has_triggermethod() const;
  void clear_triggermethod() ;
  ::int32_t triggermethod() const;
  void set_triggermethod(::int32_t value);

  private:
  ::int32_t _internal_triggermethod() const;
  void _internal_set_triggermethod(::int32_t value);

  public:
  // optional int32 volume = 13;
  bool has_volume() const;
  void clear_volume() ;
  ::int32_t volume() const;
  void set_volume(::int32_t value);

  private:
  ::int32_t _internal_volume() const;
  void _internal_set_volume(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:protobuf.OrderCondition)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr exchange_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr symbol_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sectype_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr time_;
    ::int32_t type_;
    bool isconjunctionconnection_;
    bool ismore_;
    ::int32_t conid_;
    ::int32_t percent_;
    double changepercent_;
    double price_;
    ::int32_t triggermethod_;
    ::int32_t volume_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_OrderCondition_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// OrderCondition

// optional int32 type = 1;
inline bool OrderCondition::has_type() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline void OrderCondition::clear_type() {
  _impl_.type_ = 0;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline ::int32_t OrderCondition::type() const {
  // @@protoc_insertion_point(field_get:protobuf.OrderCondition.type)
  return _internal_type();
}
inline void OrderCondition::set_type(::int32_t value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:protobuf.OrderCondition.type)
}
inline ::int32_t OrderCondition::_internal_type() const {
  return _impl_.type_;
}
inline void OrderCondition::_internal_set_type(::int32_t value) {
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.type_ = value;
}

// optional bool isConjunctionConnection = 2;
inline bool OrderCondition::has_isconjunctionconnection() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline void OrderCondition::clear_isconjunctionconnection() {
  _impl_.isconjunctionconnection_ = false;
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline bool OrderCondition::isconjunctionconnection() const {
  // @@protoc_insertion_point(field_get:protobuf.OrderCondition.isConjunctionConnection)
  return _internal_isconjunctionconnection();
}
inline void OrderCondition::set_isconjunctionconnection(bool value) {
  _internal_set_isconjunctionconnection(value);
  // @@protoc_insertion_point(field_set:protobuf.OrderCondition.isConjunctionConnection)
}
inline bool OrderCondition::_internal_isconjunctionconnection() const {
  return _impl_.isconjunctionconnection_;
}
inline void OrderCondition::_internal_set_isconjunctionconnection(bool value) {
  _impl_._has_bits_[0] |= 0x00000020u;
  _impl_.isconjunctionconnection_ = value;
}

// optional bool isMore = 3;
inline bool OrderCondition::has_ismore() const {
  bool value = (_impl_._has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline void OrderCondition::clear_ismore() {
  _impl_.ismore_ = false;
  _impl_._has_bits_[0] &= ~0x00000040u;
}
inline bool OrderCondition::ismore() const {
  // @@protoc_insertion_point(field_get:protobuf.OrderCondition.isMore)
  return _internal_ismore();
}
inline void OrderCondition::set_ismore(bool value) {
  _internal_set_ismore(value);
  // @@protoc_insertion_point(field_set:protobuf.OrderCondition.isMore)
}
inline bool OrderCondition::_internal_ismore() const {
  return _impl_.ismore_;
}
inline void OrderCondition::_internal_set_ismore(bool value) {
  _impl_._has_bits_[0] |= 0x00000040u;
  _impl_.ismore_ = value;
}

// optional int32 conId = 4;
inline bool OrderCondition::has_conid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline void OrderCondition::clear_conid() {
  _impl_.conid_ = 0;
  _impl_._has_bits_[0] &= ~0x00000080u;
}
inline ::int32_t OrderCondition::conid() const {
  // @@protoc_insertion_point(field_get:protobuf.OrderCondition.conId)
  return _internal_conid();
}
inline void OrderCondition::set_conid(::int32_t value) {
  _internal_set_conid(value);
  // @@protoc_insertion_point(field_set:protobuf.OrderCondition.conId)
}
inline ::int32_t OrderCondition::_internal_conid() const {
  return _impl_.conid_;
}
inline void OrderCondition::_internal_set_conid(::int32_t value) {
  _impl_._has_bits_[0] |= 0x00000080u;
  _impl_.conid_ = value;
}

// optional string exchange = 5;
inline bool OrderCondition::has_exchange() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void OrderCondition::clear_exchange() {
  _impl_.exchange_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& OrderCondition::exchange() const {
  // @@protoc_insertion_point(field_get:protobuf.OrderCondition.exchange)
  return _internal_exchange();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void OrderCondition::set_exchange(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.exchange_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.OrderCondition.exchange)
}
inline std::string* OrderCondition::mutable_exchange() {
  std::string* _s = _internal_mutable_exchange();
  // @@protoc_insertion_point(field_mutable:protobuf.OrderCondition.exchange)
  return _s;
}
inline const std::string& OrderCondition::_internal_exchange() const {
  return _impl_.exchange_.Get();
}
inline void OrderCondition::_internal_set_exchange(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;


  _impl_.exchange_.Set(value, GetArenaForAllocation());
}
inline std::string* OrderCondition::_internal_mutable_exchange() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.exchange_.Mutable( GetArenaForAllocation());
}
inline std::string* OrderCondition::release_exchange() {
  // @@protoc_insertion_point(field_release:protobuf.OrderCondition.exchange)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.exchange_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.exchange_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void OrderCondition::set_allocated_exchange(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.exchange_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.exchange_.IsDefault()) {
          _impl_.exchange_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.OrderCondition.exchange)
}

// optional string symbol = 6;
inline bool OrderCondition::has_symbol() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void OrderCondition::clear_symbol() {
  _impl_.symbol_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& OrderCondition::symbol() const {
  // @@protoc_insertion_point(field_get:protobuf.OrderCondition.symbol)
  return _internal_symbol();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void OrderCondition::set_symbol(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.symbol_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.OrderCondition.symbol)
}
inline std::string* OrderCondition::mutable_symbol() {
  std::string* _s = _internal_mutable_symbol();
  // @@protoc_insertion_point(field_mutable:protobuf.OrderCondition.symbol)
  return _s;
}
inline const std::string& OrderCondition::_internal_symbol() const {
  return _impl_.symbol_.Get();
}
inline void OrderCondition::_internal_set_symbol(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000002u;


  _impl_.symbol_.Set(value, GetArenaForAllocation());
}
inline std::string* OrderCondition::_internal_mutable_symbol() {
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.symbol_.Mutable( GetArenaForAllocation());
}
inline std::string* OrderCondition::release_symbol() {
  // @@protoc_insertion_point(field_release:protobuf.OrderCondition.symbol)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.symbol_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.symbol_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void OrderCondition::set_allocated_symbol(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.symbol_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.symbol_.IsDefault()) {
          _impl_.symbol_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.OrderCondition.symbol)
}

// optional string secType = 7;
inline bool OrderCondition::has_sectype() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void OrderCondition::clear_sectype() {
  _impl_.sectype_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const std::string& OrderCondition::sectype() const {
  // @@protoc_insertion_point(field_get:protobuf.OrderCondition.secType)
  return _internal_sectype();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void OrderCondition::set_sectype(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.sectype_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.OrderCondition.secType)
}
inline std::string* OrderCondition::mutable_sectype() {
  std::string* _s = _internal_mutable_sectype();
  // @@protoc_insertion_point(field_mutable:protobuf.OrderCondition.secType)
  return _s;
}
inline const std::string& OrderCondition::_internal_sectype() const {
  return _impl_.sectype_.Get();
}
inline void OrderCondition::_internal_set_sectype(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000004u;


  _impl_.sectype_.Set(value, GetArenaForAllocation());
}
inline std::string* OrderCondition::_internal_mutable_sectype() {
  _impl_._has_bits_[0] |= 0x00000004u;
  return _impl_.sectype_.Mutable( GetArenaForAllocation());
}
inline std::string* OrderCondition::release_sectype() {
  // @@protoc_insertion_point(field_release:protobuf.OrderCondition.secType)
  if ((_impl_._has_bits_[0] & 0x00000004u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004u;
  auto* released = _impl_.sectype_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.sectype_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void OrderCondition::set_allocated_sectype(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.sectype_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.sectype_.IsDefault()) {
          _impl_.sectype_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.OrderCondition.secType)
}

// optional int32 percent = 8;
inline bool OrderCondition::has_percent() const {
  bool value = (_impl_._has_bits_[0] & 0x00000100u) != 0;
  return value;
}
inline void OrderCondition::clear_percent() {
  _impl_.percent_ = 0;
  _impl_._has_bits_[0] &= ~0x00000100u;
}
inline ::int32_t OrderCondition::percent() const {
  // @@protoc_insertion_point(field_get:protobuf.OrderCondition.percent)
  return _internal_percent();
}
inline void OrderCondition::set_percent(::int32_t value) {
  _internal_set_percent(value);
  // @@protoc_insertion_point(field_set:protobuf.OrderCondition.percent)
}
inline ::int32_t OrderCondition::_internal_percent() const {
  return _impl_.percent_;
}
inline void OrderCondition::_internal_set_percent(::int32_t value) {
  _impl_._has_bits_[0] |= 0x00000100u;
  _impl_.percent_ = value;
}

// optional double changePercent = 9;
inline bool OrderCondition::has_changepercent() const {
  bool value = (_impl_._has_bits_[0] & 0x00000200u) != 0;
  return value;
}
inline void OrderCondition::clear_changepercent() {
  _impl_.changepercent_ = 0;
  _impl_._has_bits_[0] &= ~0x00000200u;
}
inline double OrderCondition::changepercent() const {
  // @@protoc_insertion_point(field_get:protobuf.OrderCondition.changePercent)
  return _internal_changepercent();
}
inline void OrderCondition::set_changepercent(double value) {
  _internal_set_changepercent(value);
  // @@protoc_insertion_point(field_set:protobuf.OrderCondition.changePercent)
}
inline double OrderCondition::_internal_changepercent() const {
  return _impl_.changepercent_;
}
inline void OrderCondition::_internal_set_changepercent(double value) {
  _impl_._has_bits_[0] |= 0x00000200u;
  _impl_.changepercent_ = value;
}

// optional double price = 10;
inline bool OrderCondition::has_price() const {
  bool value = (_impl_._has_bits_[0] & 0x00000400u) != 0;
  return value;
}
inline void OrderCondition::clear_price() {
  _impl_.price_ = 0;
  _impl_._has_bits_[0] &= ~0x00000400u;
}
inline double OrderCondition::price() const {
  // @@protoc_insertion_point(field_get:protobuf.OrderCondition.price)
  return _internal_price();
}
inline void OrderCondition::set_price(double value) {
  _internal_set_price(value);
  // @@protoc_insertion_point(field_set:protobuf.OrderCondition.price)
}
inline double OrderCondition::_internal_price() const {
  return _impl_.price_;
}
inline void OrderCondition::_internal_set_price(double value) {
  _impl_._has_bits_[0] |= 0x00000400u;
  _impl_.price_ = value;
}

// optional int32 triggerMethod = 11;
inline bool OrderCondition::has_triggermethod() const {
  bool value = (_impl_._has_bits_[0] & 0x00000800u) != 0;
  return value;
}
inline void OrderCondition::clear_triggermethod() {
  _impl_.triggermethod_ = 0;
  _impl_._has_bits_[0] &= ~0x00000800u;
}
inline ::int32_t OrderCondition::triggermethod() const {
  // @@protoc_insertion_point(field_get:protobuf.OrderCondition.triggerMethod)
  return _internal_triggermethod();
}
inline void OrderCondition::set_triggermethod(::int32_t value) {
  _internal_set_triggermethod(value);
  // @@protoc_insertion_point(field_set:protobuf.OrderCondition.triggerMethod)
}
inline ::int32_t OrderCondition::_internal_triggermethod() const {
  return _impl_.triggermethod_;
}
inline void OrderCondition::_internal_set_triggermethod(::int32_t value) {
  _impl_._has_bits_[0] |= 0x00000800u;
  _impl_.triggermethod_ = value;
}

// optional string time = 12;
inline bool OrderCondition::has_time() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void OrderCondition::clear_time() {
  _impl_.time_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline const std::string& OrderCondition::time() const {
  // @@protoc_insertion_point(field_get:protobuf.OrderCondition.time)
  return _internal_time();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void OrderCondition::set_time(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.time_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:protobuf.OrderCondition.time)
}
inline std::string* OrderCondition::mutable_time() {
  std::string* _s = _internal_mutable_time();
  // @@protoc_insertion_point(field_mutable:protobuf.OrderCondition.time)
  return _s;
}
inline const std::string& OrderCondition::_internal_time() const {
  return _impl_.time_.Get();
}
inline void OrderCondition::_internal_set_time(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000008u;


  _impl_.time_.Set(value, GetArenaForAllocation());
}
inline std::string* OrderCondition::_internal_mutable_time() {
  _impl_._has_bits_[0] |= 0x00000008u;
  return _impl_.time_.Mutable( GetArenaForAllocation());
}
inline std::string* OrderCondition::release_time() {
  // @@protoc_insertion_point(field_release:protobuf.OrderCondition.time)
  if ((_impl_._has_bits_[0] & 0x00000008u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000008u;
  auto* released = _impl_.time_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.time_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void OrderCondition::set_allocated_time(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  _impl_.time_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.time_.IsDefault()) {
          _impl_.time_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:protobuf.OrderCondition.time)
}

// optional int32 volume = 13;
inline bool OrderCondition::has_volume() const {
  bool value = (_impl_._has_bits_[0] & 0x00001000u) != 0;
  return value;
}
inline void OrderCondition::clear_volume() {
  _impl_.volume_ = 0;
  _impl_._has_bits_[0] &= ~0x00001000u;
}
inline ::int32_t OrderCondition::volume() const {
  // @@protoc_insertion_point(field_get:protobuf.OrderCondition.volume)
  return _internal_volume();
}
inline void OrderCondition::set_volume(::int32_t value) {
  _internal_set_volume(value);
  // @@protoc_insertion_point(field_set:protobuf.OrderCondition.volume)
}
inline ::int32_t OrderCondition::_internal_volume() const {
  return _impl_.volume_;
}
inline void OrderCondition::_internal_set_volume(::int32_t value) {
  _impl_._has_bits_[0] |= 0x00001000u;
  _impl_.volume_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_OrderCondition_2eproto_2epb_2eh
